### ISSUE TITLE
async/await syntax in lambda not working

### ISSUE THREAD

**Issue by fredericbarthelet** [aws/aws-iot-device-sdk-js-v2#100]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

I found a similar issue but the symptoms look different #58 
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
Using `aws-iot-device-sdk-js-v2` within the context of an AWS lambda with `async/await` syntax does not work. `await` statements for `connection.connect()`, `identity.subscribeToCreateCertificateFromCsrAccepted`, `identity.subscribeToCreateCertificateFromCsrRejected` and `identity.publishCreateCertificateFromCsr` seems ineffective.

**SDK version number**
1.3.1

**Platform/OS/Hardware/Device**
AWS lambda on nodejs12.x runtime, no custom layer

**To Reproduce (observed behavior)**

Deploying the following code to a lambda :
```js
'use strict';

// NOTE: `aws-iot-device-sdk-v2` is bundled into the deployment package
// eslint-disable-next-line import/no-unresolved
const { mqtt, io, iot, iotidentity } = require('aws-iot-device-sdk-v2');

async function registerDevice(event) {
  io.enable_logging(io.LogLevel.INFO);
  const clientBootstrap = new io.ClientBootstrap();
  const client = new mqtt.MqttClient(clientBootstrap);

  const configBuilder = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder(
    event.certificatePem,
    event.keyPair.PrivateKey
  );
  configBuilder.with_clean_session(false);
  configBuilder.with_client_id(`test-${Math.floor(Math.random() * 100000000)}`);
  configBuilder.with_endpoint('xxxxINTENTIONALLY_ANONYMISEDxxx-ats.iot.us-east-1.amazonaws.com');
  const config = configBuilder.build();

  const connection = client.new_connection(config);

  const identity = new iotidentity.IotIdentityClient(connection);

  await new Promise(resolve => setTimeout(resolve, 3000));

  console.log('waited 3 seconds')

  await connection.connect();

  console.log('connected')

  await identity.subscribeToCreateCertificateFromCsrAccepted({}, mqtt.QoS.AtLeastOnce);

  await identity.subscribeToCreateCertificateFromCsrRejected({}, mqtt.QoS.AtLeastOnce);

  await identity.publishCreateCertificateFromCsr({ csr: '' }, mqtt.QoS.AtLeastOnce);

  return 'success';
}
```

Running the lambda with response of `createProvisioningClaim` as input event prints the `waited 3 seconds` statement - showing async/await does seems to work, no syntax error there - but not the `connected` statement. A few info statement are shown, showing execution of connect did in fact started. However, the lambda runs just over 3s (the timeout period) and then resolve. No `success` string is returned from the lambda execution.

Running the same code on my machine nodejs runtime shows no problem at all.

**Expected behavior**
Resolving promises from `connection.connect()` and other asynchronous calls.

**Logs/output**
![image](https://user-images.githubusercontent.com/23530626/95240740-26979f00-080d-11eb-89cd-96e7af54ba07.png)

**Additional context**
The reason for executing this code in an lambda environment is for integration testing purposes.
Currently developing iot fleet provisioning pre-provision lambda hook as part of Serverless framework feature.
Lambda aims to simulate a device requesting provisioning via template provisioning feature (CSR) on a freshly deployed CloudFormation stack.

Current state of the PR : https://github.com/serverless/serverless/pull/8324

**Comment by RianFuro** [comment]
Huh, I'm facing a similar issue right now, in a different context. The call to `await connection.connect()` does not resolve for me, UNLESS express starts.

In essence, this works:
```javascript
const app = express()
app.listen(port, () => {
    console.log(`Server is up at port ${port}`)
    connection.connect().then(() => console.log('connected!'))
});
```
while this does not:
```javascript
const app = express()
connection.connect().then(() => {
    console.log('connected!')
    app.listen(port, () => {
       console.log(`Server is up at port ${port}`)
    });
})
```

In the latter case the promise returned from `connection.connect()` never resolves, the *then* callback is never called.
Removing express from my application does not solve the issue, so I don't believe it's the cause. Also, no error is raised from a promise rejection.

I'm working on my local environment:
Arch Linux 5.9.14-arch1-1
nodejs v15.5.0

**Comment by JonathanHenson** [comment]
I think the issue is most likely because connection.connect() does not take a reference to the V8 event-loop and when the line app.listen is executed asynchronously all references are gone and the application completes before the connection.connect() has had a chance to run. 

You see the reverse behavior in the 2nd option, because app.listen takes a reference to the event-loop when the closure is created, and thus it keeps the application alive until after the connection completes.

One easy work around is to throw a timer into the application (or a loop or something)

**Comment by RianFuro** [comment]
@JonathanHenson My application doesn't terminate though. In both cases the application stays alive, but in the first case, the promise to `connection.connect()` resolves (the log in the following statement is printed), while in the second it doesn't.

**Comment by jmklix** [comment]
@fredericbarthelet when using the latest version of the sdk are you still not able the use async/await in lambdas?
