### ISSUE TITLE
Maybe you should tell people to add iotConnect Action to their policy?

### ISSUE THREAD

**Issue by snobu** [aws/aws-iot-device-sdk-js-v2#101]
Don't know, would be nice for others not to waste hours to .. you know, connect?
  
```
 "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:eu-central-1:XXXXXXX:client/YourDeviceName",
      ]
```

The exception being thrown if you don't have `iotConnect` in the policy is also as meaningful as a drunk goose fighting trigonometry.

```
CrtError: Failed to connect: libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP
The connection was closed unexpectedly
```

**Comment by TingDaoK** [comment]
For connection with AWS IoT core, we don't have the detail from the server about the reason the connection lost. So, you will need to check the log from server for the detail. But, yeah, the error information is not informative. Added more information. Thank you for pointing it out!

**Comment by eduardosanzb** [comment]
@snobu thank you so much for the tip!!!
This line was life-saver! 
`        "arn:aws:iot:eu-central-1:XXXXXXX:client/YourDeviceName",`
