### ISSUE TITLE
AWS_ERROR_MQTT_CONNECTION_SHUTDOWN

### ISSUE THREAD

**Issue by EyalSi** [aws/aws-iot-device-sdk-js-v2#102]
I'm getting the following error when trying to run the pub_sub example.
Went over the  Troubleshootin tutorial, but the problem consist:

Does someone has an idea?

events.js:291
      throw er; // Unhandled 'error' event
      ^

CrtError: Failed to subscribe: libaws-c-mqtt: AWS_ERROR_MQTT_CONNECTION_SHUTDOWN, MQTT operation interrupted by connection shutdown.
    at /home/pi/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/native/mqtt.js:331:36
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on MqttClientConnection instance at:
    at MqttClientConnection.emit (/home/pi/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/common/event.js:75:22)
    at /home/pi/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/native/mqtt.js:331:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  error: 'Failed to subscribe: libaws-c-mqtt: AWS_ERROR_MQTT_CONNECTION_SHUTDOWN, MQTT operation interrupted by connection shutdown.',
  error_code: undefined,
  error_name: undefined
}

**Comment by bretambrose** [comment]
"Failed to subscribe: libaws-c-mqtt" hints that the problem may be an issue with the IAM policy associated with the credentials you are using (AWS credentials for websockets, x509 cert for direct mqtt).  Have you checked to see if your policy allows that subscribe operation?
