### ISSUE TITLE
How can connect the mqtt client in a ecs fragate instance?

### ISSUE THREAD

**Issue by joaspacce** [aws/aws-iot-device-sdk-js-v2#106]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?
In Node 10
**Describe the question**
I have a code connecting to the mqtt client in my development environment, but in ecs is throwing an error of credentials not provided. It should not use the task role credentials? Or I'm missing something??

Thanks

**Comment by jmklix** [comment]
It sounds like you might be missing the credentials for the IoT devices. If you haven't already you will need to go to the AWS Management Console > IoT Core > Onboard > Get started. The connection kit  will download a script to install and run the v1 device-example. It will also have credentials needed to connect to AWS IoT. You can use these to for the v2 pub_sub.

node dist/index.js --endpoint <endpoint> --root-ca <file> --cert <file> --key <file>

If you are still having problems please respond with your OS, what error message you are getting, and what you are trying to do when you get it.
