### ISSUE TITLE
How to integrate 'aws-iot-device-sdk-js-v2' into react native?

### ISSUE THREAD

**Issue by FrozenPyrozen** [aws/aws-iot-device-sdk-js-v2#112]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?
React native

**Describe the question**
How I can integrate it with react native?

**Comment by jmklix** [comment]
I noticed you commented that the [v1 doesn't work with tls auth](https://github.com/aws/aws-iot-device-sdk-js/issues/86#issuecomment-738045905). Have you tried similar steps from that issue while using the aws-iot-device-sdk-js-v2? If so what errors have you run into?

**Comment by FrozenPyrozen** [comment]
I'm trying to follow https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pub_sub/index.ts#L165 example, but it's quite hard to understand for me, v1 workflow was easier)
![image](https://user-images.githubusercontent.com/38257513/101153014-80a9ba80-362c-11eb-9951-0217f730d079.png)

**Comment by jmklix** [comment]
@FrozenPyrozen I don't know how much I can help you with react native, but I will try to help you as much as possible.

The specific line you linked is for
```
/**
* Overrides the default system trust store.
* @param ca_dirpath - Only used on Unix-style systems where all trust anchors are
* stored in a directory (e.g. /etc/ssl/certs).
* @param ca_filepath - Single file containing all trust CAs, in PEM format
*/
with_certificate_authority_from_path(ca_dirpath?: string, ca_filepath?: string): this;
```

What parts of the example don't you understand?

**Comment by FrozenPyrozen** [comment]
@jmklix I’m not sure that code for node.is would work in react native for 100%, so I’m using rewriting some library with Mobile Native modules and it’s working with tls auth https://github.com/FrozenPyrozen/rn-native-mqtt

**Comment by jmklix** [comment]
Sorry, I couldn't be more helpful. Are there any questions you still have about this sdk? If not I will close this issue.

**Comment by FrozenPyrozen** [comment]
Yes, you can close)

**Comment by sidd2217** [comment]
@FrozenPyrozen  
Hi, 
Did you found a way to solve this issue later?
As I'm stuck on the same.

**Comment by FrozenPyrozen** [comment]
@sidd2217 try to use https://github.com/FrozenPyrozen/rn-native-mqtt , it worked for me year ago

**Comment by avinashsahoo** [comment]
> @sidd2217 try to use https://github.com/FrozenPyrozen/rn-native-mqtt , it worked for me year ago

It's not working anymore. Too many compile time error for iOS.

**Comment by avinashsahoo** [comment]
> @FrozenPyrozen
> Hi,
> Did you found a way to solve this issue later?
> As I'm stuck on the same.

Did you find any solution to this ?

**Comment by sidd2217** [comment]
> 

Nope, I went with another method.
Create a API gateway and pass data to it and it triggers a lambda function with the data included.
You can call that API gateway directly from react native.
