### ISSUE TITLE
All exemples contain setTimeout to keep node alive, why?

### ISSUE THREAD

**Issue by fredericbarthelet** [aws/aws-iot-device-sdk-js-v2#115]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**

All 3 exemples in this repository cope with `connection = client.new_connection(config);` using a `setTimeout` function rather than relying on async/await syntax with Promises. The comment above the setTimeout line indicates `force node to wait 60 seconds before killing itself, promises do not keep node alive`. I tried removing this timer and rely only on promises, and I do in fact see that removing this line does not await for any code to compile. How come this is not working ? Why is it necessary to start an arbitrary 60s thread to prevent node from thinking execution is completed ?

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/426fd196dcf3cead75e67b1010b863a14dd8eabd/samples/node/pub_sub/index.ts#L174

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/426fd196dcf3cead75e67b1010b863a14dd8eabd/samples/node/fleet_provisioning/index.ts#L312

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/426fd196dcf3cead75e67b1010b863a14dd8eabd/samples/node/basic_discovery/index.ts#L201

**SDK version number** 1.3.3

**Platform/OS/Hardware/Device**
Mac OS & Lambda

**To Reproduce (observed behavior)**
I used exactly the code from `fleet_provisioning` sample, removing the `setTimeout` line

**Expected behavior**
I expect `new_connection` to actually return a connection

**Logs/output**
No log output

**Comment by bretambrose** [comment]
If the samples were real programs doing real other things, it probably wouldn't be necessary, as those "other things" would keep node going.  But as it stands, the samples are a bit of command line parsing followed by a few async operations via promises.  Assuming the comment is correct and promises don't keep node alive, something needs to while the async operations complete.

**Comment by fredericbarthelet** [comment]
Thanks for your reply @bretambrose. The use of Promises and async/await syntax usually prevents proceeding with next instruction until required work is completed and the promise resolves, or an error happens, the promise rejects and an exception is thrown.

I'm very interested with alternative suggestions if you manage to gather some of them :)

**Comment by jpdev33** [comment]
Seconding this issue. Creating a test script that simply creates a `DiscoveryClient` and calls `discover` illustrates the issue perfectly. The Node process exits before the `discover` result resolves or rejects.

**Comment by jmklix** [comment]
Closing this issue because it is old and hasn't had any comments in the past year. 

As far as alternative solutions you don't really need to use the timeouts as mentioned by bretambrose. Your program can go do other things instead of waiting the the promise to resolve
