### ISSUE TITLE
MQTT connection is not resumed when access point is taken offline for a period of time

### ISSUE THREAD

**Issue by jarredkenny** [aws/aws-iot-device-sdk-js-v2#117]
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**

The AWS IOT SDK does not continue to receive messages on subscribed topics if the device's network is powered for a period of time and then restored. The SDK does however reconnect to the broker, as we see a device presence event on the reserved presence topic.

The scenario is which this fails consistently for us is when we physically powered down the wireless access point the device is connected to for a period of time. This seems to be a different scenario then simply disconnecting the device from the network for a period of time. When we disconnect from the device and reconnect, things seems to work. However, when powering down our AP for a period of time we see this failure.

In an attempt to make this work, I tried having our code resubscribe to its MQTT topics when we detect we are back online, but this has not worked for us either .

We have with_clean_session: false in our configuration, so I would expect the MQTT subscriptions to resume in either case.

Here are debug logs from the SDK capturing the time period in which the network goes down and back up. When the network comes back online the SDK appears to reconnect, but will never receive messages on its MQTT subscriptions.

[aws_iot_stdout.log](https://github.com/aws/aws-iot-device-sdk-js-v2/files/5688995/aws_iot_stdout.log)

**SDK version number**
aws-crt 1.3.2
aws-iot-device-sdk-v2 1.3.2

**Platform/OS/Hardware/Device**
Debian 10 x86

**Comment by jules-ofs** [comment]
I am also seeing this.  We have a device that subscribes to shadow topics.  When there is a short network outage - device reconnects.  After this no shadow messages are received.

**Comment by jmklix** [comment]
I haven't been able to reproduce this. Do you have a ballpark for what length of time causes it to no longer reconnect?

Also are you testing this with just the pubsub? or a modified example?

**Comment by hpgmiskin** [comment]
We are experiencing the same issue when there are network issues that occur for longer than 1 hour.

1. When the connection is resumed after < 1 hour of network issues `session_present` is `true`
2. When the connection is resumed after > 1 hour of network issues `session_present` is `false`

It seems that the `session_present` value indicates if the previous subscriptions are lost. 

There is a note in [aws-iot-device-sdk-python-v2 documentation](https://aws.github.io/aws-iot-device-sdk-python-v2/awsiot/mqtt_connection_builder.html#module-awsiot.mqtt_connection_builder) that if `session_present` is `false` then there is a need to resubscribe to topics.

> Note that the server has forgotten all previous subscriptions if this is False. Subscriptions can be re-established via resubscribe_existing_topics().

However, I cannot find this method available in the JS SDK. 

1. Will manually subscribing to topics work following a loss of session?
2. Are there any plans to provide the `resubscribe_existing_topics` method in the JS SDK?

This loss of subscription feels a little bit like an anti-pattern for a communication technology designed for use in poor internet connectivity environments.

**Comment by raRaRa** [comment]
@jarredkenny @hpgmiskin Did you ever find a solution to this problem?
