### ISSUE TITLE
README needs work

### ISSUE THREAD

**Issue by bretambrose** [aws/aws-iot-device-sdk-js-v2#12]
Update with

* install instructions
* build from scratch instructions
* how to run the samples

**Comment by KaibaLopez** [comment]
Hi @bretambrose ,
thanks for pointing this out, we'll work on this.

**Comment by cyrusadkisson** [comment]
Just saw the "new version" message on the old repo and need to incorporate this new version into my product before launch (several months away). I'm very much interested in seeing this documentation so I can get started on the migration.
