### ISSUE TITLE
Connect aws iot device using aws-iot-device-sdk-v2 and aws-cognito

### ISSUE THREAD

**Issue by indranilatwork** [aws/aws-iot-device-sdk-js-v2#129]
Using aws-iot-device-sdk-v2 package in a node.js app I am trying to connect new Iot device.

When using static credentials aws-iot-device-sdk-v2 package is working fine and giving proper response.

const { mqtt, io, iot } = require('aws-iot-device-sdk-v2');

    const CONFIG = {
      endpoint: '****',
      key: 'path_.pem.key',
      cert: 'path_.pem.crt',
      client_id: 'sdk-nodejs-v2',
      topic: '$aws/things/+/shadow/update/accepted',
      verbosity: 'none',
      ca_file: 'path_.pem.txt',  
    }

    class IoT {
      constructor () {
        this.logging();
        this.connect();
      }

      logging () {
        if (CONFIG.verbosity != 'none') {
          const level = parseInt(io.LogLevel[CONFIG.verbosity.toUpperCase()]);
          io.enable_logging(level);
        }
      }

      async connect () {
        var clientID = 'webapp-' +  new Date().getTime();

        const client_bootstrap = new io.ClientBootstrap();
        const config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path(CONFIG.cert, CONFIG.key);
        config_builder.with_certificate_authority_from_path(undefined, CONFIG.ca_file);

        config_builder.with_clean_session(false);
        config_builder.with_client_id(clientID);
        config_builder.with_endpoint(CONFIG.endpoint);
 
        // Keep node running forever
        setInterval(() => {}, 1 << 30);

        const config = config_builder.build();
        const client = new mqtt.MqttClient(client_bootstrap);
        const connection = client.new_connection(config);

        await connection.connect();
        await this.subscribe(connection);
      }

      async subscribe (connection) {
        await connection.subscribe(CONFIG.topic, mqtt.QoS.AtLeastOnce, (topic, payload) => {
    
          try {
            console.log('Got message: ', topic);
          } catch(_) {}
        });
      }
    }

    module.exports = IoT;

But for the when I am doing runtime login using aws cognito.

    var authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails({username:***, password:***});
          var userPool = new AmazonCognitoIdentity.CognitoUserPool({userpoolId,clientId});
          var cognitoUser = new AmazonCognitoIdentity.CognitoUser({userName,userpool});
          var login = {};
          var accessToken,
            loginKey;
          cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: function (result) {
              accessToken = result.getAccessToken().getJwtToken();
              loginKey = ***;
              login[loginKey] = result.getIdToken().getJwtToken();
              AWS.config.update({
                credentials: new AWS.CognitoIdentityCredentials({
                  IdentityPoolId: ***,
                  Logins: login
                }),
                region: ***
              });
              AWS.config.credentials.refresh((error) => {
                if (error) {
                  console.error(error);
                } else {
                  console.log('Successfully logged!');
                  ;
                }
              });
            },
            onFailure: function (err) {
              console.log(err);
            }
          });
          
The cognito login was successful. But then I was trying to use the aws config from cognito to connect the aws iot device, I was trying to pass AWS.config.credentials from cognito as argument in iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder. But getting error: TypeError: certificate must be a String (or convertible to a String). I have not find out any proper document how to use the cognito config in this aws-iot-device-sdk-v2.

Earlier I used aws-iot-device-sdk and followed https://aws.amazon.com/blogs/iot/configuring-cognito-user-pools-to-communicate-with-aws-iot-core/ and it worked for me. 

But with this new aws-iot-device-sdk-v2 I have not able to figure out the way out till now.

![Screenshot+from+2021-01-27+13-57-25](https://user-images.githubusercontent.com/3873634/106445401-fc957700-64a4-11eb-8ce4-22b3abd21555.png)

**Comment by jmklix** [comment]
As mentioned [here](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/70) we don't currently support Cognito with this v2 sdk. I'm going to change this to a feature-request so we can make sure to update you when we have implemented it.

**Comment by indranilatwork** [comment]
@jmklix As you mentioned currently Cognito is not supported with this v2 sdk. So if I don't want to use static certificate and want to use cognito auth for users to get data for aws iot device, is it recommended to use  aws-iot-device-sdk-js?

Is there any chance the v1 sdk will be deprecated in near future as we have a v2 sdk?

**Comment by matriedel** [comment]
@jmklix As you mentioned Cognito is not supported with this v2 SDK what would be your proposal combining Cognito credentials with IoT?

**Comment by jmklix** [comment]
Yes, for now you should use aws-iot-device-sdk-js if you are looking to use Cognito. The v1 will not be depreciated until after there is feature parity between v1 and v2.

**Comment by jfloodnet** [comment]
It looks like this PR uses `with_credentials` in the builder to achieve this now. Does that mean cognito credentials now work with this library? https://github.com/aws/aws-iot-device-sdk-js-v2/pull/225/files#diff-ba753f320915714f4ab3ea17dc9cd2b4806299903a543ed8b0fa1754d662dcd0R59

**Comment by jmklix** [comment]
This should now work and we have added a sample to show you how to use it: [Browser pub/sub](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples#browser-pubsub). Please let us know if you have any questions with how to use cognito
