### ISSUE TITLE
Issue using AwsIotMqttConnectionConfigBuilder.new_mtls_builder(cert: string, private_key: string) to create MQTT connection

### ISSUE THREAD

**Issue by ConnorGitHubAccount** [aws/aws-iot-device-sdk-js-v2#132]
I am currently developing an ios app that uses ionc 5 and angular 9. I am trying to intialize an mqtt connection to the IoT core like this
```
let config = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder(String(args.cert_string), String(args.private_string))
    .with_clean_session(false)
    .with_client_id(this.globals.getVariable("applicationID"))
    .with_endpoint(this.globals.getVariable("aws_endpoint"))
    .with_keep_alive_seconds(6)
    .build();
let client_bootstrap = new io.ClientBootstrap();
let client = new mqtt.MqttClient(client_bootstrap);
let connection = client.new_connection(config);
connection.connect().then((session_present) => {
    console.log("Aws iot connection successful, resuming session:", session_present);
}).catch((error) => {
    console.log("MQTT initialization error:", error);
});
```
But I am getting this error 
```
MQTT initialization error: TypeError: Cannot read property 'aws_access_id' of undefined
    at create_websocket_url (ws.js:78)
    at Object.create_websocket_stream (ws.js:91)
    at MqttClient.create_websocket_stream [as streamBuilder] (mqtt.js:224)
    at MqttClient._setupStream (client.js:298)
    at new MqttClient (client.js:277)
    at new MqttClientConnection (mqtt.js:233)
    at MqttClient.new_connection (mqtt.js:110)
    at SkalaControlWebsocket.ts:1590
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4629)
```
I am referencing this documentation https://aws.github.io/aws-iot-device-sdk-js-v2/classes/aws_crt.awsiotmqttconnectionconfigbuilder.html. I cannot seem use AwsIotMqttConnectionConfigBuilder.new_mtls_builder to initialize an mqtt client where the certificate and private key are strings. I have made sure that they are in PEM format. Any help would be greatly appreciated.
Thanks

**Comment by jmklix** [comment]
Have you taken a look at this similar issue? https://github.com/aws/aws-iot-device-sdk-js-v2/issues/77

**Comment by ConnorGitHubAccount** [comment]
Hi @jmklix I appreciate the quick response time. Yes I have seen #77 and am able to create a MQTT connection the with the `AwsIotMqttConnectionConfigBuilder.new_with_websockets()` method shown toward the bottom of the post. The only thing about his method is the authentication uses IAM credentials(AWS Access Key Id, AWS Secret access key, and AWS session token). I would like to establish a connection using strings in PEM format of certificate and private key pairs provided by the IoT core. This would be much much more preferable for our application.

**Comment by anselpeters** [comment]
were you able to make any progress here?  I am facing a similar situation where we have a devices using certificates/PK but we need to use the newer v2 SDK which has proxy support.

**Comment by ConnorGitHubAccount** [comment]
No, I was not...

**Comment by bretambrose** [comment]
If you're using nodejs then you can make certificate-based mqtt connections to IoT core, but if you're not, your only option is websockets.
