### ISSUE TITLE
Specifying retain false causes disconnect

### ISSUE THREAD

**Issue by Kilowhisky** [aws/aws-iot-device-sdk-js-v2#133]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
If you issue a publish with the last parameter `retain` set to `false` it will cause the connection to terminate and reconnect over and over and over again (see with trace logging on). The AWS IoT core documentation states that only if you pass `true` would the connection be disconnected.

> The MQTT specification provides a provision for the publisher to request that the broker retain the last message sent to a topic and send it to all future topic subscribers. AWS IoT doesn't support retained messages. If a request is made to retain messages, the connection is disconnected.

https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html 

**SDK version number**

```
"aws-iot-device-sdk-v2": "^1.3.6"
```

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
Use the basic pub_sub example but change line 130 from. 

```
connection.publish(argv.topic, json, mqtt.QoS.AtLeastOnce);
```
 
to 

```
connection.publish(argv.topic, json, mqtt.QoS.AtLeastOnce, false);
```

**Expected behavior**
This should be the same behavior as not passing the parameter at all.

**Comment by bretambrose** [comment]
Apologies for the very belated response.  Regressing this, it appears to be working now, possibly in conjunction with the retained support that was released earlier.  Please reopen if you're still seeing an issue.
