### ISSUE TITLE
Topic or filter is invalid when trying subscribe to a topic containing hash (#)

### ISSUE THREAD

**Issue by gattasrikanth** [aws/aws-iot-device-sdk-js-v2#141]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
Subscribe to `--topic m2c2/#`
Subscribing to a topic with # is throwing an error message saying `Topic or filter is invalid`

**SDK version number**
`1.4.1`
**Platform/OS/Hardware/Device**
What are you running the sdk on?
`Mac OS BigSur Version 11.2.3 (20D91)`
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Run the sample under `pub_sub/index.js` with all required keys/certs etc.
Ex: `node dist/index.js --key key --cert cert --topic m2c2/#`
Add topic as `m2c2/#`

**Expected behavior**
Should be able to subscribe without any errors.
Working fine when hash is removed from the topic.

**Logs/output**
```events.js:292
      throw er; // Unhandled 'error' event
      ^

CrtError: Error: libaws-c-mqtt: AWS_ERROR_MQTT_INVALID_TOPIC, Topic or filter is invalid.
    at /Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:333:36
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on MqttClientConnection instance at:
    at MqttClientConnection.emit (/Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/common/event.js:75:22)
    at /Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:333:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  error: Error: libaws-c-mqtt: AWS_ERROR_MQTT_INVALID_TOPIC, Topic or filter is invalid.
      at /Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:229:39
      at new Promise (<anonymous>)
      at MqttClientConnection.<anonymous> (/Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:215:20)
      at Generator.next (<anonymous>)
      at /Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:27:12)
      at MqttClientConnection.publish (/Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-crt/dist/native/mqtt.js:214:16)
      at /Users/s/Downloads/aws-iot-samples/aws-iot-device-sdk-js-v2/samples/node/pub_sub/dist/index.js:135:36
      at Generator.next (<anonymous>) {
    code: 'Topic or filter is invalid.'
  },
  error_code: undefined,
  error_name: undefined
}
```

**Additional context**
Working fine IoT AWS console, and also in the v1 sdk.

**Comment by bretambrose** [comment]
The error is not being thrown by the subscribe, it's being thrown by the publish since the sample takes the topic and uses it for both subscribe and publish operations and a publish to a wildcard is not allowed.

There is a related bug that should be fixed shortly where wildcard subscriptions would result in message received callbacks where the topic was the wildcard and not the specific topic that message was published to: https://github.com/awslabs/aws-crt-nodejs/pull/217

That issue should be fixed in a release in the near future.
