### ISSUE TITLE
Iot Client cannot setup due to error

### ISSUE THREAD

**Issue by sunhubs** [aws/aws-iot-device-sdk-js-v2#142]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Just use nodejs 14
**Describe the question**
I initiate the mqtt in below way, similar as the sample code of pub_sub.ts:
proxy_options = undefined
this.config_builder = iot.iot.AwsIotMqttConnectionConfigBuilder.new_websocket_builder({
      region: 'us-east-1',
      credentials_provider: iot.auth.AwsCredentialsProvider.newDefault(this.client_bootstrap),
      proxy_options: proxy_options
    })
but always get the following issue:

**N-API call failed: napi_get_value_int32(env, node_error_code, &error_code)
    @ /codebuild/output/src388857601/src/aws-crt-nodejs/source/mqtt_client_connection.c:515: napi_number_expected**
[INFO] [2021-03-11T05:58:40Z] [00007f2a60db5740] [dns] - id=0x511ed00: Initializing default host resolver with 64 max host entries.
[INFO] [2021-03-11T05:58:40Z] [00007f2a60db5740] [channel-bootstrap] - id=0x512bf60: Initializing client bootstrap with event-loop group 0x5135460
[DEBUG] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Creating profile collection from file at "/root/.aws/config"
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Parsing aws profile line in profile "<None>", current property: "<None>"
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Parsing aws profile line in profile "default", current property: "<None>"
[DEBUG] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Creating profile collection from file at "/root/.aws/credentials"
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Parsing aws profile line in profile "<None>", current property: "<None>"
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Parsing aws profile line in profile "default", current property: "<None>"
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - Parsing aws profile line in profile "default", current property: "aws_access_key_id"
[WARN] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - property "region" has value "" replaced during merge
[WARN] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - property "aws_access_key_id" has value "" replaced during merge
[WARN] [2021-03-11T05:58:40Z] [00007f2a60db5740] [AuthProfile] - property "aws_secret_access_key" has value "" replaced during merge
[INFO] [2021-03-11T05:58:40Z] [00007f2a60db5740] [Unknown] - id=0x50ac4a0: Successfully created
[INFO] [2021-03-11T05:58:40Z] [00007f2a60db5740] [exp-backoff-strategy] - id=0x50acbc0: Initializing exponential backoff retry strategy with scale factor: 0 jitter mode: 0 and max retries 1
[WARN] [2021-03-11T05:58:40Z] [00007f2a60db5740] [tls-handler] - ctx: X.509 validation has been disabled. If this is not running in a test environment, this is likely a security vulnerability.
[DEBUG] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - client=0x50acb90: Initalizing MQTT client
[DEBUG] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Creating new connection
[DEBUG] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-topic-tree] - tree=0x5123f08: Creating new topic tree
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Setting connection interrupted and resumed handlers
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Setting username and password
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Using websockets
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Setting on_any_publish handler
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Opening connection
[DEBUG] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Begin connecting process, switch state to CONNECTING.
[INFO] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: using ping timeout of 3000000000 ns
[TRACE] [2021-03-11T05:58:40Z] [00007f2a60db5740] [mqtt-client] - id=0x5123cb0: Transforming websocket handshake request.
**Mar 11 05:58:40 sg-controller[1] ERROR: caught unhandled rejection: TypeError: error_code must be a number or undefined
    at Function.<anonymous> (/node_modules/aws-crt/dist/native/aws_iot.js:106:21)**
    at Generator.throw (<anonymous>)
    at rejected (/node_modules/aws-crt/dist/native/aws_iot.js:25:65)

would you please help why this issue happen, and give a guide about how to use the Mqtt on websocket?

**Comment by sunhubs** [comment]
there is another crash log:
Signal received: -1263631500, errno: 32585
################################################################################
Resolved stacktrace:
################################################################################
0x00007f49b49b91d3: ?? ??:0
0x00000000000a3a53: s_print_stack_trace at module.c:?
0x00000000000110e0: __restore_rt at ??:?
node(EVP_MD_CTX_clear_flags+0x5) [0x15ca3d5]
node(EVP_DigestInit_ex+0x1e) [0x15b517e]
node(HMAC_Init_ex+0x189) [0x15d4589]
0x00007f49b49ad11a: ?? ??:0
0x00007f49b49abbe9: ?? ??:0
0x00007f49b48eaa12: ?? ??:0
0x00007f49b48eac4f: ?? ??:0
0x00000000000e9a9b: s_aws_signing_on_get_credentials at signing.c:?
0x00000000000df540: s_aws_provider_default_chain_callback at credentials_provider_default_chain.c:?
0x00000000000f2dcd: s_cached_credentials_provider_get_credentials_async_callback at credentials_provider_cached.c:?
0x00000000000f3317: s_aws_provider_chain_member_callback at credentials_provider_chain.c:?
0x00000000000e17de: s_profile_file_credentials_provider_get_credentials_async at credentials_provider_profile.c:?
0x00000000000e0f20: s_credentials_provider_environment_get_credentials_async at credentials_provider_environment.c:?
0x00000000000f36b9: s_credentials_provider_chain_get_credentials_async at credentials_provider_chain.c:?
0x00000000000f2ac6: s_cached_credentials_provider_get_credentials_async at credentials_provider_cached.c:?
0x00000000000df43e: s_credentials_provider_default_chain_get_credentials_async at credentials_provider_default_chain.c:?
0x00007f49b48f5c1e: ?? ??:0
0x0000000000098807: s_aws_sign_request at auth.c:?
0x00000000000998da: s_method_call at class_binder.c:?
node() [0x9b8c6f]
node() [0xbe571b]
node() [0xbe6cc6]
node(_ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE+0x16) [0xbe7346]
node() [0x14012d9]
################################################################################
Raw stacktrace:
################################################################################
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_backtrace_print+0x53) [0x7f49b49b91d3]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xa3a53) [0x7f49b48afa53]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0) [0x7f49b79e00e0]
node(EVP_MD_CTX_clear_flags+0x5) [0x15ca3d5]
node(EVP_DigestInit_ex+0x1e) [0x15b517e]
node(HMAC_Init_ex+0x189) [0x15d4589]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_sha256_hmac_default_new+0x8a) [0x7f49b49ad11a]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_sha256_hmac_compute+0x19) [0x7f49b49abbe9]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(s_calculate_signature_value+0x262) [0x7f49b48eaa12]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_signing_build_authorization_value+0x4f) [0x7f49b48eac4f]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xe9a9b) [0x7f49b48f5a9b]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xdf540) [0x7f49b48eb540]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xf2dcd) [0x7f49b48fedcd]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xf3317) [0x7f49b48ff317]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xe17de) [0x7f49b48ed7de]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xe0f20) [0x7f49b48ecf20]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xf36b9) [0x7f49b48ff6b9]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xf2ac6) [0x7f49b48feac6]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xdf43e) [0x7f49b48eb43e]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_sign_request_aws+0x8e) [0x7f49b48f5c1e]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x98807) [0x7f49b48a4807]
/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0x998da) [0x7f49b48a58da]
node() [0x9b8c6f]
node() [0xbe571b]
node() [0xbe6cc6]
node(_ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE+0x16) [0xbe7346]
node() [0x14012d9]
root@centos-7:/# command terminated with exit code 137

**Comment by jmklix** [comment]
In the code snippet that you included you have `iot` twice on the config_builder line 

``` js
this.config_builder = iot.iot.AwsIotMqttConnectionConfigBuilder.new_websocket_builder({
// above is what you have and below is what it should be
this.config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_websocket_builder({
```

Please let me know if you are still getting this error. Also if you haven't already make sure you can run the unmodified pub sub first.

**Comment by sunhubs** [comment]
hi jmklix, 
    this is not the issue, the iot is just the package name I used, it should be similar as iotsdk, so it contains iot, mqtt, http sub-modules as you know.
    And after check and test:
    the first issue may be caused by there is a wrong AKSK/aws crenditial is used, but the error log is not so clear.
    the second issue is caused by the latest aws-iot-sdk-js-v2 1.4.1 with aws-crt 1.5.2, if i rollback to aws-iot-sdk-js-v2 1.3.6 with aws-crt 1.3.9, it is able to connect. So **please help check the issue with new version.**
    and then I continue to test the mqtt over websocket with ccproxy 8.0, it is ok for http proxy without authentication, but it fails for http proxy with authentication, configure and error details are as below:

{"client_id":"9ba5f790-1843-48b8-a9c7-*","host_name":"*-ats.iot.us-east-1.amazonaws.com","socket_options":{"handle":{}},"port":443,"use_websocket":true,"clean_session":false,"username":"?SDK=NodeJSv2&Version=1.3.8","tls_ctx":{"handle":{}},"proxy_options":{"host_name":"192.168.0.98","port":8080,"auth_method":1,"auth_username":"proxy","auth_password":"proxy"}}
new connection initiate
events.js:292
      throw er; // Unhandled 'error' event
      ^

CrtError: Failed to connect: aws-c-http: AWS_ERROR_HTTP_PROXY_TLS_CONNECT_FAILED, Proxy tls connection establishment failed because the CONNECT call failed
    at /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/native/mqtt.js:333:36
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Emitted 'error' event on MqttClientConnection instance at:
    at MqttClientConnection.emit (/root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/common/event.js:75:22)
    at /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/native/mqtt.js:333:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  error: 'Failed to connect: aws-c-http: AWS_ERROR_HTTP_PROXY_TLS_CONNECT_FAILED, Proxy tls connection establishment failed because the CONNECT call failed',
  error_code: undefined,
  error_name: undefined
}
    I am not sure it is a bug of sdk or proxy, please help identify this from sdk side. Thanks.

**Comment by sunhubs** [comment]
updating
i use the python sdk to connect to the same proxy, it works.
I capture the package to see that the proxy is asking the client to provide authentication, so it seems to be a bug of sdk that proxy authentication setting does not work well. please help check from sdk side.

**Comment by sunhubs** [comment]
debugger strack for auth issue
++++++++++++++
debug> s
< N-API call failed: napi_new_instance(env, constructor, 0, NULL, result)
<     @ /codebuild/output/src143007243/src/aws-crt-nodejs/source/class_binder.c:480: napi_pending_exception
< N-API call failed: aws_napi_http_message_wrap(env, args->request, &params[0])
<     @ /codebuild/output/src143007243/src/aws-crt-nodejs/source/mqtt_client_connection.c:535: napi_pending_exception
< Fatal error condition occurred in /codebuild/output/src143007243/src/aws-crt-nodejs/source/mqtt_client_connection.c:535: aws_napi_http_message_wrap(env, args->request, &params[0])
< Exiting Application
< ################################################################################
< Resolved stacktrace:
< ################################################################################
< 0x00007fc8a3b91123: ?? ??:0
< 0x00007fc8a3b85f44: ?? ??:0
< 0x00000000000a4a46: s_transform_websocket_call 于 mqtt_client_connection.c:?
< 0x00000000009d4d28: _ZN6v8impl12_GLOBAL__N_118ThreadSafeFunction6IdleCbEP9uv_idle_s 于 node_api.cc:?
< 0x0000000001383c79: uv__run_idle 于 loop-watcher.c:68 (discriminator 6)
< 0x000000000137c5f0: uv_run 于 core.c:379
< 0x00000000009a4b28: _ZN4node11Environment14CleanupHandlesEv 于 ??:?
< 0x00000000009a9dc6: _ZN4node11Environment10RunCleanupEv 于 ??:?
< 0x000000000096d547: _ZN4node15FreeEnvironmentEPNS_11EnvironmentE 于 ??:?
< 0x0000000000a4483f: _ZN4node16NodeMainInstance3RunEv 于 ??:?
< 0x00000000009d1e15: _ZN4node5StartEiPPc 于 ??:?
< 0x00007fc8b31a2555: ?? ??:0
< 0x00000000009694cc: _start 于 ??:?
< ################################################################################
< Raw stacktrace:
< ################################################################################
< /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_backtrace_print+0x53) [0x7fc8a3b91123]
< /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_fatal_assert+0x44) [0x7fc8a3b85f44]
< /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xa4a46) [0x7fc8a3a8ea46]
< /usr/bin/node() [0x9d4d28]
< /usr/bin/node() [0x1383c79]
< /usr/bin/node(uv_run+0x2f0) [0x137c5f0]
< /usr/bin/node(_ZN4node11Environment14CleanupHandlesEv+0x138) [0x9a4b28]
< /usr/bin/node(_ZN4node11Environment10RunCleanupEv+0x56) [0x9a9dc6]
< /usr/bin/node(_ZN4node15FreeEnvironmentEPNS_11EnvironmentE+0x47) [0x96d547]
< /usr/bin/node(_ZN4node16NodeMainInstance3RunEv+0x10f) [0xa4483f]
< /usr/bin/node(_ZN4node5StartEiPPc+0x115) [0x9d1e15]
< /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fc8b31a2555]
< /usr/bin/node() [0x9694cc]

**Comment by sunhubs** [comment]
inspect debugger track for auth issue
++++++++++++
debug> s
< N-API call failed: napi_new_instance(env, constructor, 0, NULL, result)
<     @ /codebuild/output/src143007243/src/aws-crt-nodejs/source/class_binder.c:480: napi_pending_exception
< N-API call failed: aws_napi_http_message_wrap(env, args->request, &params[0])
<     @ /codebuild/output/src143007243/src/aws-crt-nodejs/source/mqtt_client_connection.c:535: napi_pending_exception
< Fatal error condition occurred in /codebuild/output/src143007243/src/aws-crt-nodejs/source/mqtt_client_connection.c:535: aws_napi_http_message_wrap(env, args->request, &params[0])
< Exiting Application
< ################################################################################
< Resolved stacktrace:
< ################################################################################
< 0x00007fc8a3b91123: ?? ??:0
< 0x00007fc8a3b85f44: ?? ??:0
< 0x00000000000a4a46: s_transform_websocket_call 于 mqtt_client_connection.c:?
< 0x00000000009d4d28: _ZN6v8impl12_GLOBAL__N_118ThreadSafeFunction6IdleCbEP9uv_idle_s 于 node_api.cc:?
< 0x0000000001383c79: uv__run_idle 于 loop-watcher.c:68 (discriminator 6)
< 0x000000000137c5f0: uv_run 于 core.c:379
< 0x00000000009a4b28: _ZN4node11Environment14CleanupHandlesEv 于 ??:?
< 0x00000000009a9dc6: _ZN4node11Environment10RunCleanupEv 于 ??:?
< 0x000000000096d547: _ZN4node15FreeEnvironmentEPNS_11EnvironmentE 于 ??:?
< 0x0000000000a4483f: _ZN4node16NodeMainInstance3RunEv 于 ??:?
< 0x00000000009d1e15: _ZN4node5StartEiPPc 于 ??:?
< 0x00007fc8b31a2555: ?? ??:0
< 0x00000000009694cc: _start 于 ??:?
< ################################################################################
< Raw stacktrace:
< ################################################################################
< /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_backtrace_print+0x53) [0x7fc8a3b91123]
< /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(aws_fatal_assert+0x44) [0x7fc8a3b85f44]
< /root/test/iot/node_modules/aws-iot-device-sdk-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node(+0xa4a46) [0x7fc8a3a8ea46]
< /usr/bin/node() [0x9d4d28]
< /usr/bin/node() [0x1383c79]
< /usr/bin/node(uv_run+0x2f0) [0x137c5f0]
< /usr/bin/node(_ZN4node11Environment14CleanupHandlesEv+0x138) [0x9a4b28]
< /usr/bin/node(_ZN4node11Environment10RunCleanupEv+0x56) [0x9a9dc6]
< /usr/bin/node(_ZN4node15FreeEnvironmentEPNS_11EnvironmentE+0x47) [0x96d547]
< /usr/bin/node(_ZN4node16NodeMainInstance3RunEv+0x10f) [0xa4483f]
< /usr/bin/node(_ZN4node5StartEiPPc+0x115) [0x9d1e15]
< /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fc8b31a2555]
< /usr/bin/node() [0x9694cc]

**Comment by jmklix** [comment]
Are you changing any of the settings for ccproxy when setting it up? 
Also what version of windows are you using?
