### ISSUE TITLE
Pub_sub does not work

### ISSUE THREAD

**Issue by dbelovol** [aws/aws-iot-device-sdk-js-v2#145]
There was issue #136, and I've established, that it works on Ubuntu 18.04.4 LTS, but don't on my OpenSUSE Leap 15.1. I've closed it recently. As It becames clear, the reason was libssl-dev. For OpenSUSE it's name is libopenssl-devel. I've installed it via package manager and  it works. May be it would be helpful for someone

**Comment by jmklix** [comment]
Are there any special steps that you had to take when using libopenssl-devel?

**Comment by dbelovol** [comment]
Nothing. Install by Yast (Graphical package manager for SUSE) and everything gets Ok.

**Comment by bretambrose** [comment]
We've transitioned away from openssl as our linux crypto dependency and we hope that this will clear up a lot of issues, especially with the javascript sdk which struggled the most with the openssl-with-fpic dependency.  Let us know if you're still having an issue here.
