### ISSUE TITLE
AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path is not a function when integrating it in a electron+webpack application

### ISSUE THREAD

**Issue by akiannillo** [aws/aws-iot-device-sdk-js-v2#148]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
macOS Big Sur Version 11.2.3 on a MacBook Pro (16-inch, 2019)

**Describe the question**

I'm trying to integrate aws-iot-device-sdk-js-v2 in a electron application that uses webpack (jitsi-meet-electron) but I cannot understand why it gives me this error:
```
Uncaught (in promise) TypeError: aws_iot_device_sdk_v2__WEBPACK_IMPORTED_MODULE_10__.iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path is not a function
    at createConnection (Conference.js:369)
    at Conference._onVideoConferenceJoined (Conference.js:316)
    at D.eval (Conference.js:182)
    at D.a.emit (external_api.js:265)
    at eval (external_api.js:1259)
    at eval (external_api.js:891)
    at Set.forEach (<anonymous>)
    at _.emit (external_api.js:890)
    at _onMessageReceived (external_api.js:879)
    at eval (external_api.js:836)
```

I created a new async function in the Conference.js (https://github.com/jitsi/jitsi-meet-electron/blob/master/app/features/conference/components/Conference.js) 

```
async function createConnection(id: string) {

    const client_bootstrap = new io.ClientBootstrap();
    let config_builder = null;
    config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path(
        "/path/to/certificate.pem.crt.txt", 
        "/path/to/private.pem.key");
    config_builder.with_certificate_authority_from_path(
        undefined, 
        "/path/to/AmazonRootCA1.pem");
    config_builder.with_clean_session(false);
    config_builder.with_client_id(id);
    config_builder.with_endpoint("<my_prefix>-ats.iot.<my_region>.amazonaws.com");

    const config = config_builder.build();
    const client = new mqtt.MqttClient(client_bootstrap);
    const connection = client.new_connection(config);

    await connection.connect()
    await sconnection.disconnect()
}
```

Am I missing something?

**Comment by akiannillo** [comment]
I tried also with require instead of import, that is:

```
async function createConnection(id: string) {

    const { mqtt, io, iot } = require('aws-iot-device-sdk-v2');

    const client_bootstrap = new io.ClientBootstrap();
    let config_builder = null;
    config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path(
                   "/path/to/certificate.pem.crt.txt", 
                   "/path/to/private.pem.key");
    config_builder.with_certificate_authority_from_path(
                    undefined, 
                    "/path/to/AmazonRootCA1.pem");
    config_builder.with_clean_session(false);
    config_builder.with_client_id(id);
    config_builder.with_endpoint("<my_prefix>-ats.iot.<my_region>.amazonaws.com");

    const config = config_builder.build();
    const client = new mqtt.MqttClient(client_bootstrap);
    const connection = client.new_connection(config);

    await connection.connect()
    await connection.disconnect()
}
```

but the result is still 

```
Uncaught (in promise) TypeError: iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path is not a function
    at createConnection (Conference.js:372)
    at Conference._onVideoConferenceJoined (Conference.js:313)
    at D.eval (Conference.js:179)
    at D.a.emit (external_api.js:265)
    at eval (external_api.js:1259)
    at eval (external_api.js:891)
    at Set.forEach (<anonymous>)
    at _.emit (external_api.js:890)
    at _onMessageReceived (external_api.js:879)
    at eval (external_api.js:836)
```

that makes me think that webpack is not responsible for this (or not?)

**Comment by jmklix** [comment]
Electron is not something that we're supporting currently:

https://github.com/awslabs/aws-crt-nodejs/issues/221#issuecomment-862628268
> 
> Just checked with the team, referring to @justinboswell. We don't really support electron now, and binding.gyp will not work on Windows, we remove it as it is a bad solution. So, basically rebuild for electron will not work with our codebase.
> 
> A possible workaround is you can build aws-crt from source and link electron with the binary instead of rebuild. Possible reference [here](http://man.hubwiz.com/docset/electron.docset/Contents/Resources/Documents/docs/tutorial/using-native-node-modules.html#modules-that-rely-on-prebuild)
> I don't really have a good suggestion as I am super unfamiliar with electron...

A possible workaround can be found here: https://github.com/awslabs/aws-crt-nodejs/pull/220
