### ISSUE TITLE
Provide sample for Angular 6+ or IONIC

### ISSUE THREAD

**Issue by devrajeev** [aws/aws-iot-device-sdk-js-v2#162]
**Is your feature request related to a problem? Please describe.**
Sample and docs are not expressive

**Describe the solution you'd like**
Could you please provide a sample application for the Angular(6+) app latest version

**Describe alternatives you've considered**
Alternatively, you can provide for IONIC Angular

**Additional context**
I tried a lot to understand how this one can use in my IONIC angular application due to the lack of examples and docs, I am unable to process. I would suggest creating a sample example with even static certificates would help me and others a lot.

Thank you.

**Comment by jmklix** [comment]
Sorry, but we are not planning on adding samples for these frameworks.
