### ISSUE TITLE
Crash on disconnect in a multi MQTT connection scenario

### ISSUE THREAD

**Issue by thehellmaker** [aws/aws-iot-device-sdk-js-v2#163]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ Y] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [ Y] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
We have an AWS MQTT bridge where multiple connection are made from the same node process. So most of the clients connect to our node server dynamically and for each of these we create a new MQTT Client Connection. In a single client scenario things are working fine but in a multi client scenario we are facing crashed esp during disconnects.

Signal received: 11, errno: 0
  SIGSEGV @ 0x0x298
################################################################################
Stack trace:
################################################################################
1   aws-crt-nodejs.node                 0x000000010560ee13 s_print_stack_trace + 19
2   libsystem_platform.dylib            0x00007fff2062bd7d _sigtramp + 29
3   ???                                 0x0000000000000000 0x0 + 0
4   aws-crt-nodejs.node                 0x00000001056849c9 aws_mutex_lock + 9
5   aws-crt-nodejs.node                 0x000000010563e006 aws_mqtt_client_connection_disconnect + 102
6   aws-crt-nodejs.node                 0x00000001056134a8 aws_napi_mqtt_client_connection_disconnect + 472
7   node                                0x000000010006b7ea _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE + 122
8   node                                0x000000010025a498 _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE + 616
9   node                                0x0000000100259a2c _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE + 524
10  node                                0x0000000100259152 _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE + 258
11  node                                0x0000000100a7a319 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
12  node                                0x0000000100a135e2 Builtins_InterpreterEntryTrampoline + 194
13  node                                0x0000000100ab9ea0 Builtins_PromiseConstructor + 1696
14  node                                0x0000000100a0f78a Builtins_JSBuiltinsConstructStub + 138

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?
"aws-crt": "^1.8.0",
"aws-iot-device-sdk-v2": "1.5.1",

**To Reproduce (observed behavior)**
We use a modified version of https://github.com/d3alek/aws-iot-non-cert-bridge which is migrated to v2 sdk

**Comment by jmklix** [comment]
When you say modified version, what changes does that include?

**Comment by imZack** [comment]
I'm having the same issue. Does anyone know how to resolve it?

I've tried the following trick and it's not working as well
```
    const timer = setInterval(() => {}, 60 * 1000)
    await conn.disconnect()
    clearTimeout(timer)
```
