### ISSUE TITLE
Greengrass discovery sample doesn't print DiscoveryError information

### ISSUE THREAD

**Issue by FThompsonAWS** [aws/aws-iot-device-sdk-js-v2#164]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
The discovery sample doesn't output information about DiscoveryError errors, which includes common errors such as HTTP 403 or HTTP 404. This makes it difficult to troubleshoot discovery issues when using this sample. The sample outputs the following error when it encounters a DiscoveryError.

```
DISCOVERY SAMPLE FAILED: Error: Discovery failed (headers: [object Object])
```

**SDK version number**
1.5.1

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Amazon Linux 2 (EC2)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

The following steps assume that you start with a working end-to-end Greengrass discovery sample.

To reproduce HTTP 403:
1. Deny the `greengrass:Discover` permission for the IoT thing that runs the discovery sample.
2. Run the discovery sample again.

To reproduce HTTP 404:
1. Remove the IoT thing from all Greengrass groups (so the device has no cores to discover).
2. Run the discovery sample again.

**Expected behavior**

I expect that the DiscoveryError message and error code would be surfaced in the error logs, so that I can identify why the error occurred.

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
const level : io.LogLevel = parseInt(io.LogLevel[argv.verbosity.toUpperCase()]);
io.enable_logging(level);
```

**Additional context**

**Comment by jmklix** [comment]
I will look into fixing this
