### ISSUE TITLE
Cannot find module aws-crt-nodejs from '../node_modules/aws-crt/dist/native/binding.js'

### ISSUE THREAD

**Issue by empz** [aws/aws-iot-device-sdk-js-v2#168]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
I'm trying to test a service that uses this library and so I'm using `jest.mock` to mock both `aws-iot-devide-sdk-js-v2` and `aws-crt`

**SDK version number**
    "aws-crt": "^1.8.1",
    "aws-iot-device-sdk-v2": "^1.5.2",

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
https://codesandbox.io/s/jest-mock-aws-iot-device-sdk-v2-74f6e
Open a new shell and run `npm test`

Fails with the following output

```
Cannot find module '/sandbox/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs' from '../node_modules/aws-crt/dist/native/binding.js'

    Require stack:
      /sandbox/node_modules/aws-crt/dist/native/binding.js
      /sandbox/node_modules/aws-crt/dist/native/crt.js
      /sandbox/node_modules/aws-crt/dist/index.js

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/aws-crt/lib/native/binding.js:40:19)
```

**Expected behavior**
Test should run successfully.

**Additional context**
So I don't know if this is a problem on this library, NestJS or Jest. But I find it odd that this library's package contains a node_modules folder with aws-crt inside (instead of leveraging the `aws-crt` in the root node_modules, as the documentation says we need to install `aws-crt` also).
![image](https://user-images.githubusercontent.com/412489/123432325-8d8efb00-d5ca-11eb-8454-ff4779baff85.png)

**Comment by jmklix** [comment]
The link you provided doesn't seem to work, but this user had a similar problem with jest that you might find helpful: https://github.com/aws/aws-iot-device-sdk-js-v2/issues/119#issuecomment-748670403

If that doesn't work can you provide the steps you took to set it up?
