### ISSUE TITLE
Device interface like v1

### ISSUE THREAD

**Issue by ed-sparkes** [aws/aws-iot-device-sdk-js-v2#17]
Hi, 

Was going to try the new SDK but there doesnt appear to be anything equivalent to the Device interface in v1. 

My use case is as web socket implementation for notifications to a webapp. 

Asynchronous backend processed put messages to a topic and webapp listening for these notifications. 

Similar to that described in this serverless blog post ... 

https://serverless.com/blog/serverless-notifications-on-aws/

Am i missing something, is this still in development or is this use case not going to be supported by the new SDK?

Thanks, Ed

**Comment by rccarper** [comment]
The API is different, but the necessary parts for this use case should be there.  Our pub-sub sample should show the operations that you need (setting up a client, creating a connection, subscribing, publishing, etc..): 

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/master/samples/node/pub_sub/index.ts

Hopefully that helps!  Let me know if there's anything that you still see missing.

**Comment by jmklix** [comment]
@ed-sparkes have you had any problems using v2?
