### ISSUE TITLE
having issue on installing aws-crt

### ISSUE THREAD

**Issue by chojowliu** [aws/aws-iot-device-sdk-js-v2#171]
I am trying to install aws-crt on my rasberry pi 4. The installation kept interrupted on "aws/testing/compression/huffman.h: No such file or directory"

![image](https://user-images.githubusercontent.com/2468697/124335672-ad8d6400-db60-11eb-8b5b-8e69cdedf418.png)

I am using node v11.15.

Please help.

**Comment by chojowliu** [comment]
I just realized, it only happens on 1.8.*, 1.7.* is working okay.

**Comment by jmklix** [comment]
Not sure if this is the same issue because you are getting a different error, but can you try [this](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/167#issuecomment-866443246):

> 
> 
> We currently don't include the pre-compiled binaries for raspberry pi, but you can do this manually if you want to.
> 
> Go [here](https://github.com/awslabs/aws-crt-nodejs) and follow the install instructions (I have also included them below)
> 
> ```shell
> git clone https://github.com/awslabs/aws-crt-nodejs.git
> cd aws-crt-nodejs
> git submodule update --init
> npm install
> ```
> 
> Then you will want to copy the folder containing `aws-crt-nodejs.node` to the location mentioned in the error message:
> 
> ```shell
> cp -r ~/aws-crt-nodejs/dist/bin/linux-arm ~/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/bin/linux-arm
> ```
