### ISSUE TITLE
Browser - Mqtts Cert Based Connection

### ISSUE THREAD

**Issue by ryanhagen** [aws/aws-iot-device-sdk-js-v2#173]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?
macOS

**Describe the question**
Is it supported to use cert based mqtts in the browser? Is the browser at all supported by this SDK?
I'm running into this issue:
`Uncaught Error: The current runtime is not reporting an NAPI version. Please upgrade to node >=10.16.0, or use the provided browser implementation.`

node -v
`v16.4.2`

**Comment by ryanhagen** [comment]
Or is there even a way to use mqtt username and password and have it be browser compatible?

**Comment by jmklix** [comment]
There is a [feature request](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/129) on this sdk for cognito, but it isn't currently supported in this sdk

**Comment by antoineaws** [comment]
Running into the same issue when trying to create an MQTT config with the following info:
```
        let customAuthConfig: MqttConnectCustomAuthConfig = {
            authorizerName: "IoTCustomAuthorizer",
            username: "MyUsername",
            password: password,
            tokenKeyName: "token",
            tokenValue: "token_value",
            tokenSignature: "token_sign"
        };

        let builder = AwsIotMqtt5ClientConfigBuilder.newDirectMqttBuilderWithCustomAuth(
            amplifyconfig.IoT.endpoint,
            customAuthConfig
        );
```
Error is: Uncaught Error: The current runtime is not reporting an NAPI version. Please upgrade to node >=10.16.0, or use the provided browser implementation. 

Library version is: `1.19.5`

Thoughts on what could be the issue?

**Comment by xiazhvera** [comment]
> Running into the same issue when trying to create an MQTT config with the following info:
> 
> ```
>         let customAuthConfig: MqttConnectCustomAuthConfig = {
>             authorizerName: "IoTCustomAuthorizer",
>             username: "MyUsername",
>             password: password,
>             tokenKeyName: "token",
>             tokenValue: "token_value",
>             tokenSignature: "token_sign"
>         };
> 
>         let builder = AwsIotMqtt5ClientConfigBuilder.newDirectMqttBuilderWithCustomAuth(
>             amplifyconfig.IoT.endpoint,
>             customAuthConfig
>         );
> ```
> 
> Error is: Uncaught Error: The current runtime is not reporting an NAPI version. Please upgrade to node >=10.16.0, or use the provided browser implementation.
> 
> Library version is: `1.19.5`
> 
> Thoughts on what could be the issue?

It looks like you are calling node API in browser. You can follow this link to make sure the app utilizes the browser API.
https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/documents/FAQ.md#i-would-like-to-build-a-browser-application-and-got-error-property-does-not-exist-on-type-typeof-importpathnode_modulesaws-crtdistnative-

**Comment by antoineaws** [comment]
Thanks @xiazhvera this helped get past the above error. I used a similar way to import like this:
```
import { mqtt5, auth, iot } from "aws-iot-device-sdk-v2/dist/browser";
```

However now, running into an issue where the aws-iot-device-sdk-v2 client MQTT5 doesn't connect. I can see it attempting a connection but no messages are sent as part of the initial connect as with MQTT.js and Amplify SDK PubSub. Screenshot below:
`aws-iot-device-sdk-v2`
<img width="605" alt="Screenshot 2024-05-15 at 7 37 21 AM" src="https://github.com/aws/aws-iot-device-sdk-js-v2/assets/78559652/feb716f1-4067-4e76-89ae-97ab1c3a1598">

The code used is:
```javascript
private async connectIotCoreAwsSdkMqtt5() {
        const jwtToken = this.authSvc.currentUser?.tokens?.accessToken;
        let customAuthConfig: iot.MqttConnectCustomAuthConfig = {
            authorizerName: "xxxxxx",
            username: this.authSvc.currentUser?.userSub,
            password: new TextEncoder().encode(jwtToken?.toString()),
        };
        let builder = iot.AwsIotMqtt5ClientConfigBuilder.newWebsocketMqttBuilderWithCustomAuth(
            amplifyconfig.IoT.endpoint,
            customAuthConfig
        );
        this.mqtt5Client = new mqtt5.Mqtt5Client(builder.build());
        this.mqtt5Client.on('error', (error) => {
            console.log(error);
        });

        this.mqtt5Client.on("messageReceived", (eventData: mqtt5.MessageReceivedEvent): void => {
            console.log(eventData);
        });

        this.mqtt5Client.on('attemptingConnect', (eventData: mqtt5.AttemptingConnectEvent) => {
            console.log(eventData);
        });

        this.mqtt5Client.on('connectionSuccess', (eventData: mqtt5.ConnectionSuccessEvent) => {
            console.log(eventData);
        });

        this.mqtt5Client.on('connectionFailure', (eventData: mqtt5.ConnectionFailureEvent) => {
            console.log(eventData);
        });

        this.mqtt5Client.on('disconnection', (eventData: mqtt5.DisconnectionEvent) => {
            console.log(eventData);
        });

        this.mqtt5Client.on('stopped', (eventData: mqtt5.StoppedEvent) => {
            console.log(eventData);
        });
        this.mqtt5Client.start();

        const suback = await this.mqtt5Client.subscribe({
            subscriptions: [
                { qos: mqtt5.QoS.AtLeastOnce, topicFilter: this.authSvc.currentUser?.userSub ?? '' },
            ]
        });

        const qos0PublishResult = await this.mqtt5Client.publish({
            qos: mqtt5.QoS.AtMostOnce,
            topicName: this.authSvc.currentUser?.userSub ?? '',
            payload: "This is a qos 0 payload"
        });
    }
```

With the other libraries (AmplifySDK and Mqtt.js) I noticed a message sent with the username and password part of the initial payload/messages, but not with this library. Thoughts on what I could be missing? Note, I am using "Custom Domain Configuration" under IoT Core => Settings. Same domain works well with the other libraries. Format is: `xxxx-ats.iot.ca-central-1.amazonaws.com`

**Comment by xiazhvera** [comment]
I could not tell more without additional information. Here is some suggestion you could try out. 

1. Ensuring that the client starts correctly by waiting for the connection success. In case the start process was not finished. 
Example:https://github.com/aws/aws-iot-device-sdk-js-v2/blob/e1088bfdcc37321c315f1a1a88b5edcde05b395e/samples/browser/pub_sub_mqtt5/index.ts#L139.

2. Confirming that the MqttConnectCustomAuthConfig is URL encoded (While I doubt it's the issue, since no data transaction occurred. It's worth checking).

As what you're experiencing doesn't seem to be related to the original issue, please consider opening a separate ticket. This way, we can ensure better visibility and address the new problem more effectively. Please attach logs if you plan to create a new thread.
