### ISSUE TITLE
TypeError: Cannot read property 'AwsCredentialsProvider' of undefined

### ISSUE THREAD

**Issue by sean-paterson** [aws/aws-iot-device-sdk-js-v2#174]
**Platform/OS/Hardware/Device**
MacOS on Google Chrome

**Describe the question**
Been trying to test out the `aws-iot-device-sdk-v2` library for a bit. I am currently trying to test out the [sample app](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/pub_sub/index.ts) provided by the AWS dev team. I am trying to test out the system incrementally. This is the code I have tested so far:

```
import { mqtt, auth, http, io, iot } from 'aws-iot-device-sdk-v2';

const client_bootstrap = new io.ClientBootstrap();
        
let config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets({
    region: 'us-west-2',
    credentials_provider: auth.AwsCredentialsProvider.newDefault(client_bootstrap)
});

config_builder.with_clean_session(false);
config_builder.with_endpoint('example.com');
config_builder.with_client_id(1);
        
const config = config_builder.build();
const client = new mqtt.MqttClient(client_bootstrap);
const connection = client.new_connection(config);

await connection.connect();
```

When running this on the AWS console, I am getting the following error:

`TypeError: Cannot read property 'AwsCredentialsProvider' of undefined`

It looks like the `aws-crt` library is getting imported correctly into the `node_modules` of `aws-iot-device-sdk-v2`. I've even tried installing different versions of aws-crt (back to 1.7.1) and it hasn't solved the issue. Any idea what I'm doing wrong here?

**Comment by bretambrose** [comment]
Do you get the same when trying to run the pub_sub sample under samples/node/pub_sub?  Unless you're in the browser where you'll need to source credentials in another manner, for example via providers/cognito from the regular js sdk ala https://github.com/awslabs/aws-crt-nodejs/blob/main/samples/browser/pub_sub/index.ts#L16

**Comment by sean-legitscript** [comment]
I am working on the browser. Every other library seems to import correctly except for auth.

**Comment by sean-legitscript** [comment]
Wasn't able to identify why I couldn't use AwsCredentialsProvider as expected but found a work-around. Instead, I was able to initialize the builder with `const config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets();`. Anyway, didn't figure out why I couldn't utilize AwsCredentialsProvider as expected. Might be something to look into if you have time. 👍

**Comment by bretambrose** [comment]
There are no credentials provider implementations in the browser functionality.  Your best bet is to adapt a provider from the AWS SDK for Javascript (https://github.com/aws/aws-sdk-js-v3)
