### ISSUE TITLE
MqttClientConnection.connect infinite loop

### ISSUE THREAD

**Issue by sean-paterson** [aws/aws-iot-device-sdk-js-v2#175]
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues)

**Platform/OS/Hardware/Device**
MacOS on Google Chrome

**Describe the question**
While running my NodeJS app in the browser, I tried connecting to the IoT cloud using an access key, private key and token. These credentials were generated through passing in an AWS RoleARN into AWS STS. Here is the code I have so far.

```
        async function iotConnect (response) {
          response = JSON.parse(response);
          console.log(response);

          const client_bootstrap = new io.ClientBootstrap();
          const config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets();

          config_builder.with_clean_session(false);
          config_builder.with_client_id(response.iotUserId);
          config_builder.with_endpoint(response.host);
          config_builder.with_credentials(response.region, response.key, response.secret, response.sessionToken);

          const config = config_builder.build();
          const client = new mqtt.MqttClient(client_bootstrap);
          config.port = 443;
          const connection = client.new_connection(config);

          console.log(connection);

          connection.on("error", (err) => {
            console.log("error", err);
          })

          connection.on("interrupt", (err) => {
            console.log("interrupt", err);
          })

          console.log('about to call connect');
          await connection.connect();
          console.log('just called connect');
        }
```

When running this application, I am able to properly create the `connection` object. However, when I reach the `connection.connect()` function call, the method never returns and None of my connection.on handlers are ever hit. I can see in the chrome dev tools that my mqtt request is getting the following response:
```
General
Request Url: wss://<iot hostname>.iot.us-west-2.amazonaws.com/mqtt?X-Amz-Algorithm=<algorithmM>&X-Amz-Credential=<credential>%2F<date>%2F<region>%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=<date>&X-Amz-SignedHeaders=host&X-Amz-Signature=<signature>&X-Amz-Security-Token=<token>
Request Method: GET
Status Code: 101 Switching Protocols

Response Headers
access-control-allow-origin: *
access-control-expose-headers: x-amzn-ErrorMessage
access-control-expose-headers: x-amzn-RequestId
access-control-expose-headers: x-amzn-ErrorType
access-control-expose-headers: Date
connection: upgrade
content-length: 0
. . .
```

Sorry if this is a long explanation. I am trying to find a way to debug this problem but I am not seeing any easy way how. Do you have any suggestions on how I can go about debugging this infinite loop? Maybe you've seen this loop before and know what usually causes it?

**Comment by sean-legitscript** [comment]
Was able to resolve this problem. It turns out my IAM credentials were organized incorrectly. The original ARN I created was not properly synced to use iot:Connect. This meant that the resulting key, secret, and token were not authorized to initiate a connection.

My hang-up is that the `MqttClientConnection.connect()` method never returned to notify me that this was the problem. I've noticed this same problem in the MQTT.js function. Is there any chance there could be an update where `MqttClientConnection.connect()` will return an error when this is the case?

**Comment by bretambrose** [comment]
Thanks for the report.  We've had some reports about problems propagating initial connection errors when using mqtt-js 4.x, which both the v2 and v1 JS SDKs now use.  This seems like a good repro case and I will try and see what we can do to resolve it.
