### ISSUE TITLE
Handle MqttClient going offline

### ISSUE THREAD

**Issue by RavidAshurov** [aws/aws-iot-device-sdk-js-v2#178]
Hi, 

I am working with an MQTT message broker and would like to get some guidance regarding client disconnection.
If my process, that uses MqttClient to both publish and subscribe to topics, went offline (but still running) for a long period, is there a way for me to know that the MqttClient is no longer  connected? 
I have tried to turn off the network and it seems that no event (close, offline, disconnect, error) is triggered...

Thanks

**Comment by jmklix** [comment]
You should be able to use the callbacks, but it might not work as expected especially in the browser.

If you wanted you can also try publishing something and see if you get it back as a subscription.

**Comment by RavidAshurov** [comment]
const { up } = require("inquirer/lib/utils/readline")

`try {
    const client_bootstrap = new io.ClientBootstrap();
    const config_builder = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path(
        certPath,
        keyPath
    );
    config_builder.with_certificate_authority_from_path(undefined, caPath);
    config_builder.with_clean_session(false);
    config_builder.with_client_id(`${clientId}`);
    config_builder.with_endpoint(awsIoTEndpoint);

    const config = config_builder.build();
    const client = new mqtt.MqttClient(client_bootstrap);
    this._mqttConnection = client.new_connection(config);

    this._mqttConnection.on('connect', () => {
        console.log("%%%%CONNECTED!!!%%%%");
        clearInterval(this.reconnectMqttTimeout);
    });

    this._mqttConnection.on('close', () => {
        console.log("^^^^^^^^^^CLOSE!!!^^^^^^^^^^");
        this.reconnectMqttTimeout = setInterval(() => {
            this.reconnectToMqtt();
        }, MQTT_RECONNECT_INTERVAL);
    });
    this._mqttConnection.on('disconnect', () => {
        console.log("^^^^^^^^^DISCONNECTED!!!^^^^^^^^");
        this.reconnectMqttTimeout = setInterval(() => {
            this.reconnectToMqtt();
        }, MQTT_RECONNECT_INTERVAL);
    });
    this._mqttConnection.on('error', (e) => {
        console.log("^^^^^^ERROR!!!^^^^^^^^^^^");
        console.log(e);
        this.reconnectMqttTimeout = setInterval(() => {
            this.reconnectToMqtt();
        }, MQTT_RECONNECT_INTERVAL);
    });
    this._mqttConnection.on('offline', () => {
        console.log("^^^^^^^^OFFLINE!!!^^^^^^^^^^");
        this.reconnectMqttTimeout = setInterval(() => {
            this.reconnectToMqtt();
        }, MQTT_RECONNECT_INTERVAL);
    });
    this._isMqttConnected = await this._mqttConnection.connect();
    console.log("ALSO CONNECTED :::::::::::::::");
} catch (error) {
    this._isMqttConnected = false;
    console.log('********FAILED TO CONNECT********');
}`

I have attached a sample from my NodeJS process.
the scenario is that the process  starts running while the machine is connected to the network, and then i disconnect the machine from the network - meaning the MQTT client should be disconnected as well.. but non of the events are triggered (except for the initial "connect" event).

Note that the process is not exiting, and that there is an interval (every .5sec) that publishes using the MQTT client

Here is the interval snippet: 

`setInterval(()=> {
    try {
        const res = await this._mqttConnection.publish(
            topic,
            JSON.stringify(msg),
            mqtt.QoS.AtLeastOnce
        );
        console.log(res);
    } catch (error) {
        console.log("ERROR", {error})
    }
}, 500)`

From what i saw, the publish promise is not rejected when the connection is down, it just waits and resolves once the connection is back up, even if it takes over 10 minutes.

**Comment by jmklix** [comment]
What do you have your `keep_alive_secs` set to?

**Comment by jmklix** [comment]
Does using [`MqttConnectionInterrupted`](https://aws.github.io/aws-iot-device-sdk-js-v2/modules/mqtt.html#mqttconnectioninterrupted) give you what you are looking for?
