### ISSUE TITLE
How to package node applications that uses  aws-iot-device-sdk-js-v2  in windows

### ISSUE THREAD

**Issue by zhex900** [aws/aws-iot-device-sdk-js-v2#182]
Hi,

How do you package node applications that use aws-iot-device-sdk-js-v2  in windows? I can't use pkg. 
https://github.com/awslabs/aws-crt-nodejs/issues/227

README says `aws-iot-device-sdk-js-v2` is cross-platform. If it is cross-platform, what is the recommended way to package the node application?

**Comment by jmklix** [comment]
What have you tried so far and what errors are you getting? The more details the better

**Comment by zhex900** [comment]
Please refer to the details in https://github.com/awslabs/aws-crt-nodejs/issues/227. 

`pkg` produced an `exe` but I cannot run it.

**Comment by jmklix** [comment]
That error is more closely related to the aws-crt-nodejs repo that you linked and you should be getting the help you need there. Closing this issue
