### ISSUE TITLE
Unit testing using Jasmine in Angular project

### ISSUE THREAD

**Issue by sean-legitscript** [aws/aws-iot-device-sdk-js-v2#183]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution. Specifically, I have scoured the internet for anything related to unit testing `aws-iot-device-sdk-js-v2` using jasmine and haven't found anything.

**Describe the bug**
We are currently trying to unit test our Angular 6 web app using jasmine. In our codebase, we are utilizing the `aws-iot-device-sdk-js-v2` package. It currently works great in our web application and we are able to connect to our IoT cluster fine. However, attempting to unit test our code has been less successful. We have been running into a bug where jasmine seems to be skipping our `.spec.ts` file for the class that uses functions defined in the package. It doesn't matter if we mock out the methods used from the package. It's as if the code is failing before it even has a chance to mock those package functions. If we comment out the use of the package's functions, the unit tests work fine.

Definitely seems like the package was not optimized for jasmine testing. Therefore, I wanted to see what we could do to remedy this problem as it is stopping us from successfully unit testing our component.

**SDK version number**
v1.5.x

**Platform/OS/Hardware/Device**
Angular: 6
Jasmine: 3.1.x
OS: macOS Big Sur
Hardware: MacBook Pro
Device: Google Chrome Browser

**To Reproduce (observed behavior)**
This is not the exact code we are utilizing in our system but it should be enough for you to reproduce the unit testing problem we are seeing.

```
//example.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { io, iot, mqtt } from 'aws-iot-device-sdk-v2';

@Component({
  selector: 'example',
})
export class ExampleComponent implements OnInit, OnDestroy {
  private connection: mqtt.MqttClientConnection = null;

  public async ngOnInit() {
    if (this.connection) {
      const configBuilder = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets();

      configBuilder.with_clean_session(false);
      configBuilder.with_client_id('EXAMPLE USER ID');
      configBuilder.with_endpoint('EXAMPLE HOST');
      configBuilder.with_credentials('EXAMPLE REGION', 'EXAMPLE KEY', 'EXAMPLE SECRET', 'EXAMPLE SESSION TOKEN');

      const configObj = configBuilder.build();
      const client = new mqtt.MqttClient(new io.ClientBootstrap());
      configObj.port = 443;
      this.connection = await client.new_connection(configObj);
    } else {
      await this.connection.reconnect();
    }
  }

  public async ngOnDestroy() {
    if (this.connection) {
      await this.connection.disconnect();
    }
  }
}
```
```
//example.component.spec.ts
import { ExampleComponent } from './example.component';

describe('ExampleComponent', () => {
    let component: ExampleComponent;

    beforeEach(() => {
        component = new ExampleComponent();
    });

    it('should initialize correctly with ngOnInit', () => {
        expect(ExampleComponent).toBeDefined();
    });
});
```

When we run our tests, the file name and it's unit tests are not displayed in the results which leads me to believe that the unit tests were ignored. There aren't any extra errors to display other then the Logs/outputs displayed below.

**Expected behavior**
We expected to see that the file was included in our unit testing result.

**Logs/output**
```
HeadlessChrome 0.0.0 (Mac OS X x.x.x) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught ReferenceError: process is not defined",
    "str": "An error was thrown in afterAll\nUncaught ReferenceError: process is not defined"
  }
HeadlessChrome 0.0.0 (Mac OS X x.x.x) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught ReferenceError: process is not defined",
    "str": "An error was thrown in afterAll\nUncaught ReferenceError: process is not defined"
  }
```

**Comment by sean-legitscript** [comment]
Hey gang, any update on this one? Would definitely like to have increased code coverage!

**Comment by bretambrose** [comment]
We'd love to have our SDKs compatible with as many testing frameworks as possible, but given the constraints we work under (our team maintains almost 20 repositories across 6+ languages, while balancing a full plate of internally-requested feature work) it is very unlikely that anyone will be able to look into this soon, from a priority standpoint.

If you're able to find a solution or find what could be done to fix the issue, we'd be happy to take a look at the pull request.

My only other suggestion would be that the issue may actually be a problem with the aws-crt-nodejs package (https://github.com/awslabs/aws-crt-nodejs), which is where the browser and native/node implementations are unified; I don't think there is anything specific to browser environments here in the SDK.
