### ISSUE TITLE
Check if MqttClientConnection is open

### ISSUE THREAD

**Issue by zhex900** [aws/aws-iot-device-sdk-js-v2#184]
I want to gracefully close the mqtt connection. 

This is my connection code 

```
const config = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder(
      `${certificatePem}`,
      `${privateKey}`
    )
      .with_clean_session(false)
      .with_protocol_operation_timeout_ms(2 * 1000)
      .with_keep_alive_seconds(MQTT_KEEP_ALIVE_SECS)
      .with_client_id(deviceId) // registered thing name
      .with_endpoint(IOT_ENDPOINT)
      .build();

    const clientBootstrap = new io.ClientBootstrap();
    const client = new mqtt.MqttClient(clientBootstrap);

    connection = client.new_connection(config);
```

How do I check if the `connection` is open?

If I run `connection.disconnect()` before the `connection` is open. I will get this error

AWS_ERROR_MQTT_NOT_CONNECTED, The requested operation is invalid as the connection is not open

**Comment by jmklix** [comment]
Currently there is no function that directly tells you the connection status. But you can get around this by using listeners to determine when the connection is dropped. Take a look at the Api Docs [here](https://aws.github.io/aws-iot-device-sdk-js-v2/classes/aws_crt.mqttclientconnection.html) and let me know if you have any questions.

**Comment by mogambo100** [comment]
Hi, The API doc is not available anymore. Can you please share how we can check MqtttClient connection status in the IotV2 right Now

**Comment by TwistedTwigleg** [comment]
Here's an updated link to the API docs for the [Node](https://aws.github.io/aws-iot-device-sdk-js-v2/node/classes/mqtt.MqttClientConnection.html) and [Browser](https://aws.github.io/aws-iot-device-sdk-js-v2/browser/classes/mqtt.MqttClientConnection.html) versions of the SDK.

One way to determine if the MqttClientConnection is connected or not is using the events (`CONNECT`, `DISCONNECT`, etc) and track the status of the connection using those callbacks.
