### ISSUE TITLE
How to make correct migration from aws-iot-device-sdk to aws-iot-device-sdk-v2

### ISSUE THREAD

**Issue by baliand** [aws/aws-iot-device-sdk-js-v2#203]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
AWS Lambda arm and x86

**Describe the question**
Please help me. I can'd find how to correct make migration

I have this connection 

```
const awsIot = require('aws-iot-device-sdk'); 

let client = awsIot.device({
        clientId: utils.uuidv1(),
        protocol: 'wss',
        host: MYHOST,
        keepalive: 1000,
});

client.on('error', (err) => {
    console.error(err);
});
client.on('connect', () => {
    console.info('MQTT connected');
});

client.on('message', async (messageTopic, payload) => {
/// some my actions
});

client.subscribe(mysubTopic, async (error, granted) => {
 // some my actions
})

// i need make unsubscripbe for some case
client.unsubscribe(mysubTopic);
```

How can I do it now with `aws-iot-device-sdk-v2`?

Thanks

**Comment by KaibaLopez** [comment]
Hi @baliand ,
So first let me ask, have you taken a look at our samples for v2? specifically the [pub_sub](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples#nodepub_sub) one might help you I believe.
If you have then could you be a bit more specific on what you are having problems with?

**Comment by baliand** [comment]
@KaibaLopez I saw  pub_sub  and it not understandable for me. I need send send command and wait resonse from device. My code running on AWS lambda.

**Comment by jmklix** [comment]
I highly recommend that you start with getting the pubsub working and go from there. There is even a new example in javascript(vs the original example in typescript). What exactly do you not understand about the pubsub example?

The difference between new_websocket_builder and new_with_websockets is that there really is none. As seen [here](https://github.com/awslabs/aws-crt-nodejs/blob/92b118e5d7bb963f2ca9f26f79b8167d7370ba83/lib/native/aws_iot.ts#L118) one just returns the other.
