### ISSUE TITLE
MQTT 5.0+ Support 

### ISSUE THREAD

**Issue by kanumuru** [aws/aws-iot-device-sdk-js-v2#21]
Hi Team
We are thinking to implement the MQTT 5.0+ in our project!
aws-iot-device-sdk-js supports only MQTT 3.1 for AWS IoT.
Does aws-iot-device-sdk-js-v2 supports MQTT 5.0 + ?
Any information related to this is helpful and appreciated!
Thank you in advance.

**Comment by JonathanHenson** [comment]
It does not currently, but fortunately we have complete control over the mqtt implementation. Could you file an issue on github.com/awslabs/aws-c-mqtt

If we inplement it there is will be reflected in all v2 iot sdks at once.

**Comment by kanumuru** [comment]
Yeah sure, I will open an issue at github.com/awslabs/aws-c-mqtt
Thank you for the support

**Comment by KaibaLopez** [comment]
Linking to issue awslabs/aws-c-mqtt#120.
Closing it here.
