### ISSUE TITLE
Error due to aws-crt-node when running pub_sub_js example

### ISSUE THREAD

**Issue by javipedrosa** [aws/aws-iot-device-sdk-js-v2#210]
Confirm by changing [ ] to [x] below:
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [ x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?

 DigitalOcean instance with Ubuntu 21.04 x64

**Describe the question**

I was playing around a DO instance with aws-iot-device-sdk-v2 pub_sub_js example and everyting works fine. Then, I create a new project where I copied the index.js and /utils/cli_args.js, and when I run the code I have this:

```
N-API call failed: napi_get_value_int32(env, node_error_code, &error_code)
    @ /codebuild/output/src422080616/src/aws-crt-nodejs/source/mqtt_client_connection.c:572: napi_number_expected
(node:103300) UnhandledPromiseRejectionWarning: TypeError: error_code must be a number or undefined
    at Function.<anonymous> (/usr/local/src/myIot/node_modules/aws-crt/dist/native/aws_iot.js:109:21)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/src/myIot/node_modules/aws-crt/dist/native/aws_iot.js:29:65)
```

I tried with both, aws-crt and aws-iot-device-sdk-v2 installed in the same project and also excluding aws-crt installed as a global dependency, but still have the same error and can not figure out what is happening.

These are dependencies in my project:
```
  "dependencies": {
    "aws-crt": "^1.10.5",
    "aws-iot-device-sdk-v2": "^1.6.5",
    "dotenv": "^10.0.0",
    "websocket": "^1.0.34",
    "yargs": "^16.2.0"
  },
```

**Comment by javipedrosa** [comment]
To shed some light, this is the execution command I am using:

``` node index.js --endpoint <endpoint> --ca_file <file> --cert <file> --key <file> --use_websocket```

if I remove --use_websocket it works fine.  

Now the mystery is why it works on my Mac but fails on DO Instance

**Comment by bretambrose** [comment]
x509 based mutual tls (cert/key) is mutually exclusive with websockets, which uses AWS Sigv4 signing of websocket upgrade handshake.

**Comment by javipedrosa** [comment]
so, how can I fix that?

**Comment by bretambrose** [comment]
Run with mutual tls or with websockets, not with both.

**Comment by jmklix** [comment]
Are you having any problems when running only one of the following: mutual tls or websockets

**Comment by javipedrosa** [comment]
Honestly, I don't know how to set that modes, since following the tutorial I couldn't find how to do that. I just saw the option --use_websockets in some other issue and gave a try... everything was working on my macbook and then when I did the deploy to DO instance it started to complain.

Please let me know how to switch between modes and I will give a try.

**Comment by jmklix** [comment]
As shown in the samples [Readme](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples#nodepub_sub) you only need this to run the pub_sub:
``` sh
node dist/index.js --endpoint <endpoint> --ca_file <file> --cert <file> --key <file>
```

Websockets are another way to send data and you read more about them here ([MQTT vs Websockets](https://www.educba.com/mqtt-vs-websocket/))
