### ISSUE TITLE
code sample for connecting the device via customAuth by using aws-iot-device-sdk-v2

### ISSUE THREAD

**Issue by yilin01** [aws/aws-iot-device-sdk-js-v2#212]
Hi,

I would like to use aws-iot-device-sdk-v2 (nodejs) to connect the device with customAuth. I could not find any sample code how to make the connection.

Currently I am able to make the connection by using v1 version - aws-iot-device-sdk as follow:
const deviceModule = require('aws-iot-device-sdk').device;
const device = deviceModule({
      protocol: "wss-custom-auth",
      customAuthHeaders: {
         "X-Amz-CustomAuthorizer-Name": config.customAuthorizerName,
         "AuthorizationToken": accessToken,
         "X-Amz-CustomAuthorizer-Signature": newTokenSignature
      },
      clientId: clientId,
      region: config.region,
      host: config.host,
      debug: config.debug
   });

Can you please provide the similar sample code for aws-iot-device-sdk-v2 so that I can connect the device with customAuth?

Thanks

**Comment by jmklix** [comment]
Yes this is something that we are planning on adding, but I don't have a timeline for when this will get added.

**Comment by TwistedTwigleg** [comment]
This was added in the latest release: [version 1.8.2](https://github.com/aws/aws-iot-device-sdk-js-v2/releases/tag/v1.8.2)! 🙂 

Closing issue...
