### ISSUE TITLE
Custom Authentication with Alpn list [ 'mqtt' ]

### ISSUE THREAD

**Issue by karthikj007** [aws/aws-iot-device-sdk-js-v2#214]
I am trying to connect with Alpn protocol  **'mqtt'**  to  use the custom authentication.
I have configured the query string and certificate but always getting error like : 

**CrtError: Failed to connect: aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed**

 I am passing the query string  in username field - **config.username='uname?SDK=NodeJSv2&Version=1.10.5&x-amz-customauthorizer-name=<LambdaName>&x-amz-customauthorizer-signature=<signature>&<Token-name>=<tokenValue>';**

Same configuration working fine with alpnlist protocol **x-amzn-mqtt-ca**,port 443_ ( V2) 

Code :

```
let config_builder = new iot.AwsIotMqttConnectionConfigBuilder(); 
//config_builder.with_certificate_authority_from_path(undefined,ca_file ); 
config_builder.with_client_id(<clientId>);
config_builder.with_endpoint(aws_endpoint);
config_builder.with_clean_session(false); 
config_builder.with_port(443); 
const config = config_builder.build(); 
config.username='uname?x-amz-customauthorizer-name=<authName>&x-amz-customauthorizer-signature=<signature>&Token-Header=<tokenValueName>';
config.password='password'; 
io.enable_logging(6); 

let tlsContextOption= io.TlsContextOptions.create_client_with_mtls_from_path(cert,key);
tlsContextOption.override_default_trust_store_from_path('./',ca_file);
tlsContextOption.alpn_list=["mqtt"];
tlsContextOption.verify_peer=false;
let tlsContext=new ServerTlsContext(tlsContextOption);
config.tls_ctx=tlsContext;

const client = new mqtt.MqttClient(new ClientBootstrap());
const connection=new mqtt.MqttClientConnection(client,config);
```

**Comment by jmklix** [comment]
Can you try passing the this config string: 
```
username?x-amz-customauthorizer-name=authorizer-name&x-amz-customauthorizer-signature=token-signature&token-key-name=token-value
```

As shown in the docs [here](https://docs.aws.amazon.com/iot/latest/developerguide/custom-auth.html#custom-auth-mqtt), it's sightly different that what you are trying:
`token-key-name` 
vs 
`Token-Header`
