### ISSUE TITLE
PubSub for react-native.

### ISSUE THREAD

**Issue by sidd2217** [aws/aws-iot-device-sdk-js-v2#216]
Hi,
I'm new to aws-iot,
I wanted to to subscribe and publish using MQTT test client in iot core using react-native app.
I'm trying to find a documentation to use it in aws-sdk-js-V3 but couldn't find one so can anyone help me regarding this.
The reason I'm raising this issue here is that there is a example of pubsub here which is supported for aws-sdk-js-v2 but could'nt find one for the v3 one.
I've also gone through client-iot for js-v3 but couldn't find one.

**Comment by bretambrose** [comment]
There was a PR here (https://github.com/awslabs/aws-crt-nodejs/pull/278) that included changing the browser samples to use v3.  It might provide some useful insight.

**Comment by sidd2217** [comment]
@bretambrose 
Hi,
I went through the PR and tried working around it but it seems that PR isn't implemented in the repository so it isn't working at the moment, so do you have any other suggestions regarding this?
