### ISSUE TITLE
Importing creates an open Handle called `aws_logger`

### ISSUE THREAD

**Issue by Benedict-Carling** [aws/aws-iot-device-sdk-js-v2#219]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Describe the bug**
Importing from this library creates an open handle during jest testing

Open handle called `aws_logger`

**SDK version number**
1.6.5

**Platform/OS/Hardware/Device**
MacOS

**To Reproduce (observed behavior)**
include the following, in a file which is imported by a test file to be run by jest
```typescript
import { io, iot, mqtt } from "aws-iot-device-sdk-v2";
```
Run your testing library
```
npm run test --detectOpenHandles
```
An open handle called `aws_logger` will appear

**Expected behavior**
No open handle to be created when importing from this library

**Logs/output**
![Screenshot 2022-02-11 at 15 11 05](https://user-images.githubusercontent.com/53439684/153617032-88aa256b-142b-4e43-985d-9f87d64ef7dc.png)

**Comment by jmklix** [comment]
I'm not super familiar with using jest, but I was able to run it on the basic_discovery sample (this sample uses io, iot, and mqtt). This didn't show any open handles for me. It is possible that the logger in this sdk is shutting down after jest expects it to, which is causing the error that you see. Thanks for pointing out this error, it is probably safe to ignore this specific error until we are able to fix it.

**Comment by Benedict-Carling** [comment]
@jmklix If I were to provide a bug reconstruction in a repository, would that help you investigate?

**Comment by adamduren** [comment]
@jmklix @Benedict-Carling did you find a way to resolve this?

**Comment by Benedict-Carling** [comment]
> @jmklix @Benedict-Carling did you find a way to resolve this?

No, I have not resolved this
