### ISSUE TITLE
Is a "jobs-agent" coming?

### ISSUE THREAD

**Issue by cyrusadkisson** [aws/aws-iot-device-sdk-js-v2#22]
Our device (in development) uses the previous library's "jobs-agent.js" to accept standard job commands like reboot, shutdown, as well as upgrades etc. We've modified it to subscribe to custom topics as well and it seems to do the job.

Wondering if this new version has or will have a similar jobs-agent?

**Comment by bretambrose** [comment]
We don't have near terms plans for adding the higher-level clients that the old SDKs had, but you're not the first to ask about them.  Depending on customer demand/interest we may end up re-prioritizing.

**Comment by cyrusadkisson** [comment]
Curious if there has been any movement on this front. Thanks.

**Comment by rccarper** [comment]
Hello, there isn't any more information that we can provide right now, but we have recorded this feature request internally.

**Comment by lwilkovich** [comment]
@cyrusadkisson There does exist an [AWS IoT Device Client](https://github.com/awslabs/aws-iot-device-client) that provides support for what you're describing here.  However our Client is written in C++ and built on the C++ SDK.

**Comment by satheshantanu** [comment]
@cyrusadkisson we believe you'll be able to build and install the [AWS IoT Device Client](https://github.com/awslabs/aws-iot-device-client) in C++ quite easily, to avail default functionality to reboot, shut-down, install applications, restart applications etc. 
Further, the AWS IoT Device Client lets you add any custom device-side implementations through a "handler". You are able to write the "handler" in any language you want, so long as you can hook it into the Jobs feature of the device client. 
We'd be grateful for your feedback. We also find a way to help you if you face any roadblocks along the way.
