### ISSUE TITLE
Support using with ESM in browser

### ISSUE THREAD

**Issue by coderbyheart** [aws/aws-iot-device-sdk-js-v2#223]
Currently there are no examples for using the project in the browser, so I created a [minimal example](https://github.com/coderbyheart/aws-iot-device-sdk-js-browser-esm/blob/cdefd5912f5e3c78fd0fe99cec7b512a4215b287/index.js) that creates a connection in a web application bundled using [Vite.js](https://vitejs.dev/), which uses ES modules.

This does not work, for example because the library depends on `globals`.

This can be addressed by defining it (see this [bug report](https://github.com/aws/aws-sdk-js/issues/3673#issuecomment-855205181)):

```html
<script>
  // @see https://github.com/aws/aws-sdk-js/issues/3673#issuecomment-855205181
  var global = global || window;
</script>
```

However then `mqtt-packet/constants.js` is loaded, which depends on the Node.js API. ESM and browser friendly alternative exists: https://www.npmjs.com/package/u8-mqtt-packet

I understand this is a bigger task, so I wanted people to have an issue to upvote.

**Comment by jmklix** [comment]
Thanks for bringing this to our attention. We want to add support for ESM, but I don't have a date for when that will get added. Please continue to upvote if this is something that you want.

**Comment by matiasfha** [comment]
Maybe, monkey patch the dependency by using an alias inside webpack/vite configuration?

**Comment by bretambrose** [comment]
Would it be accurate to say this is an issue with mqtt-js and not the SDK?  What is under SDK/CRT control that can help address this?

**Comment by matiasfha** [comment]
The SDK can replace the dependency on non ESM packages like the mqtt one

**Comment by bretambrose** [comment]
That is a very significant ask =/

**Comment by coderbyheart** [comment]
In the mean-time we have gotten [proper Websocket API support on API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html) which provides a better alternative for our use-case. So if you need real-time updates from your IoT devices, I encourage you to look into that instead.

**Comment by jmklix** [comment]
As @bretambrose said, for ESM to work with this sdk it would need to work with mqtt-js. The changes need to be made in that repo. Because of this I'm going to close this feature request.

**Comment by linglingsyu** [comment]
@jmklix  mqtt.js seems to have been updated, see https://github.com/mqttjs/MQTT.js/issues/1269 
any modifications would be greatly appreciated , thanks
