### ISSUE TITLE
Why the upgrade?

### ISSUE THREAD

**Issue by cyrusadkisson** [aws/aws-iot-device-sdk-js-v2#23]
Most of us interested in this package are currently using the old package. So it's a bit alarming to see a major upgrade bc that implies there were problems/issues with the old one.

What were they?

**Comment by JonathanHenson** [comment]
The 1st version of the js SDK didn’t have any major stability issues. Other sdks though, such as the cpp SDK had some major stability issues that were architectural in nature.

Mostly we needed more control over the underlying transport and cryptography layers across all of our sdks (there’s 4 others) and we want the ability to have a uniform implementation across all languages and to ship more sdks more quickly in the future. Also this gives us the ability to ship more features reliably across languages.

This new sdk does have several immediate advantages though.

1st.) the performance and memory footprint is an immediate improvement
2nd.) the security posture, especially on unix systems, is improved by moving from openssl to s2n
3rd.) if you have a more complex infrastructure with multiple programming languages you will have predictable and uniform operational qualities (it’s the same implementation everywhere regardless of platform or programming language).
4th.) as the iot feature set grows, each SDK will receive updates at the same time and more quickly. For example some sdks didn’t have websocket support. Some didn’t have proxy support. Others didn’t have alpn support. If we need to upgrade the mqtt version, we can also do that quickly across all sdks.

**Comment by JonathanHenson** [comment]
Of course the exception to this is the webbrowser, where we can’t exactly deploy a c implementation easily. Maybe over time we can play around with wasm and llvm though, and this also gives us enough control over the stack to perform such experiments safely.
