### ISSUE TITLE
Very confused with certificate generations and samples

### ISSUE THREAD

**Issue by matart15** [aws/aws-iot-device-sdk-js-v2#237]
### Describe the issue

Every time I try IoT, I struggle with certificates.

Most examples and documents use aws console generated certificates. Which works but still confusing.

for example : 

On AWS GUI :
there is two options to create certificate.

![image](https://user-images.githubusercontent.com/17027219/163740804-7a7c8999-27f9-4a82-9350-7df1e254d17c.png)

1. Auto-generate. which gives me five file
![image](https://user-images.githubusercontent.com/17027219/163740748-f8ed3e4e-f17f-4e97-9218-46c2fb3e4963.png)

mostly works. But when first time tried IoT, I struggled a lot with wich key is for which props.

```ts
const AwsIotDeviceSetting = {
  host: "************-ats.iot.ap-northeast-1.amazonaws.com",
  keyPath: 'certs/key_name.key',      <--- which file path is it
  certPath: 'certs/private.pem',      <--- which file path is it
  caPath: 'certs/root-CA.crt',        <--- which file path is it
  clientId: "raspi",
  region: "ap-northeast-1"
}

const device = new iot.device(AwsIotDeviceSetting);
```

ended up trying all possible combinations.

2. use CSR.

`openssl req -new -key my-device-private.pem.key > my-device.csr` command gives 3 files

Again confused with which files are which. 

But worst is according to [115th page of this pdf](https://pages.awscloud.com/rs/112-TZM-766/images/EV_iot-deepdive-aws2_Sep-2020.pdf) and [this article](https://dev.classmethod.jp/articles/try-fleet-provisioning-with-js-device-sdk/), there are 7 different ways to generate certificates, some works with some conditions. ( Sorry it is japanese. could not find english source. ). Some methods need extra steps like 

change [example code](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/v1.4.3/samples/node/fleet_provisioning/index.ts#L221) to this code.
```ts
fs.writeFileSync(
  `certs/${response.certificateId}-certificate.pem.crt`,
  response.certificatePem
);
```

My suggesstion is : Add documentation or step be step example with AWS GUI, openssl and other possible certificate generation methods.

Example : [in this docs](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/) reader can select use `npm` or `curl` and different steps are presented. 

### Links

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/README.md

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/node/basic_connect/index.ts

**Comment by jmklix** [comment]
The change to the logging in the example wouldn't be a good idea because the certificate file names don't have to be standardized. The path and file extension can be different, so changing that could cause additional confusion. 

I can't read the Japanese explaining the different ways to generate certificates, but you can find a few of them documented [here](https://docs.aws.amazon.com/iot/latest/developerguide/x509-client-certs.html) in the amazon docs. There is a getting started GUI that already exists in the AWS console that auto-generates certs and gives you a shell script. That shell script then downloads and installs the v1 sdk's and you can look at that to see which certs are needed. Please let me know if there is still something that is confusing you or might better prevent others from being confused. Thanks for taking the time to give feedback on ways to improve our docs.

**Comment by matart15** [comment]
> There is a getting started GUI that already exists in the AWS console that auto-generates certs and gives you a shell script. 

Yes. that works. But custom CA does not ( I mean I cannot make it work ).

I am using AWS CDK. [Which creates IOT and Certificates on deploy.](https://github.com/aws/aws-cdk/issues/19303#issuecomment-1063722656)

But that `openssl` created certificate does not work. Mostly AWS says it wrong format, I don't know which file is which and what extra steps do I need to do

**Comment by matart15** [comment]
Here is rough translation of japanese page

![Screen Shot 2022-04-20 at 9 34 08](https://user-images.githubusercontent.com/17027219/164125013-5dfdf7c3-9a08-4858-a25e-0287752bcb13.png)


![Screen Shot 2022-04-20 at 9 47 59](https://user-images.githubusercontent.com/17027219/164125046-7922a6b2-7a2f-4d4e-9335-51c9a904de78.png)

**Comment by matart15** [comment]
PDF says writer works at Amazon, digital transformation facility, IoT Specialist Solution Architect.

So if he say there is 7 different ways to create CERTS and register, and it behaves differently, I think we need very detailed 7 example.
