### ISSUE TITLE
Error: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by matart15** [aws/aws-iot-device-sdk-js-v2#239]
### Describe the bug

I created discussion first. then thought maybe its bug. because it works with aws created certificates.

details : https://github.com/aws/aws-iot-device-sdk-js-v2/discussions/238

### Expected Behavior

work with openssl certificates

### Current Behavior

Error: error:0909006C:PEM routines:get_name:no start line

### Reproduction Steps

1. create certificate with openssl 
```sh 
openssl genrsa -out privatekey.pem 2048
openssl req -new -subj "/C=JP/ST=Tokyo/L=Chiyodaku/O=MyCompany/CN=AWS IoT Certificate" -key privatekey.pem -out cert.csr
```

2. use this code 
```ts
import {device as  deviceModule} from "aws-iot-device-sdk"

const AwsIotDeviceSetting = {
  host: "********-ats.iot.ap-northeast-1.amazonaws.com",
  keyPath: 'certs/key_name.key',
  certPath: 'certs/private.pem',
  caPath: 'certs/root-CA.crt',
  clientId: "raspi",
  region: "ap-northeast-1"
}
  const device = new deviceModule(AwsIotDeviceSetting);
  device.on('error',(error: Error | string) => {
    console.log("error", error)
  });
  device.on('connect', function() {
    device.subscribe(TOPIC.unlockDaytime);
    device.subscribe(TOPIC.unlock);
    console.log("listening all")
  });
```

### SDK version used

1

### Environment details (OS name and version, etc.)

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)", node v17.8.0.

**Comment by jmklix** [comment]
Answered your question [here](https://github.com/aws/aws-iot-device-sdk-js-v2/discussions/238). This looks like you incorrectly set up something with your certs which means it's most likely not something wrong with this sdk. Closing this issue for now
