### ISSUE TITLE
Unable to run basic_connect sample on Ubuntu desktop

### ISSUE THREAD

**Issue by IamFlowZ** [aws/aws-iot-device-sdk-js-v2#256]
### Describe the bug

I'm attempting to test out some basic functionality on my local desktop
> node iot-v2/samples/node/basic_connect/dist/index.js --endpoint my_iot_endpoint-ats.iot.us-east-1.amazonaws.com --ca_file iot-v2/certs/AmazonRootCA1.pem --cert iot-v2/certs/idk-certificate.pem.crt --key iot-v2/certs/idk-public.pem.key

Linux xxxxx 5.13.0-44-generic #49-Ubuntu SMP Wed May 18 13:28:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 21.10

When running the sample this is my error message:
> Error: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context
    at new TlsContext (/home/me/the_project/iot-v2/samples/node/basic_connect/node_modules/aws-crt/dist/native/io.js:309:33)
    at new ClientTlsContext (/home/me/the_project/iot-v2/samples/node/basic_connect/node_modules/aws-crt/dist/native/io.js:327:9)
    at AwsIotMqttConnectionConfigBuilder.build (/home/me/the_project/iot-v2/samples/node/basic_connect/node_modules/aws-crt/dist/native/aws_iot.js:301:35)
    at build_connection (/home/me/the_project/iot-v2/samples/node/basic_connect/dist/index.js:42:35)
    at Object.<anonymous> (/home/me/the_project/iot-v2/samples/node/basic_connect/dist/index.js:49:28)
    at Generator.next (<anonymous>)
    at /home/me/the_project/iot-v2/samples/node/basic_connect/dist/index.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/home/me/the_project/iot-v2/samples/node/basic_connect/dist/index.js:8:12)
    at Object.main [as handler] (/home/me/the_project/iot-v2/samples/node/basic_connect/dist/index.js:47:12) {
  code: 'Failed to create tls context'
}

My SSL version:
openssl version -a
OpenSSL 1.1.1l  24 Aug 2021

this is the TlsContextOptions object right before it gets passed to the C code

~~~
TlsContextOptions {
  min_tls_version: 128,
  alpn_list: [ 'x-amzn-mqtt-ca' ],
  verify_peer: true,
  certificate_filepath: 'iot-v2/certs/idk-certificate.pem.crt',
  private_key_filepath: 'iot-v2/certs/idk-public.pem.key',
  ca_dirpath: undefined,
  ca_filepath: 'iot-v2/certs/AmazonRootCA1.pem'
}
~~~

Personally I'm not skilled enough with C to decipher what's happening in there, and the error message returned doesn't provide much value in terms of deciphering issues with the calling code. Can develop on other devices, but this is my main workstation so it's kinda a bummer.

I've also ensured that I have a port forward allowing traffic from the port specified by iot to this machine and that they are no firewall configs disallowing traffic on that port.

### Expected Behavior

The sample runs as detailed by the readme.

### Current Behavior

See description above, failing while making the TLS connection to AWS

### Reproduction Steps

sadly not 100% sure how. samples run fine on my 21 MacBook air. Can't run on my linux tower.

### SDK version used

^1.8.1

### Environment details (OS name and version, etc.)

Ubuntu 21.10, kernel: 5.13.0-44-generic

**Comment by TwistedTwigleg** [comment]
The `--key` argument needs the private key file, which might be causing the issue.

Another thing that *might* be causing the issue is the file paths not starting with `./` but I'm not positive if it would make a difference. It might be something to try though.

**Comment by IamFlowZ** [comment]
It was the policy as mentioned in the FAQ. The error message wasn't helpful and the only reason I eventually found it was because of running the V1 example where it requires you to pass a client_id. Supplied a client_id that looked like it would pass the policy and poof it worked. Cost me a few hours for something that seems poorly documented. Specifically that client_id exists and that an IoT thing could pass whatever client_id it wants, assuming that its unique for the connection pool.

**Comment by IamFlowZ** [comment]
So this was part of what was causing the confusion. I initially set up a thing for usage with the V1 SDK via the "learn" section of the IoT console. It created a policy that worked. I then switched to V2 and made a new thing, but used the same auto-generated policy from the first thing, not wanting to change something that already worked. 
V1's connect policy statement uses something like "sdk-nodejs-*" where it needed to be "test-*". The V2 docs don't make mention of the client_id and the example that the "learn" section doesn't explain the parameter. It seems like something minor and obviously going forward it's not going to be an issue but it was quite the hangup due to the implicit nature of it.
