### ISSUE TITLE
browser mqtt publish with QoS.AtMostOnce throws error

### ISSUE THREAD

**Issue by AnderbergE** [aws/aws-iot-device-sdk-js-v2#262]
### Describe the bug

I use this sdk in the browser to connect directly to aws iot. It is bundled into my code using Vite, which works without issues.
I import the mqtt module and setup the connection and then call the publish method with QoS: mqtt.QoS.AtMostOnce. This will send the message (verified in the aws iot test console), but shortly after an error message is printed in the console log.

### Expected Behavior

No error message

### Current Behavior

This is printed to the console log:
```
Uncaught (in promise) TypeError: packet is undefined
    MqttClientConnection mqtt.ts:419
    sendPacket client.js:183
    _sendPacket client.js:1250
    publishProc client.js:659
    publish client.js:665
    MqttClientConnection mqtt.ts:414
    MqttClientConnection mqtt.ts:413
    step aws-iot-device-sdk-v2.js:26700
    verb aws-iot-device-sdk-v2.js:26647
    __awaiter aws-iot-device-sdk-v2.js:26633
    __awaiter aws-iot-device-sdk-v2.js:26615
    publish aws-iot-device-sdk-v2.js:26917
    publish iotClient.js:41 (<- This is from my code)
```

### Reproduction Steps

import { mqtt } from 'aws-iot-device-sdk-v2';
const connection = new mqtt.MqttClient().new_connection(<options>);
connection.publish(<topic>, <payload>, mqtt.QoS.AtMostOnce);

### Possible Solution

According to what I have found:
This package uses aws-crt for mqtt. In aws-crt, browser/mqtt the publish function of the MqttClientConnection will expect two parameters in the callback function (error, packet) and then resolves with packet.messageId.
However. mqtt library client that is used does not return any values when QoS AtMostOnce is used (mqtt\lib\client:183).

A possible solution would be to check if packet parameter exists.

### SDK version used

1.8.2

### Environment details (OS name and version, etc.)

Windows 10, Vite 2.9.5

**Comment by jmklix** [comment]
This fix was added when the dependency was updated to 1.13.1. Please let us know if you get any more errors
