### ISSUE TITLE
Problem Compiling node-gyp in ARM7

### ISSUE THREAD

**Issue by skulljoi** [aws/aws-iot-device-sdk-js-v2#276]
### Describe the bug

I am not able to install this dependency in a amr7 device.
version 1.5.5 is working but
version 1.8.6 is not working

### Expected Behavior

-- Build files have been written to: /home/gitlab-runner/builds/4oPySPkg/0/abovetech/mqtt-publisher-component/mqtt-publisher/node_modules/aws-crt/build
info CMD BUILD
info RUN cmake --build "/home/gitlab-runner/builds/4oPySPkg/0/abovetech/mqtt-publisher-component/mqtt-publisher/node_modules/aws-crt/build" --config Release --target install
Scanning dependencies of target aws-c-common
[  0%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator.c.o
[  0%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator_sba.c.o
[  0%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/arch/arm/asm/cpuid.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/array_list.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/assert.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/byte_buf.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/cache.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/codegen.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/command_line_parser.c.o
[  1%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/common.c.o
[  2%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/condition_variable.c.o
[  2%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/date_time.c.o
[  2%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/device_random.c.o
[  2%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/encoding.c.o
[  2%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/error.c.o
[  2%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/fifo_cache.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/hash_table.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/lifo_cache.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/linked_hash_table.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_channel.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_formatter.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_writer.c.o
[  3%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/logging.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/lru_cache.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/math.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/memtrace.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/clock.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/condition_variable.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/device_random.c.o
[  4%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/environment.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/file.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/mutex.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/process.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/rw_lock.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/system_info.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/thread.c.o
[  5%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/time.c.o
[  6%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/priority_queue.c.o
[  6%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/process_common.c.o
[  6%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/promise.c.o
[  6%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/ref_count.c.o
[  6%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/resource_name.c.o
[  6%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/ring_buffer.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/statistics.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/string.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/task_scheduler.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/thread_scheduler.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/thread_shared.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/uuid.c.o
[  7%] Building C object crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/xml_parser.c.o
[  8%] Linking C static library libaws-c-common.a
[  8%] Built target aws-c-common
Scanning dependencies of target aws-checksums

### Current Behavior

CMake Error at CMakeLists.txt:38 (include):
  include could not find load file:
    AwsFindPackage
CMake Error at CMakeLists.txt:44 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-common" which is not an existing
  directory.
CMake Error at CMakeLists.txt:50 (add_subdirectory):
  add_subdirectory given source "crt/aws-lc" which is not an existing
  directory.
CMake Error at CMakeLists.txt:52 (add_subdirectory):
  add_subdirectory given source "crt/s2n" which is not an existing directory.
CMake Error at CMakeLists.txt:55 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-sdkutils" which is not an existing
  directory.
CMake Error at CMakeLists.txt:56 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-io" which is not an existing
  directory.
CMake Error at CMakeLists.txt:57 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-cal" which is not an existing
  directory.
CMake Error at CMakeLists.txt:58 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-compression" which is not an
  existing directory.
CMake Error at CMakeLists.txt:59 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-http" which is not an existing
  directory.
CMake Error at CMakeLists.txt:60 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-auth" which is not an existing
  directory.
CMake Error at CMakeLists.txt:61 (add_subdirectory):
  add_subdirectory given source "crt/aws-c-mqtt" which is not an existing
  directory.
CMake Error at CMakeLists.txt:62 (add_subdirectory):
  add_subdirectory given source "crt/aws-checksums" which is not an existing
  directory.
CMake Error at CMakeLists.txt:76 (include):
  include could not find load file:
    AwsCFlags
CMake Error at CMakeLists.txt:77 (include):
  include could not find load file:
    AwsSharedLibSetup
CMake Error at CMakeLists.txt:78 (include):
  include could not find load file:
    AwsSanitizers
CMake Error at CMakeLists.txt:85 (aws_set_common_properties):
  Unknown CMake command "aws_set_common_properties".
-- Configuring incomplete, errors occurred!
See also "/home/gitlab-runner/builds/xxx/node_modules/aws-crt/build/linux-arm/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1

### Reproduction Steps

create a project in a ARM7 device, try to install: 'npm i aws-iot-device-sdk-v2'
it will fail

### SDK version used

1.8.6

### Environment details (OS name and version, etc.)

Linux xxx-yyy 5.10.60-v7+ #1449 SMP Wed Aug 25 15:00:01 BST 2021 armv7l GNU/Linux

**Comment by TwistedTwigleg** [comment]
Thank you for reporting this issue! This issue should now be fixed in the latest SDK release: [v1.8.7](https://github.com/aws/aws-iot-device-sdk-js-v2/releases/tag/v1.8.7). Can you please give it a try and let us know if the latest release fixed the issue you are seeing?
