### ISSUE TITLE
Snyk ReDoS issue in ansi-regex nested dependency 

### ISSUE THREAD

**Issue by Pradeep976** [aws/aws-iot-device-sdk-js-v2#286]
### Describe the bug

My Snyk Dashboard shows that this package has a high level security issue in one of the packages that is installed by the dependencies of this package, 

The problem is with the package **ansi-regex@2.1.1** which causes Regular Expression Denial of Service ( REDOS ), this issue in fixed in the package **ansi-regex 3.0.1**

Can you please make use of the latest packages in order to solve this issue
<img width="1289" alt="Screenshot 2022-09-21 at 10 52 27 AM" src="https://user-images.githubusercontent.com/61454285/191446241-eadee963-6206-424d-9b67-dfd4eb5e7a84.png">

### Expected Behavior

No issues in Snyk

### Current Behavior

1 High issue reported in snyk

### Reproduction Steps

When running our external Snyk pipeline this issue is reported in the Snyk dashboard

### SDK version used

1.8.8

### Environment details (OS name and version, etc.)

Mac OS Monterey 12.4

**Comment by jmklix** [comment]
Thanks for bringing this up, but this sdk is dependent on the latest version of cmake-js. So I would recommend making a request for that to be updated.

**Comment by JohnSigs** [comment]
@jmklix cmake-js latest version now resolves this. Can it be updated. Thanks
