### ISSUE TITLE
AwsIotMqttConnectionConfigBuilder not export new_builder_for_websocket

### ISSUE THREAD

**Issue by Fabbi-GiangTB** [aws/aws-iot-device-sdk-js-v2#287]
### Describe the bug

I followed the example https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/index.ts but the editor compiler gives the error type static **new_builder_for_websocket** not exits.
I have check **declare aws_iot.d.ts** and it doesn't seem to exist either.

### Expected Behavior

declare static method  ** static  new_builder_for_websocket** and method ** with_use_websockets **

### Current Behavior

**declare aws_iot.d.ts** not exits **static new_builder_for_websocket** and method **with_use_websockets** class **AwsIotMqttConnectionConfigBuilder**

### Reproduction Steps

when use iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()...

### SDK version used

1.8.8

### Environment details (OS name and version, etc.)

Window

**Comment by jmklix** [comment]
Can you provide more details about the error you are getting? as well as what version of Windows and browser that you are using?

Just making sure but you are following these steps for the browser [pub_sub](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/README.md#browserpub_sub):
>## Browser/pub_sub
>
>This is a browser based version of the PubSub sample in JS.
>
>To run the sample:
>1) Configure your credentials and endpoint URL in `settings.js`.
    * You will need to setup a Cognito identity pool to run this sample. You can read how to setup a Cognito identity pool here: [AWS documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-create-identity-pool.html).
>
>2) Build the script via `npm install`
>
>3) Open index.html from your browser.

**Comment by Fabbi-GiangTB** [comment]
i using typescript, when i use method `new_builder_for_websocket` and `with_use_websockets`, editor show the below error message.
![image](https://user-images.githubusercontent.com/103635437/192455892-ccec9392-f5eb-4d46-9f90-88e091ade273.png)

it looks like it's not defined in the d.ts . file

**Comment by jmklix** [comment]
It looks like you are using an edited version of the browser pub_sub sample. Can you get the original sample running without this error?

Another suggestion is to make sure you importing the correct things at the top of your ts file
```ts
import { mqtt, iot, auth } from "aws-iot-device-sdk-v2";
import * as AWS from "aws-sdk";
```

**Comment by Fabbi-GiangTB** [comment]
i tried but it seems the editor will  **import {mqtt, iot} from 'aws-crt/dist/native'**.

I then tried to import the following
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/103635437/192677464-bed00e71-b749-4d8b-9e1b-f68c8366ca14.png">
It has been fixed.

**Comment by jmklix** [comment]
Glad that you where able to get it working with the correct imports. 

Did you run npm install twice? once to install the sdk and a second time to install the sample?

**Comment by Fabbi-GiangTB** [comment]
I only installed it once with npm with this package. Because this package is dependent on 'aws-crt' it is also downloaded. However I tried few times but can't import from aws-iot-device-sdk-v2

**Comment by jmklix** [comment]
Can you try building the sdk from [source](https://github.com/aws/aws-iot-device-sdk-js-v2#build-the-v2-sdk-and-crt-from-source)?

```sh
# Create a workspace directory to hold all the SDK files.
mkdir sdk-workspace
cd sdk-workspace
# Clone the repository to access the samples.
git clone --recursive https://github.com/aws/aws-iot-device-sdk-js-v2.git
# Ensure all submodules are properly updated.
cd aws-iot-device-sdk-js-v2
git submodule update --init --recursive
# Install the SDK.
npm install
# Then you can run the samples following the instructions in the samples README.
```
