### ISSUE TITLE
MQTT Client does no connect after IOS update to 16.0.2

### ISSUE THREAD

**Issue by 3AGSystemsShervin** [aws/aws-iot-device-sdk-js-v2#289]
### Describe the bug

Hi team,

I have been using the JavaScript device SDK to subscribe to MQTT topics from AWS IOT Core and Sitewise inside my Angular 10 web app. I have had no issues on my website for chrome and safari users until now. The other day I upgraded my IOS device to version 16.0.2 which is the latest. Now I cannot receive any messages from Sidewise or IoT core on my website. After some debugging I found out that the "MqttClient" does not connect anymore. Usually I have a console log on the MqttClient.on('connect') function to make sure connection is successful. This is no longer firing off. And none of the messages are received. This is only on IOS and safari for the latest update (16.0.2)

Please let me know if I can somehow fix this issue by resetting some setting or anything as I am completely stock. 

Thanks,

Shervin

### Expected Behavior

I expect the MqttClient to connect and be able to subscrite to MQTT messages from AWS Iot Core and Sitewise

### Current Behavior

No exceptions are thrown. It just does not connect when I run the connect

### Reproduction Steps

Install the aws-iot-device-sdk-js-v2 via NPM

Create a simple webpage that uses the the MQTT client to connect using a access key and secret. subscribe to a given topic. It will work on IOS 15 but not the latest one on version 16. Below is a sample of the code I use in my JavaScript 

//Below is the code to instantiate the client and than use it to connect to a given AWS account using access key and secret

```ts
import { io, iot, mqtt } from 'aws-iot-device-sdk-v2';
import { MqttClientConnection } from 'aws-crt/dist/native/mqtt';


  private mqttClientConnection: MqttClientConnection;

 const clientBootstrap = new io.ClientBootstrap();

    const myClient = iot.AwsIotMqttConnectionConfigBuilder
      .new_with_websockets({
        region: 'us-west-2',
        credentials_provider: '',
        proxy_options: undefined
      });


    const config = myClient.with_client_id(uniqueGuid)
      .with_clean_session(true)
      .with_credentials('us-west-2', 'SOME AWS ACESS KEY', 'SOME AWS SECRET')
      .with_endpoint('SOME AWS ENDPOINT')
      .build();



    const client = new mqtt.MqttClient(clientBootstrap);


    this.mqttClientConnection = client.new_connection(config);


    // tslint:disable-next-line:variable-name
    this.mqttClientConnection.on('connect', (_session_present) => {

    console.log('Connection is sucessfull');
    });

    this.mqttClientConnection.connect().catch(ex => {
          console.log(ex );

    });
```

//Below is the code to subscribe to a given topic from AWS Iot Core or Sitewise

```ts
      this.mqttClientConnection.subscribe(topicName, mqtt.QoS.AtLeastOnce, (topic, payload) => {

        const decoder = new TextDecoder('utf8');
        const message = decoder.decode(payload);
        const obj = JSON.parse(message);

console.log(obj );
       
      }).catch(ex => {
        console.log(ex);
      });
```
### Possible Solution

Not sure maybe its a security issue which I might need to set some setting on the phone.

### SDK version used

V2

### Environment details (OS name and version, etc.)

iOS 16.0.2

**Comment by jmklix** [comment]
Can you include logs from when you are trying to connect? 

Make sure to sanitize any personal info.
```js
const level = parseInt(io.LogLevel["TRACE"]);
io.enable_logging(level);
```

**Comment by 3AGSystemsShervin** [comment]
> Can you include logs from when you are trying to connect?
> 
> Make sure to sanitize any personal info.
> 
> ```js
> const level = parseInt(io.LogLevel["TRACE"]);
> io.enable_logging(level);
> ```

@jmklix 

Looking at the LogLevel enum I can see the one I need is number 6. I might be doing it wrong  but the issue I'm running into is when I add the code you have provided above I get the following error on the console. 

**"aws_iot_device_sdk_v2__WEBPACK_IMPORTED_MODULE_5__.io.enable_logging is not a function"**

![image](https://user-images.githubusercontent.com/68082681/193146787-4aa1e6f2-81c4-4966-809c-4a9c2fe9d9be.png)

**Comment by 3AGSystemsShervin** [comment]
> Can you include logs from when you are trying to connect?
> 
> Make sure to sanitize any personal info.
> 
> ```js
> const level = parseInt(io.LogLevel["TRACE"]);
> io.enable_logging(level);
> ```

Below is my connect to AWS function code. Also my import statements:

import { io, iot, mqtt } from 'aws-iot-device-sdk-v2';
import { MqttClientConnection } from 'aws-crt/dist/native/mqtt';

 connectToAws(): void {

    let guidString = this.generateGuid();
    let timeNowInMilliseconds = new Date().getTime();
    let uniqueGuid = guidString + timeNowInMilliseconds;


    io.enable_logging(6);

    const clientBootstrap = new io.ClientBootstrap();

    const myClient = iot.AwsIotMqttConnectionConfigBuilder
      .new_with_websockets({
        region: 'us-west-2',
        credentials_provider: '',
        proxy_options: undefined
      });


    const config = myClient.with_client_id(uniqueGuid)
      .with_clean_session(true)
      .with_credentials('us-west-2', 'SOME ACCESS KEY', 'SOME ACESS SECRET')
      .with_endpoint('SOME END POINT ')
      .build();



    const client = new mqtt.MqttClient(clientBootstrap);


    this.mqttClientConnection = client.new_connection(config);



    // tslint:disable-next-line:variable-name
    this.mqttClientConnection.on('connect', (_session_present) => {

  


    });

 

    this.mqttClientConnection.connect().catch(ex => {

      console.log(ex);
    });





  }

**Comment by bretambrose** [comment]
I would suggest looking at the packet-level traffic via a tool like wireshark.  It sounds like potentially an OS-level filtering or firewall issue.

**Comment by 3AGSystemsShervin** [comment]
@jmklix @bretambrose 

I figured out the issue. Thanks to this thread on GitHub (https://github.com/mqttjs/MQTT.js/issues/1326)

@jmklix 
Before closing this ticket, can you please answer my question above about how to enable logging and accessing the logs, as it could be very useful for me in the future.


So for anyone having similar issue. When you update the OS it enables a setting on Safari which causes this issue. The safari experimental feature "NSURLSession WebSocket" was enabled by default.  You need to disable it under the safari settings.
Navigate to Settings > Safari > Advanced > Experimental Features and disable "NSURLSession WebSocket"

Thanks everyone for your help

**Comment by jmklix** [comment]
Sorry for the confusion, but this sdk doesn't currently support logging in the browser. What I mentioned earlier is for node.js

**Comment by 3AGSystemsShervin** [comment]
> Sorry for the confusion, but this sdk doesn't currently support logging in the browser. What I mentioned earlier is for node.js

OK no worries. Thanks for your help

Il close the issue now
