### ISSUE TITLE
Can it run on BrightSign?

### ISSUE THREAD

**Issue by jafl** [aws/aws-iot-device-sdk-js-v2#29]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

BrightSign's OS is Linux, but it is completely closed.  There is no way to upload system libraries, only JavaScript.

**Comment by justinboswell** [comment]
This package is available from npm, and our npm package will download the native binaries from S3, but does not have any system library dependencies. As long as you can install from npm and connect to S3, you should be able to use this library. If you cannot, then you would need to compile the [aws-crt-nodejs](https://github.com/awslabs/aws-crt-nodejs) package yourself locally.

**Comment by jafl** [comment]
Sorry, that's what I meant.  There is no way to install binaries on BrightSign.  I have to assemble the package on my laptop (my code + node_modules), and then upload it to the BrightSign device.

**Comment by justinboswell** [comment]
Oh, I see. In that case, you'd have to do something like tarball the module, along with its dependencies after building locally. You can refer to the README on https://github.com/awslabs/aws-crt-nodejs for the prereqs to build locally.

Something like:
```
> npm install
> tar czf mypackage.tar.gz package.json dist node_modules
> scp mypackage.tar.gz mydevice:/tmp/mypackage.tar.gz
> unpack and run...
```

**Comment by jafl** [comment]
I'll have to try it and see if the binaries will run.  Thanks.
