### ISSUE TITLE
Sample browser/pub_sub erroneous

### ISSUE THREAD

**Issue by croraf** [aws/aws-iot-device-sdk-js-v2#301]
### Describe the issue

I copied the code from [index.ts](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/index.ts) and installed two packages needed 

    "aws-iot-device-sdk-v2": "^1.8.11",
    "aws-sdk": "^2.1267.0",

In this code, the `iot` and `auth` variables, which are imported from `aws-iot-device-sdk-v2` library, are missused.

In the code:
 -  `auth` uses properties which do not exist on its interface `auth.CredentialsProvider` and `auth.AWSCredentials`
 - `iot.AwsIotMqttConnectionConfigBuilder` uses function `iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()` which does not exist on its interface

### Links

https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser/pub_sub

**Comment by jmklix** [comment]
You shouldn't need to make any changes other than in the settings.js as mentioned in the setup [instructions](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples#browserpub_sub):

> ## Browser/pub_sub
> 
> This is a browser based version of the PubSub sample in JS.
> 
> To run the sample:
> 1) Configure your credentials and endpoint URL in `settings.js`.
>     * You will need to setup a Cognito identity pool to run this sample. You can read how to setup a Cognito identity pool here: [AWS documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-create-identity-pool.html).
> 
> 2) Build the script via `npm install`
> 
> 3) Open index.html from your browser.

**Comment by croraf** [comment]
Yes I do. As I explained, `iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()` does not exist at all.

`AwsIotMqttConnectionConfigBuilder` comes from `aws-crt@1.14.8` library, is reexported from `aws-iot-device-sdk-v2`.

Similarly `auth.CredentialsProvider` and `auth.AWSCredentials` do not exist at all on the `auth` interface

**Comment by bretambrose** [comment]
The browser and node public APIs of the CRT dependency have slightly different interfaces.  The build step (webpack) for the browser sample needs to be followed as well; just copying index.ts isn't sufficient.

**Comment by croraf** [comment]
@bretambrose 

But the webpack for browser/pub_sub https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/webpack.config.js only contains Node core module polyfils. (Which is needed for Buffer and process and other polyfils, but I do have this included.)

This doesn't provide the missing items mentioned in the original post.

**Comment by bretambrose** [comment]
My (very recent, very limited) understanding is that webpack will use/prefer the 'browser' directives in package.json, which exist both for the crt (https://github.com/awslabs/aws-crt-nodejs/blob/main/package.json#L15) and the v2 SDK (https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/package.json#L20), leading to a browser-runnable build for the sample.  If you just npm install the sample and run it, it works.

I'm glad you brought this up though, even if it's a no-op, because looking closer, this is likely the source of problems people are having with angular or using webpack and node together with the CRT/SDK.

**Comment by croraf** [comment]
For some reason it is taking it from the "aws-crt/dist" for me. Check also this @bretambrose .

**Comment by croraf** [comment]
It actually seems to take the runtime code from `aws-crt/dist.browser`, but the types are taken from `aws-crt/dist`. If I put ts-ignore above https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/index.ts#L81 it runs.

**Comment by bretambrose** [comment]
Maybe https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/tsconfig.json#L40 is another missing piece from your project re-creation?

**Comment by bretambrose** [comment]
It seems like we definitely need a "How to consume from the browser" guide or section in the readme.  None of this obvious.

**Comment by croraf** [comment]
> Maybe https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/pub_sub/tsconfig.json#L40 is another missing piece from your project re-creation?

Good find. But I don't think this line does anything. `"node_modules/aws-iot-device-sdk-v2/dist/browser"` does not exist. And it does not solve my issue.

My issue is kind of bypassed locally with https://github.com/aws/aws-iot-device-sdk-js-v2/issues/301#issuecomment-1340037524 . It is ofc not a solution, because I tamper with the node_modules content.

**Comment by croraf** [comment]
OK. I found what was the issue with the `"path: "`.  When I hovered on it it says "Path mapping to be computed relative to baseUrl option." 

Because my baseUrl is `./src` I had to adjust the path to be `"path" = "../node_modules/...etc..."`.
