### ISSUE TITLE
Not able to connect to MQTT with browser - connection establish stalled

### ISSUE THREAD

**Issue by croraf** [aws/aws-iot-device-sdk-js-v2#303]
### Describe the bug

I'm trying a code sample provided in the repo [browser/pub_sub](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser/pub_sub).

I'm identifying through Cognito identity pool. I set to allow Unauthenticated identities. I  created and assigned a new role to both unauthenticated and authenticated identities. That role was created with default policy document.

After I run the application I see in Cognito that the identity has been created as anonymous identity.

Everything seems to be executed properly but the connection does not get established and instead enters in a "pending state" (reconnecting infinitely, check below image),

![image](https://user-images.githubusercontent.com/19698636/205633377-9e97d405-5b71-4a1d-ae24-95384f6bab15.png)

I did enter the region and endpoint of IoT Core.
```
export const AWS_REGION = "eu-west-1";
export const AWS_IOT_ENDPOINT = "...-ats.iot.eu-west-1.amazonaws.com";
```

The endpoint is the one I found in https://eu-west-1.console.aws.amazon.com/iot/home?region=eu-west-1#/connectdevice

Also in https://eu-west-1.console.aws.amazon.com/iot/home?region=eu-west-1#/policyhub I have created a policy with this
![image](https://user-images.githubusercontent.com/19698636/206060652-7052b798-6638-48e3-bfd9-029c7aa7d023.png)
 

### Expected Behavior

Connection establish should either work or report a meaningful error.

### Current Behavior

It just repeatedly tries to make a WS connection. It doesn't throw an error (provides a message on why it fails).

### Reproduction Steps

Run the snippet.

### SDK version used

1.18.11

### Environment details (OS name and version, etc.)

Ubuntu 22.04 (Chrome 108 browser)

**Comment by croraf** [comment]
As I expected the reason was security. 
I edited permissions to the role that was returned from Cognito. 
https://us-east-1.console.aws.amazon.com/iamv2/home?region=eu-west-1#/roles

For example:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "iot:Connect",
                "iot:Subscribe"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by croraf** [comment]
@jmklix  In the code samples documentation I suggest to add notes about IAM role permissions that have to be set in order to run the samples. (per sample would be best)

**Comment by croraf** [comment]
Also, I don't know if it is possible that the WS throws with an error, rather than stalling, when it cannot connect due to permission failure.

Hopefully returning an error like the following:
>  "iot:connect and iot:receive" permissions are missing thus connection cannot be established

**Comment by jmklix** [comment]
I will work on adding the IAM role permissions to the samples documentation. 

As for adding the warning, that currently can't be done with how IoT Core works. This is because when permissions are not valid it just doesn't respond with any message. So the sample (and the js-v2 sdk) has no way of knowing why the connection isn't successful.

**Comment by jmklix** [comment]
After running through the setup process again I don't think that this needs to be added to the readme. The IAM roles needed for this are different from usual when setting up IoT things. But, it correctly creates the correct IAM policy for you when creating the congnito Identity pools. There are other places where you can find more info about how to set up IAM policies, so I don't think it would be helpful to add it to this samples readme. Please let me know if you disagree or have any other suggestions to improve this sdk. Thanks again.
