### ISSUE TITLE
  iotshadow is undefined

### ISSUE THREAD

**Issue by zhuwujing** [aws/aws-iot-device-sdk-js-v2#309]
### Describe the bug

    "react": "17.0.2",
    "react-native": "0.66.0",

import {iotshadow} from "aws-iot-device-sdk-v2"  iotshadow is undefined

### Expected Behavior

iotshadow is not undefinded

### Current Behavior

iotshadow is undefined

### Reproduction Steps

import {iotshadow} from "aws-iot-device-sdk-v2" 
 console.log("iotshadow=", iotshadow);

### SDK version used

1.9.0

### Environment details (OS name and version, etc.)

    "react-native": "0.66.0"     Android

**Comment by jmklix** [comment]
How are you setting up your react app? Are you trying to add this to a newly created react app?

**Comment by zhuwujing** [comment]
@jmklix Yes,when i change sdk to "aws-iot-device-sdk", I can run and build my react-native app.   When I use "aws-iot-device-sdk-v2" for a new  react-native project (not react app) ,it`s not well.

**Comment by jmklix** [comment]
What steps are you taking to setup your react-native project?
