### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by jmklix** [aws/aws-iot-device-sdk-js-v2#331]
### Describe the feature

This sdk currently has some problems when running with React and it is not officially supported yet. This is something that we are planning on fixing, but we don't have a set time for when that will be finished.

These are the current issues related to this:
 - [React - Webpack warning on build](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/323)
 - [Unable to handle/catch aws-crt error Connection closed](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/302)
 - [Uncaught ReferenceError: Buffer is not defined](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/295)
 
 Please feel free to :+1: this issue if this is something that you want!

### Use Case

aws-iot-device-sdk-js-v2 to work with React framework without errors.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

all main browsers

**Comment by massi-ang** [comment]
See https://github.com/awslabs/aws-crt-nodejs/issues/425 for workaround

**Comment by bretambrose** [comment]
This should be addressed in release v1.10.1
