### ISSUE TITLE
Sample code gets "has no default export" error

### ISSUE THREAD

**Issue by narutaro** [aws/aws-iot-device-sdk-js-v2#345]
### Describe the bug

There is an error when compiling `index.ts` in `aws-iot-device-sdk-js-v2/samples/node/pub_sub`

### Expected Behavior

Compile without an error. 

### Current Behavior

The error...

```
$ tsc index.ts 
../../../node_modules/aws-crt/dist/native/auth.d.ts:9:8 - error TS1192: Module '"/Users/me/Projects/typescript/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/native/binding"' has no default export.

9 import crt_native from './binding';
         ~~~~~~~~~~

../../../node_modules/aws-crt/dist/native/http.d.ts:9:8 - error TS1192: Module '"/Users/me/Projects/typescript/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/native/binding"' has no default export.

9 import crt_native from './binding';
```

### Reproduction Steps

```
tsc index.ts
```

I added `"allowSyntheticDefaultImports": true` in the `tsconfig.json` but still get the same error. 

### SDK version used

v2

### Environment details (OS name and version, etc.)

Mac

**Comment by narutaro** [comment]
@TwistedTwigleg - after adding `"allowSyntheticDefaultImports": true` in the `tsconfig.json` and build whole project with just `tsc` generated `index.js` without an error. Thank you for your kind explanation!

**Comment by TwistedTwigleg** [comment]
Awesome, happy to hear that it helped! I am going to close this issue then 🙂
