### ISSUE TITLE
Shared subscription on MQTT3 client doesn't receive messages

### ISSUE THREAD

**Issue by nebbles** [aws/aws-iot-device-sdk-js-v2#357]
### Describe the bug

Establishing a shared subscription using an MQTT3 client does not throw an error, however, no messages are consequently received.

### Expected Behavior

According to the blog annoucement[^1] and the technical documentation[^2], "AWS IoT Core supports Shared Subscriptions for both MQTT 3 and MQTT 5". I would expect an MQTT client to be able to receive messages after a successful subscription with a ShareName.

[^1]: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-iot-core-mqtt5-shared-subscriptions-cloudwatch-metrics/
[^2]: https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html#mqtt5-shared-subscription

### Current Behavior

MQTT3 client connects and then subscribes without throwing errors, but no messages are received.

Independently verified that messages should be received by both 
1. checking legacy (non-share) subscription with the same topic filter
2. checking shared subscription of interest works in the test client in the AWS console (which it does)

### Reproduction Steps

Perform a standard subscribe with the SDK using an MQTT3 client

### SDK version used

1.11.0 (and previously tested on 1.8.10)

### Environment details (OS name and version, etc.)

Node 16.20.0

**Comment by jmklix** [comment]
We have been able to reproduce this and I can confirm that this is not working correctly with MQTT3.11. We are looking into ways to fix this.

**Comment by jmklix** [comment]
https://github.com/awslabs/aws-c-mqtt/pull/274

**Comment by TwistedTwigleg** [comment]
The fix has been merged into `aws-c-mqtt` but has not yet been pulled into the Javascript CRT or SDK yet. I am going to reopen this issue for now until we have the change pulled up into the CRT and SDK.

**Comment by TwistedTwigleg** [comment]
The feature has been released in the latest SDK version. Please give it a try.
Closing issue.

**Comment by nebbles** [comment]
Working in production for us now using MQTT3 client 🎉 thanks for the quick fix!
