### ISSUE TITLE
Documentation / Example for Device Shadow

### ISSUE THREAD

**Issue by lumulumu** [aws/aws-iot-device-sdk-js-v2#36]
Hi,

I am trying to port from v1 to v2.

Do you have an example how to use device shadow? Or can you hint me where I can find a good starting point.

Basic pub/sub is fine and I get along with this.

Many thanks and best,
Manuel

**Comment by graebm** [comment]
Apologies, we haven't written a Shadow sample yet for the V2 JS SDK. There are V2 SDKs for 3 other languages, and if you're comfortable reading another language you could see how it's done in the [Python](https://github.com/aws/aws-iot-device-sdk-python-v2/blob/master/samples/shadow.py), [Java](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/master/samples/Shadow/src/main/java/shadow/ShadowSample.java), or [C++](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/master/samples/shadow/shadow_sync/main.cpp) Shadow samples.

The Shadow API is nearly identical across languages in the V2 SDKs. The only real differences the async primitives used in each language, and CamelCase vs snake_case for variable names.

**Comment by jmklix** [comment]
Update: This is an example that we are still interested in adding but we have not gotten to it yet. We will update in the future if our priorities change.

**Comment by yonatangross** [comment]
@jmklix is there an update when the example will be uploaded?

I want to try upload one myself but I'm missing some guidance how to do it exactly...

**Comment by ZhouLihua** [comment]
Hi, Is there an example for browser. Like the example of v1.  https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples/browser/mqtt-explorer

**Comment by jmklix** [comment]
@yonatangross sorry, but there is no update currently

@ZhouLihua there is no v2 example for a broswers, but you can always create a feature request for one.
