### ISSUE TITLE
example pub/sub using Amazon provided `run.sh` fails in macOS

### ISSUE THREAD

**Issue by batzCognition** [aws/aws-iot-device-sdk-js-v2#376]
### Describe the bug

Following the instructions for onboarding a new single device results in failures that other people have brought up as issues on this package as well as the python variation. 

### Expected Behavior

I expect to be able to run unmodified example code without errors.

### Current Behavior

While it'll work as described in a `node` docker container, on macOS 13.3.1 (a) it returns 
```
./start.sh
___________
Running pub/sub sample application...
Failed to connect: aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
```

meanwhile following the steps below my docker container runs it correctly
```
root@5e11814a3f11:/example_simulated_device# ./start.sh
____________________________
Running pub/sub sample application...
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":1}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":2}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":3}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":4}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":5}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":6}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":7}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":8}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":9}
Publish received. topic:"sdk/test/js" dup:false qos:1 retain:false
Payload: {"message":"Hello world!","sequence":10}
```

### Reproduction Steps

- Go to AWS iOT Core
- "create single device" 
- fill in forms
- download the node connection package
- `chmod +x run.sh`
- `./run.sh`
- fail ❌
- give far too many permissions (iot:\*, resource:\*) 
- wait for IAM to propagate 
- `./run.sh`
- fail ❌
- `docker run -it -v /ABSOLUTE/PATH/example_simulated_device:/example_simulated_device  node bash`
- `cd /example_simulated_device`
- `./run.sh`
- succeed ✅

### Possible Solution

I think the testing/validation for the "Mac/linux kit" isn't run on up to date macOS versions

### SDK version used

aws-iot-device-sdk-v2  version: "1.0.0-dev"

### Environment details (OS name and version, etc.)

macOS 13.3.1 (a), M1 Pro

**Comment by yasminetalby** [comment]
Hello @batzCognition,

Thank you very much for your submission.

I have tested the behavior for this on MacOS 13.3.1 for the following SDK: aws-iot-device-sdk-js-v2
which behave as expected.

To clarify, are you following this guide :  https://docs.aws.amazon.com/iot/latest/developerguide/iot-quick-start.html ?

If that is the case, are you making any modification/changes to the start.sh file or the certificates in the connect_device_package?

I also see that you mention run.sh rather than start.sh in your submission. I am unsure if that is on purpose.

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
