### ISSUE TITLE
Support for AWS_CONTAINER_CREDENTIALS_FULL_URI

### ISSUE THREAD

**Issue by skulljoi** [aws/aws-iot-device-sdk-js-v2#390]
### Describe the feature

I would like to use the AWS_CONTAINER_CREDENTIALS_FULL_URI for grab the credentials for this SDK

### Use Case

I have a component that connects to the IoT core and the credentials are delivered by a container

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.13.0

### Environment details (OS name and version, etc.)

Linux Arm / raspberrypi

**Comment by skulljoi** [comment]
Waiting for more tests, looks like it works, it just does not have a sample

**Comment by yasminetalby** [comment]
Hello @skulljoi,

Thank you very much for your submission.
Could you provide more details about your specific use case?

Best,

Yasmine

**Comment by skulljoi** [comment]
As I mentioned it just works we just need to set an environment variable

		process.env.AWS_EC2_METADATA_DISABLED = false;
		const configBuilder = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets({
			region: 'eu-west-1',
			credentials_provider: auth.AwsCredentialsProvider.newDefault(),
		});

then it can connect using websocket and the container credentials
