### ISSUE TITLE
when we generate pkg with aws-iot-device-sdk in node js .. it has connection issue..

### ISSUE THREAD

**Issue by patson12** [aws/aws-iot-device-sdk-js-v2#397]
### Describe the bug

Hello,
i have an node  app using aws-iot-device-sdk working fine in development mode when i change it in production mode and create executabl;e file with pkg. using this lib https://www.npmjs.com/package/pkg.. it gives me connection error.. otherwise its working perfact in development mode only issue when i create executable linux file.. 

### Expected Behavior

it should work as smooth and without bugs like development mode.. 

### Current Behavior

connection issue i guess. its in production mode error so cant clearly rectifyu..

### Reproduction Steps

just created pkg file with aws-iot-client ..

### SDK version used

version": "2.2.12

### Environment details (OS name and version, etc.)

linux, node 14.17.0, npm 6.14.14

**Comment by yasminetalby** [comment]
Hello @patson12 ,

Thank you very much for your submission,
Could you please provide the log associated with the behavior as well as how you are using the aws-iot-device-sdk-js-v2 and step by step reproduction? Unfortunately, there is not enough information provided in your submission to investigate the behavior you are experiencing.
This seems similar to the behavior reported in this issue: https://github.com/aws/aws-iot-device-sdk-js-v2/issues/315 

I also invite you to checkout the [Troubleshooting guide ](https://www.npmjs.com/package/aws-iot-device-sdk#troubleshooting ) provided by npm which covers connectivity issue
Per their documentation:

> If you have problems connecting to the AWS IoT Platform when using this SDK or running the example programs, there are a few things to check:

>Region Mismatch: You have to use the certificate created in the same region as your host end point.
>Duplicate Client IDs: Within your AWS account, the AWS IoT platform will only allow one connection per client ID. Many of the example programs run as two processes which communicate with one another. If you don't specify a client ID, the example programs will generate random client IDs, but if you are using a [JSON configuration file](https://www.npmjs.com/package/aws-iot-device-sdk#configurationFile), you'll need to explictly specify client IDs for both programs using the '-i' command line option.
>Invalid NPM Version: To run the browserize.sh script which prepares the browser example applications, you'll need to use npm version 3. This is because browserize.sh expects package dependencies to be handled using the npm version 3 strategy, which is [different than the strategy used in npm version 2](https://docs.npmjs.com/how-npm-works/npm3). If you're having trouble running the browser application examples, make sure that you're using npm version 3. You can check your npm version with npm -v.

Note that this documentation is for aws-iot-device-sdk-js, their documentation for aws-iot-device-sdk-js-v2 does not contain a troubleshooting guide however this is general guidance which should be applicable to both version.

Thank you very much for your collaboration.

Sincerely,

Yasmine

**Comment by patson12** [comment]
i dont know qhy you set this minor priority issues. we are working on this since 3 days..if any node js developers in your team , please connect them.. everythings are working fine when we run this program from code in development mode, but if we make pkg with this library https://www.npmjs.com/package/pkg .. then connection issue found.. .

**Comment by yasminetalby** [comment]
Hello @patson12 ,

Thank you very much for your answer.
Priority for issue is determined by multiple factors, currently this issue falls under a p3 priority issue (p3 is defined as minor but is more a label to define the issue in comparison to other issue submission). Priority can be changed in time as well if the investigation reveals that it falls under a different priority category. I sincerely apologies if the definition seemed dismissive of your current experience.

It seems that you are using the v1 so this would be an issue for the aws-iot-device-sdk-js repository rather than aws-iot-device-sdk-js-v2. I noticed that you have just opened an [issue submission](https://github.com/aws/aws-iot-device-sdk-js/issues/421) there so I will close this submission in favor of the other one.

Thank you very much for your time and collaboration.
Sincerely,

Yasmine

**Comment by patson12** [comment]
hello yasmine,
my probl;em is solved now.. thank you for your support :)

**Comment by yasminetalby** [comment]
I am glad to hear @patson12 ,

If you have any questions or support need in the future, feel free to open an issue or discussion in our repository.

I wish you a great day!

Sincerely,

Yasmine
