### ISSUE TITLE
Browser disconnects

### ISSUE THREAD

**Issue by thdxr** [aws/aws-iot-device-sdk-js-v2#418]
### Describe the bug

When using the SDK in the browser it eventually throws a CrtError. Reconnect attempts are made but fail with the same error.  Refreshing the page fixes it.

Is there something about the configuration that expires?

### Expected Behavior

n/a

### Current Behavior

n/a

### Reproduction Steps

n/a

### SDK version used

1.14.0

### Environment details (OS name and version, etc.)

browser

**Comment by bretambrose** [comment]
What is the error?  What is the timeframe?  Do you have a minimal sample that reproduces it?  How are you sourcing credentials?  The more information you provide, the more likely it is that we can dig into the problem.

**Comment by thdxr** [comment]
This is my configuration - using a custom authorizer

```
      const config = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets()
        .with_clean_session(true)
        .with_client_id("client_" + createId())
        .with_endpoint(url)
        .with_custom_authorizer(
          "",
          <url>,
          "",
          <token>
        )
        .with_keep_alive_seconds(30)
        .build();
```

i've tried to notice any pattern but i cannot.  it seems to disconnect randomly and a reconnect will fail *unless* i create the whole client again

logging the error in `.on("interrupt")` just gives a `-1` instead of an error

**Comment by bretambrose** [comment]
What happens if you increase keep alive significantly?  What browser are you using?  Safari is notorious for throttling JS execution for backgrounded tabs so severely that keep alive exchanges get completely broken and the client becomes unusable until foregrounded.

**Comment by thdxr** [comment]
good idea - this is chrome on linux but we've seen this issue across every platform

when you say increase keep alive do you mean make it a larger number? or make it a smaller number

**Comment by bretambrose** [comment]
Try bumping it up to something like 1200
