### ISSUE TITLE
v1.0.5: samples/node/basic_discovery crashes

### ISSUE THREAD

**Issue by matoxp** [aws/aws-iot-device-sdk-js-v2#42]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Describe the bug**
The basic-discovery sample in this repo crashes on startup:
```
$ node dist/index.js -r certificates/root-CA.crt -k certificates/private.key -c certificates/cert.pem -n my-device-id --region eu-west-1
Discovery Response:
{"gg_groups":[{"gg_group_id":"...","cores":[{"thing_arn":"arn:aws:iot:eu-west-1:...:thing/...","connectivity":[{"id":"AUTOIP_127.0.0.1_0","host_address":"127.0.0.1","port":8883,"metadata":""},{"id":"AUTOIP_172.17.0.3_1","host_address":"172.17.0.3","port":8883,"metadata":""}]}],"certificate_authorities":["-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n"]}]}
Trying endpoint={"id":"AUTOIP_127.0.0.1_0","host_address":"127.0.0.1","port":8883,"metadata":""}
Trying endpoint={"id":"AUTOIP_172.17.0.3_1","host_address":"172.17.0.3","port":8883,"metadata":""}
Connected to endpoint={"id":"AUTOIP_127.0.0.1_0","host_address":"127.0.0.1","port":8883,"metadata":""}
Connected to endpoint={"id":"AUTOIP_172.17.0.3_1","host_address":"172.17.0.3","port":8883,"metadata":""}
[ERROR] [2020-05-11T10:45:15Z] [00007f5e2cb2f700] [mqtt-client] - id=0x3422450: Unhandled packet type received
[ERROR] [2020-05-11T10:45:15Z] [00007f5e2cb2f700] [mqtt-client] - id=0x344d4a0: Unhandled packet type received
node: ../nptl/pthread_mutex_lock.c:352: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust' failed.
Signal received: 749920080, errno: 32606
################################################################################
Resolved stacktrace:
################################################################################
0x00007f5e2cebd17b: ?? ??:0
0x00000000000d3633: s_print_stack_trace at module.c:?
0x0000000000011390: __restore_rt at ??:?
0x00007f5e2fbad428: ?? ??:0
0x00007f5e2fbaf02a: ?? ??:0
0x000000000002dbd7: __assert_fail_base at assert.c:92
0x000000000002dc82: __assert_fail at ??:?
0x0000000000009bf5: __pthread_mutex_lock_full at ??:?
0x000000000133ae39: uv_mutex_lock at thread.c:330
0x00000000009df7e7: napi_acquire_threadsafe_function at ??:?
0x00007f5e2ce0bba1: ?? ??:0
0x00000000000d6546: s_on_connection_resumed at mqtt_client_connection.c:?
0x00000000000eec42: s_packet_handler_connack at client_channel_handler.c:?
0x00000000000ef96d: s_process_read_message at client_channel_handler.c:?
0x000000000011dba1: s_s2n_handler_process_read_message at s2n_tls_channel_handler.c:?
0x00000000001143ce: s_do_read at socket_channel_handler.c:?
0x0000000000114a42: s_on_readable_notification at socket_channel_handler.c:?
0x000000000011c0aa: s_on_socket_io_event at socket.c:?
0x0000000000117a72: s_main_loop at epoll_event_loop.c:?
0x000000000018557b: thread_fn at thread.c:?
0x00000000000076ba: start_thread at ??:?
0x00007f5e2fc7f41d: ?? ??:0
```

**SDK version number**
1.0.5

**Platform/OS/Hardware/Device**
* Ubuntu 16.04.6  LTS (x86_64)
* node-v12.16.3-linux-x64
* greengrassd running in docker container, GGC version: 1.10.1-RC3, Target: linux-x86_64, Build: 6008587457

**Comment by KaibaLopez** [comment]
Hi @matoxp ,
I'm not able to reproduce this issue, but there are a few things I wanna know about how you're trying to run the sample.
Our sample is meant to run kind of the same way as [this tutorial](https://docs.aws.amazon.com/greengrass/latest/developerguide/test-comms.html). can you tell me a bit about your greengrass core setup? 
The way you're running the sample you'd be trying to both subscribe and publish to the same thing and on the "sdk/test/NodeJSv2" topic, so you'd have to have the thing as part of your green core group devices and a subscription to itself on the same topic. Is that what you're trying to get?
Also, just to help me reproduce this, could you try to have a device/thing + iot console subscription on your greengrass core subscriptions and try to run the sample like:
`node dist/index.js --ca_file root-CA.crt --cert subscribeThing.cert.pem --key subscribeThing.private.key --thing_name subscribeThing --region eu-west-1 --mode "subscribe" --topic "myTopic/"`
and then use the console iot tester to publish on the topic. Let me know if you get a similar error.

**Comment by matoxp** [comment]
@KaibaLopez I have port 8883 forwarded from localhost to my greengrass core docker container (-P 8883:8883). This results in two IP addresses detected during discovery (localhost and the docker network interface). I am able to connect to these two sockets using e.g. `openssl s_client`. And the iot-device-sdk-v2 also connects to these two ports:
```
Connected to endpoint={"id":"AUTOIP_127.0.0.1_0","host_address":"127.0.0.1","port":8883,"metadata":""}
Connected to endpoint={"id":"AUTOIP_172.17.0.3_1","host_address":"172.17.0.3","port":8883,"metadata":""}
```
But then crashes after emitting those errors:
```
[ERROR] [2020-05-11T10:45:15Z] [00007f5e2cb2f700] [mqtt-client] - id=0x3422450: Unhandled packet type received
[ERROR] [2020-05-11T10:45:15Z] [00007f5e2cb2f700] [mqtt-client] - id=0x344d4a0: Unhandled packet type received
```
On the gg core side, the GGConnManager.log shows this:
```
[INFO]-Added a new device connection. {"deviceId": "...", "protocol": "mqtt"}
[INFO]-Removed a device from the system.      {"deviceId": "...", "protocol": "mqtt"}
[INFO]-Added a new device connection. {"deviceId": "...", "protocol": "mqtt"}
[INFO]-Removed a device from the system.      {"deviceId": "...", "protocol": "mqtt"}
```

*But*: By removing either localhost or the docker address from the list of greengrass core endpoints, the client no longer crashes after MQTT connect. Seems like the SDK gets confused dealing with a core endpoint list containing both localhost and a docker address.
