### ISSUE TITLE
Users who have manually changed their clock cannot connect to mqtt(short issue description)

### ISSUE THREAD

**Issue by kimdanielarthur-cowlabs** [aws/aws-iot-device-sdk-js-v2#422]
### Describe the bug

When a user has changed the time on their device they are not able to connect to the mqtt

### Expected Behavior

Expect some way to override the checking of current time on device ala correctClockSkew

### Current Behavior

Have not seen any options to set the correctClockSkew for the iot-device-sdk v1 or v2

### Reproduction Steps

1. Change time on your device to be out of sync with actual time
2. Try to connect to the mqttt
3. See that connection fails

### Possible Solution

Allow to forcibly override the checks on users local device time

### SDK version used

v1.16.0

### Environment details (OS name and version, etc.)

android/ios react native

**Comment by bretambrose** [comment]
Spent a little time looking into this.  In your case, you're using the browser implementation and unfortunately I'm hitting a roadblock there that may prevent a nice solution.  As near as I can tell, the websocket implementation (and mqtt-js) do not surface any information about the failing http response sent by AWS when the websocket handshake upgrade is signed by a skewed timestamp (the core problem here).  Without the date header sent by IoT Core, we have no way to automatically calculate what the skew adjustment should be.

A less-nice alternative is for us to provide an optional callback that lets you adjust the timestamp used in signing.  It's more work for you, but your application could hit some kind of trusted time service and inject that result into the signing process.

**Comment by kimdanielarthur-cowlabs** [comment]
Thanks for looking deeper at it!

Yes I was thinking it could be a workaround to even have an option to pass some timeOffset to the client on construction and it would use that offset for all underlying requests within the sdk?

Kim

**Comment by bretambrose** [comment]
Well, the problem just becomes yours now, as it's not clear how you can get a trustworthy timestamp in the browser (ie no NTP).  

Another possibility I should mention: if you set up [custom authentication to IoT Core](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser/custom_authorizer_connect) then the connection process does not need an accurate timestamp (because sigv4 signing isn't used), only one good enough to do x509 cert chain validation for TLS.

**Comment by kimdanielarthur-cowlabs** [comment]
Thanks will look into the custom authentication.

For valid time in our case we already make a request to our servers to
retrieve endpointurl and authentication details for the mqtt. So in theory
we could ourselves calculate any time offset before the client
authenticates with mqtt? Without having ntp locally in client.

**Comment by kimdanielarthur-cowlabs** [comment]
Awesome if the SDK just magically solves it of course :D

**Comment by jmklix** [comment]
This isn't something that we plan on adding to this sdk, so I'll be closing this issue. As @bretambrose mentioned above it's not possible to access the raw http response with the date header when running js in browser applications.
