### ISSUE TITLE
Support for Alpine Linux

### ISSUE THREAD

**Issue by accnops** [aws/aws-iot-device-sdk-js-v2#43]
**Is your feature request related to a problem? Please describe.**
Currently, there is no Alpine Linux support.

When using following example:

File `index.js`:
```
require('aws-crt');
```

File `Dockerfile`:
```
FROM node:12.16.2-alpine
RUN apk add gcompat
RUN npm install aws-crt@1.1.3
COPY index.js .
CMD ["node", "index.js"]
```

Command:
`docker build -t aws-crt-test . && docker run aws-crt-test`

It seems like `aws-crt` is "hijacking" the process, and printing:
```
Signal received: 32, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
Signal received: 1530847424, errno: 32668
Signal received: 0, errno: 0
...
```
And then exiting.

**Describe the solution you'd like**
Apparently, it's because [there's not yet an alpine target where it's linked against libmusl](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/26#issuecomment-624905865). That would be great, since I can then use this library on Alpine.

**Comment by jmklix** [comment]
Update: This is a feature that we are still interested in adding but we have not gotten to it yet. We will update in the future if our priorities change.

**Comment by cazzer** [comment]
@jmklix any update on your roadmap? From my experience, Alpine is a pretty common base image for Node containers so I'd imagine this would be a common blocker for other teams, as it is for mine.

Adding a reference to what base images _do_ work would be a massive help - or any other workarounds you could suggest!

**Comment by bretambrose** [comment]
Initial alpine support has been added to the CRT package and incorporated into the SDK as of the https://github.com/aws/aws-iot-device-sdk-js-v2/releases/tag/v1.16.0 release
