### ISSUE TITLE
There's no documentation on how to refresh/update the credentials.

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-iot-device-sdk-js-v2#460]
Hi. I'm using this library in a React project to have the ability to subscribe to events. I use the cognito identity method on the browser side to get credentials. It was very simple to do in v1 but now I'm trying to upgrade to v2. In v1 I could do `updateWebSocketCredentials` to update the credentials, but I can't find anything similar in v2.

I've tried various methods in v2, such as using `new_with_websockets` that accepts options:
```
let config = iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets({
    region: awsConfiguration.region,
    service: "wss",
    credentials_provider: {
      getCredentialsAsync: async () => {
        const credentials: any = await getCredentialsAsync();
        if (credentials) {
          expiration = credentials.Expiration;
          return {
            accessKeyId: credentials.AccessKeyId,
            secretAccessKey: credentials.SecretKey,
            sessionToken: credentials.SessionToken,
            expiration: credentials.Expiration,
          };
        }
        return null;
      },
    },
  })
```

But that doesn't seem to work.

Is there no method to update the credentials when they expire? I found one React example that uses something called `.with_credential_provider` that doesn't seem to exist any longer.

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/d81d4995d61bd901e2e49288ef8d88284a1f091b/samples/browser/react_sample/src/PubSub.tsx#L85

Any help would be appreciated.

### Links

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/d81d4995d61bd901e2e49288ef8d88284a1f091b/samples/browser/react_sample/src/PubSub.tsx#L85

**Comment by bretambrose** [comment]
with_credentials_provider hasn't gone anywhere as far as I know: https://github.com/awslabs/aws-crt-nodejs/blob/main/lib/browser/aws_iot.ts#L239

**Comment by jmklix** [comment]
The `.with_credential_provider(provider)` option does still exist and the current sample in [main](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/d81d4995d61bd901e2e49288ef8d88284a1f091b/samples/browser/react_sample/src/PubSub.tsx#L85) still uses it. 

And to refresh the credentials you just need to call `refreshCredentials()`. You can find that in the api docs [here](https://aws.github.io/aws-iot-device-sdk-js-v2/browser/classes/auth.CredentialsProvider.html#refreshCredentials)

**Comment by bretambrose** [comment]
There should be no need to refresh the credentials if the sample pattern is followed.  A recurrent task does it for you.

**Comment by raRaRa** [comment]
Thanks for the quick response @bretambrose 

when I try to use `.with_credential_provider(provider)`

I get: `Property 'with_credential_provider' does not exist on type 'AwsIotMqttConnectionConfigBuilder'.`

I'm on aws-iot-device-sdk-v2 version 1.19.0 and aws-sdk 2.1541.0. Any clue what could be going on?

If I check the definition of `with_endpoint`, then I find it in /node_modules/aws-crt/dist/native/aws_iot.d.ts - but I see no presence of `with_credential_provider` in there.

**Comment by raRaRa** [comment]
Oh I figured out the issue. I forgot to set up the path in tsconfig.json. Sorry & thanks for the help. I highly recommend updating README with more details on browser usage.

**Comment by bretambrose** [comment]
You're somehow ending up with the node source and not the browser source.  If you're using typescript you can ok, you figured it out (https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/samples/browser/react_sample/tsconfig.json#L16)

**Comment by bretambrose** [comment]
> Oh I figured out the issue. I forgot to set up the path in tsconfig.json. Sorry & thanks for the help. I highly recommend updating README with more details on browser usage.

I agree, we should put a section in both aws-crt-nodejs and this repo as well.
