### ISSUE TITLE
Need proper documentation to get started with AWS OTA Update

### ISSUE THREAD

**Issue by manojrampur** [aws/aws-iot-device-sdk-js-v2#470]
### Describe the issue

Hi Team,

We're planning to start AWS OTA Updates from Scratch, aiming to handle firmware updates, delta updates, security patches, file updates, and more, but we're feeling a bit overwhelmed by all the information out there. We want to make sure we're on the right track and not getting lost in the process.

### Links

Could you please guide us on the best approach along with the steps and share the correct links to get started?

Thanks in Advance!!

**Comment by jmklix** [comment]
Are you looking to use [FreeRTOS](https://docs.aws.amazon.com/freertos/latest/userguide/freertos-getting-started-modular.html#explore-freertos-libraries) or [greengrass](https://docs.aws.amazon.com/greengrass/v2/developerguide/update-greengrass-core-v2.html)? This sdk does not support over the air (OTA) updates directly. You can use them via greengrass which is supported with this sdk. You can find more information in the links I provided, but please let me know if you have any other questions.
