### ISSUE TITLE
Connection resumed after long downtime, but no messages received

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-iot-device-sdk-js-v2#475]
### Describe the bug

My issue is 100% like https://github.com/aws/aws-iot-device-sdk-js-v2/issues/117 which is now closed. 

1. Network is down for over several hours, and then it goes back up and resumes the MQTT connection.
2. Everything looks normal but the client never recieves any messages. Kinda as if the subscription got lost?

Based on the information on the old issue that I referenced, it says I need to manually re-subscribe if `session_present` is false when the connection is resumed in `connection_success` My initial thought was that this library would handle the re-connection by itself.

I tried debugging the internal state and saw that the connection_count increases with time, when network is down and goes up after several hours. Is it because a new session was created?

I would love to have more information on this.

Thanks!

### Expected Behavior

I expected the connection to resume without any silent failure.

### Current Behavior

The connection is resumed but no messages are received

### Reproduction Steps

1. Connect to MQTT and subscribe to a topic
2. Turn off the network on the PC for 2-4 hours
3. Turn on the network on the PC
4. Whe connection is resumed, note how the client recieves no messages. Also note that session_present is false in connection_success

### Possible Solution

Re-subscribe to the topics automatically if re-connection is handled by this SDK.

### Additional Information/Context

Using browser version

### SDK version used

1.19.1

### Environment details (OS name and version, etc.)

Browser Chrome on MacOS

**Comment by raRaRa** [comment]
@bretambrose Do you know if this is by design or if this is a bug? I encountered the same issue today but it behaved differently. 

After MQTT resumed the connection, it took around 5 minutes until I started receiving messages. I even tried unsubscribing and subscribing to the same topic without any luck. It does feel like an internal bug since unsubbing and subbing again to the topic had no effect.

Is there a way to turn on internal debug logging? (on browser)

**Comment by bretambrose** [comment]
The SDK does not perform resubscription for you.  Resubscription sounds easy but quickly devolves into edge cases.  Ultimately, it feels like a correct application will still need to handle the edge case where resubscription fails anyways.  

The browser variant is a wrapper around mqtt-js, so debug logging turns into interacting with its logging facilities (which in my experience are very unsatisfactory).  I have the following in my notes from years ago, no guarantees, I have memories that every time I've tried to do this it's been an annoying/unfruitful process:

```
    let debug = require('debug');
    debug.enable('mqttjs*');
    debug.log = console.info.bind(console);
```

**Comment by jmklix** [comment]
There will always be edge cases for reconnecting that will need to be handled correctly. This feature isn't something we are currently planning on implementing because of resource constraints.
