### ISSUE TITLE
Add support for LWT

### ISSUE THREAD

**Issue by abarke** [aws/aws-iot-device-sdk-js-v2#477]
### Describe the feature

When connecting, allow configuration of LWT (Last-Will and Testament)

1. LWT Topic
2. LWT QoS
3. LWT Message
4. LWT Retain

### Use Case

Testing LWT with devices

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v1.19.1

### Environment details (OS name and version, etc.)

Windows 11

**Comment by jmklix** [comment]
We already have this implemented for this sdk for both [node](https://aws.github.io/aws-iot-device-sdk-js-v2/node/interfaces/mqtt5.ConnectPacket.html#will) and [browser](https://aws.github.io/aws-iot-device-sdk-js-v2/browser/interfaces/mqtt5.ConnectPacket.html#will). Please let us know if you have any other questions and/or feature requests for this sdk!
