### ISSUE TITLE
npm audit flags dep sbo@1.1.3 with high severity vulnerabilities due to lodash.set

### ISSUE THREAD

**Issue by 0x-a6** [aws/aws-iot-device-sdk-js-v2#493]
### Describe the bug

When running `npm audit` with `aws-iot-device-sdk-v2@1.19.3` result:
```
# npm audit report

lodash.set  *
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix`
node_modules/lodash.set
  sbo  >=1.1.3
  Depends on vulnerable versions of lodash.set
  node_modules/sbo

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix
```

### Expected Behavior

when running npm audit should result in 0 vulnerabilities

### Current Behavior

2 high vulnerabilities detected

### Reproduction Steps

6.5.0-27-generic kernel, 22.04.1-Ubuntu x86_64 Linux, 
node v18.19.1, 
npm 10.5.2
install the package
run npm audit

### Possible Solution

Perhaps it's related to an old object copy issue mentioned here: https://github.com/lodash/lodash/issues/5809 I don't know. But it seems like an old vulnerability for such a modern version of dependency

### SDK version used

1.19.3

### Environment details (OS name and version, etc.)

6.5.0-27-generic kernel, 22.04.1-Ubuntu x86_64 Linux, node v18.19.1, npm 10.5.2

**Comment by 0x-a6** [comment]
```
backend@1.0.0 /path/to/project/backend
└─┬ aws-iot-device-sdk-v2@1.19.3
  └─┬ 2@3.0.0
    └─┬ sbo@1.1.3
      └── lodash.set@4.3.2
```
Does this mean I need to raise this on the [sbo](https://github.com/lamansky/sbo) repository?

**Comment by bretambrose** [comment]
No, someone added a pointless top-level dependency.  

https://github.com/aws/aws-iot-device-sdk-js-v2/pull/494 removes

**Comment by 0x-a6** [comment]
@bretambrose Thank you! Confirmed works for me.
