### ISSUE TITLE
Error: AWS CRT binary not present in any of the following locations on Nextjs app running npm run dev

### ISSUE THREAD

**Issue by prakashmallow** [aws/aws-iot-device-sdk-js-v2#496]
### Describe the bug

I facing an issue while installing the `aws-iot-device-sdk-v2` package. After importing `iot` and `mqtt`, I attempt to run the Next.js app using `npm run dev` but encounter the below errors

```
Error: AWS CRT binary not present in any of the following locations:
        /bin/darwin-arm64-cruntime/aws-crt-nodejs.node
    at eval (webpack-internal:///./node_modules/aws-crt/dist/native/binding.js:110:11)
    
- error node_modules/aws-crt/dist/native/binding.js (109:0) @ eval
- error Error: AWS CRT binary not present in any of the following locations:
        /bin/darwin-arm64-cruntime/aws-crt-nodejs.node
    at eval (webpack-internal:///./node_modules/aws-crt/dist/native/binding.js:110:11)
```

### Expected Behavior

After importing `iot` and 'mqtt` from `aws-iot-device-sdk-v2` the nextjs app running as we expect normally

### Current Behavior

Currently, it's throwing the below error we can `import { it, mqtt } from 'aws-iot-device-sdk-v2'` on the Nextjs app component and run on it.

```
Error: AWS CRT binary not present in any of the following locations:
        /bin/darwin-arm64-cruntime/aws-crt-nodejs.node
    at eval (webpack-internal:///./node_modules/aws-crt/dist/native/binding.js:110:11)
    
- error node_modules/aws-crt/dist/native/binding.js (109:0) @ eval
- error Error: AWS CRT binary not present in any of the following locations:
        /bin/darwin-arm64-cruntime/aws-crt-nodejs.node
    at eval (webpack-internal:///./node_modules/aws-crt/dist/native/binding.js:110:11)
```

### Reproduction Steps

1. Install `aws-iot-device-sdk-v2` on the Nextjs app.
2. import `iot` and `mqtt` from `'aws-iot-device-sdk-v2` and `iot` and `mqtt` APIs are used on the Nextjs app component.
3. run `npm run dev` on terminal
4. the above-mentioned mention error throwing on the terminal

### SDK version used

1.19.5

### Environment details (OS name and version, etc.)
| Environment | version |
| macOS | 14.4.1 |
| processer | m1 chip |
| node 20.12.1 |
| nextjs | 13.4.7 |

**Comment by hari-prasad-a** [comment]
### Facing same issue

I am also facing the same issue with `aws-iot-device-sdk-v2` package. When I import `iot` and `mqtt` in an Next.js application and while running the app below error is thrown.


```
Error: AWS CRT binary not present in any of the following locations:
        /bin/darwin-arm64-cruntime/aws-crt-nodejs.node
    at eval (webpack-internal:///./node_modules/aws-crt/dist/native/binding.js:110:11)
```

**Comment by prakashmallow** [comment]
@jmklix My Next.js app is running with JSX components instead of TSX. I'm encountering an issue where the @module-federation/nextjs-mf npm package is causing problems. When I remove the @module-federation/nextjs-mf npm package from my app, it works fine with aws-iot-device-sdk-v2. However, my application requires the @module-federation/nextjs-mf npm package

**Comment by xiazhvera** [comment]
I think Next.js allows you to specify the library paths through ` jsconfig.json`. 
Reference:  https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases

**Comment by prakashmallow** [comment]
@xiazhvera  @jmklix After applying the changes mentioned in the jsconfig.json file, I'm still encountering the same issue.

**Comment by jmklix** [comment]
Can you provide more detailed steps for setting up nextjs app?

I can get the [next.js getting started app](https://nextjs.org/docs/getting-started/installation) working when I combine it with the [pub_sub_mqtt5 sample](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/browser/pub_sub_mqtt5) from this repo, while making only a few minor changes. I can also provide more detailed steps on how I set that up if you would like (it's in TS not JS).

**Comment by prakashmallow** [comment]
@jmklix 

https://github.com/hari-prasad-a/mqtt-container-app
https://github.com/hari-prasad-a/mqtt-child-app

Please clone the above repositories with all the settings already completed for the Next.js apps. Follow the below steps:

1. Install packages on both repositories.
2. First, run mqtt-child-app.
3. After successfully running mqtt-child-app, proceed to start mqtt-container-app.

**Comment by prakashmallow** [comment]
@jmklix Please check [this comment](https://github.com/module-federation/core/issues/2462#issuecomment-2101954274) and give guidances for how to configure `aws-iot-device-sdk-v2` on webpack config.externals on Nextjs app

**Comment by prakashmallow** [comment]
@jmklix any update?

**Comment by xiazhvera** [comment]
It seems like the issue more related to a webpack configuration rather than a problem with our SDK. I'm not positive if we would have a good solution for it. 
Unfortunately, I'm a bit short to dive deeper into it right now. I'll be able to revisit the issue in two weeks.

**Comment by xiazhvera** [comment]
I made several attempts to fix the issue following the suggestions mentioned in [module-federation](https://github.com/module-federation/core/issues/2462), but unfortunately, I wasn't able to resolve it. Currently, I don't have a viable solution for this problem. I'll leave the issue open in case anyone has further updates or suggestions.

**Comment by blakeage** [comment]
I don't think this is isolated to NextJS.  I'm using Webpack 5.92.0 to package up a module, running on OS X Sonoma 14.5, with Node 16.16.0.  Importing a module from aws-iot-device-sdk-js-v2 seems to be the cause.

I've attached a very basic project that also shows the issue.

[aws-crt-problem.zip](https://github.com/user-attachments/files/15891730/aws-crt-problem.zip)

**Comment by prakashmallow** [comment]
@xiazhvera @jmklix  Any update for this issue?

**Comment by xiazhvera** [comment]
Just in case anyone is still looking into this issue. It seems there is a workaround discussed here: 
https://github.com/module-federation/core/issues/2462
