### ISSUE TITLE
publish userProperties aren't returned in the PUBACK?

### ISSUE THREAD

**Issue by dhyeyyyy** [aws/aws-iot-device-sdk-js-v2#499]
### Describe the issue

Looking to create a file-persistent queue for MQTT, was hoping to use [userProperties](https://aws.github.io/aws-iot-device-sdk-js-v2/node/interfaces/mqtt5.PublishPacket.html#userProperties) to be able to link a publish with a pub ack. However- trying to experiment with this dummy program, the response contains an empty `userProperties` field. Is this the expected behaviour? How else could I go about connecting PUBACK's with their respective publishes? 

```javascript
const { iot, mqtt5, io } = require("aws-iot-device-sdk-v2");
io.enable_logging(io.LogLevel.DEBUG);

const certPath = "/home/dhyey/certificates";
const builder =
  iot.AwsIotMqtt5ClientConfigBuilder.newDirectMqttBuilderWithMtlsFromPath(
    host,
    certPath + "/certificate.pem.crt",
    certPath + "/private.pem.key"
  );
builder.withConnectProperties({
  clientId: "0x7effff03",
  keepAliveIntervalSeconds: 60,
});


builder.withAckTimeoutSeconds(5);

const config = builder.build();

const client = new mqtt5.Mqtt5Client(config);

client.on("error", (e) =>
  console.log("ERRORRR", e.toString(), client.getOperationalStatistics())
);

client.on("attemptingConnect", (e) => console.log("attemptconnect", e));

client.on("connectionSuccess", (e) => console.log("success", e));

client.on("connectionFailure", (e) =>
  console.log("failure", e, client.getOperationalStatistics())
);

client.on("disconnection", (e) =>
  console.log("disconnect", e, client.getOperationalStatistics())
);

client.on("stopped", (e) => console.log("stopped", e));
(async () => {
  try {
    while (true) {
      client.start();
      const res = await client.publish({
        qos: mqtt5.QoS.AtLeastOnce,
        topicName,
        payload: "helloo",
        userProperties: [{'name': 'id', 'value': 'hehe'}]
      });
      console.log("queue", client.getOperationalStatistics());
      console.log("result", JSON.stringify(res));
      await new Promise((resolve) => setTimeout(resolve, 5000));
    }
  } catch (err) {
    console.log("fatal", err);
  }
})();
```

output:
```
result {"type":4,"reasonCode":0,"userProperties":[]}
```

### Links

https://aws.github.io/aws-iot-device-sdk-js-v2/node/interfaces/mqtt5.PublishPacket.html#userProperties

**Comment by bretambrose** [comment]
The mqtt5 protocol does not establish any relationship between the user properties of a publish and its associated puback.  For Iot Core (and probably every one MQTT broker I'm aware of), publish user properties are only reflected in the publish packets sent to subscribers.
 
The only way to do correlation between publish and puback is by packet id.

**Comment by dhyeyyyy** [comment]
There's no way to fetch this packet ID at the application layer?

**Comment by bretambrose** [comment]
No.  We don't allow it as an input so it doesn't make sense as an output.  

Beyond that, packet ids come from a very small space (16 bits) and will be constantly reused over the course of a connection or session.  They would make a terrible persistence key.

Making it correct is certainly more complicated than this, but supposing you have a durable key-value store of packets (say uuid -> publish-packet-as-json), it seems that just chaining on to the publish promise with a delete key operation (on success) would be reasonable (pseudocode):

```
async function durablePublish(kvStore: ??, key: string, client: Mqtt5Client) {
   let publishPacket = kvStore.get(key);
   publishPacket.qos = QoS.AtLeastOnce;
   let puback = await client.publish(packet);
   if puback.reasonCode == PubackReasonCode.Success {
      kvStore.delete(key);
   }
}
```

**Comment by dhyeyyyy** [comment]
Got it- thanks so much :) !
