### ISSUE TITLE
Not able to call fromCognitoIdentityPool on iOS (browser)

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-iot-device-sdk-js-v2#531]
### Describe the bug

I just noticed that Chrome on iOS devices fails when calling `fromCognitoIdentityPool`. But it works on my desktop machine just fine with Chrome and Safari.

Example code:

```
    this.cachedCredentials = await fromCognitoIdentityPool({
      // Required. The unique identifier for the identity pool from which an identity should be
      // retrieved or generated.
      identityPoolId: this.options.IdentityPoolId,
      clientConfig: { region: this.options.Region },
    })();
```

The error I get:
```
DEBUG endpoints Resolving endpoint from template: {
  "url": "https://cognito-identity.{Region}.{PartitionResult#dnsSuffix}",
  "properties": {},
  "headers": {}
}

ERROR[object Object]
```

 I believe the error is related to `TypeError: JSON.stringify cannot serialize cyclic structures`

### Expected Behavior

I expect it to run through the last step where it errors out, which should resolve to:

```
endpoints Resolved endpoint: {
  "headers": {},
  "properties": {},
  "url": "https://cognito-identity.eu-west-1.amazonaws.com/"
}
```

### Current Behavior

Currently it errors on 
```
DEBUG endpoints Resolving endpoint from template: {
  "url": "https://cognito-identity.{Region}.{PartitionResult#dnsSuffix}",
  "properties": {},
  "headers": {}
}
```

### Reproduction Steps

Just run `fromCognitoIdentityPool` from Chrome in iOS 

### Additional Information/Context

@aws-sdk/credential-providers is on version 3.664.0

### SDK version used

1.21.1

### Environment details (OS name and version, etc.)

iPhone 13 Pro, Google Chrome

**Comment by bretambrose** [comment]
I'm not following how this is an issue with the IoT SDK.

**Comment by raRaRa** [comment]
> I'm not following how this is an issue with the IoT SDK.

I wasn't sure where to report this. The samples use fromCognitoIdentityPool but they no longer work on Chrome in iOS. Do you know of any alternative ways to use cognitio identity pool without using fromCognitoIdentityPool

Should I report this to @aws-sdk/credential-providers

**Comment by bretambrose** [comment]
> 
> Should I report this to @aws-sdk/credential-providers

That seems like it would get the best results.  I'm not sure of the support status of that major version though.

**Comment by raRaRa** [comment]
Seems like it's a bug within some library that aws-sdk uses. I've created a separated report in the aws-sdk repo.
I also solved this by manually fetching the AWS Cognito identity and credentials without using the `fromCognitoIdentityPool` method.
