### ISSUE TITLE
Connection failure does not trigger 'connection_failure' nor 'error' event

### ISSUE THREAD

**Issue by beata111** [aws/aws-iot-device-sdk-js-v2#532]
### Describe the bug

After creating new MqttClientConnection, when a connection failure happens no "connection_failure" nor "error" event is triggered (after successful connection the "connection_success" works fine).

### Reproduction Steps

Setup "connection_failure" and "error" event listeners.
Disable internet connection, create a new MqttClientConnection (MqttClient.new_connection(config)). 
Error: "WebSocket connection to '...; failed:" is visible in the console.
No "connection_failure" nor "error" event is being triggered.

### SDK version used

1.20.0

### Environment details (OS name and version, etc.)

macOS 15

**Comment by jmklix** [comment]
Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this?
