### ISSUE TITLE
Please update ./start.sh to include 'npm install aws-cert'

### ISSUE THREAD

**Issue by BraedenQ** [aws/aws-iot-device-sdk-js-v2#59]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**

**SDK version number**
Version 2

**Platform/OS/Hardware/Device**
Cloud9/EC2 with Amazon Linux 2 AMI

**To Reproduce (observed behavior)**
1) Go to IoT Core in the AWS Console
2) On the left side menu, select the Onboard sub-menu
3) select Get Started
4) Select Linux/OSX 
5) Select Node.js
6) Download the connection kit
7) upload to Ec2 Instance and unzip the connect_device_package.zip
8) chmod +x ./start.sh
9) run ./start.sh

**Expected behavior**
Start the basic pub/sub sample

**Logs/output**
nternal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/ec2-user/environment/connect_device_package/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/bin/linux-x64/aws-crt-nodejs.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ec2-user/environment/connect_device_package/aws-iot-device-sdk-js-v2/node_modules/aws-crt/dist/native/binding.js:53:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Additional context**
I installed the aws-crt npm package and reran the npm installs at the appropriate directory levels. After doing this, I was able to rerun ./start.sh with success.

**Comment by jmklix** [comment]
What version of Node.js and npm do you have currently installed? Try updating these if they are not current and then see if ./start.sh works when starting in new directory.

**Comment by BraedenQ** [comment]
I had Node v10.15.0 and npm 6.15.4.

Just updated to Node v10.21.0 and npm 6.14.5 with the same result of "Error: /lib64/libc.so.6: version `GLIBC_2.25' not found".

Still had to 1) npm install aws-crt and 2) npm install in both the "connect_device_package" dir and the "connect_device_package/aws-iot-device-sdk-js-v2/samples/node/pub_sub" to get ./start to work correctly.

**Comment by jmklix** [comment]
What glibc version do you have? 
Try this: `ldd --version`

**Comment by BraedenQ** [comment]
ldd (GNU libc) 2.17

**Comment by jmklix** [comment]
We are looking into a solution, but it appears that the pre-build native binary for aws-crt is a higher version of the system standard library (glibc) than what is on the system.
