### ISSUE TITLE
Bug in Fleet provision example

### ISSUE THREAD

**Issue by timeswind** [aws/aws-iot-device-sdk-js-v2#60]
https://github.com/aws/aws-iot-device-sdk-js-v2/blob/9b80d9df12d42f10b723636801fb636130697055/samples/node/fleet_provisioning/index.ts#L181-L184

https://github.com/aws/aws-iot-device-sdk-js-v2/blob/9b80d9df12d42f10b723636801fb636130697055/samples/node/fleet_provisioning/index.ts#L200-L203

"subscribeToCreateKeysAndCertificateRejected" is called twice, I believe you are thinking about using "subscribeToRegisterThingRejected" instead since it is bind to callback named "registerRejected"

**Comment by bretambrose** [comment]
Thanks for finding this.  The sample has been updated with this fix and a number of others.
