### ISSUE TITLE
Not sure how to migrate from V1 to V2 also how to integrate when sample codes are not clear.

### ISSUE THREAD

**Issue by subratcap** [aws/aws-iot-device-sdk-js-v2#64]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
const level : io.LogLevel = parseInt(io.LogLevel[argv.verbosity.toUpperCase()]);
io.enable_logging(level);
```

**Additional context**

**Comment by jmklix** [comment]
Hello subratcap and sorry for the long wait. In general you need to rewrite code from v1 to v2 as there where some major changes to to sdk. What exactly are you trying to do? and what samples do you need for v2?
