### ISSUE TITLE
Document going from nothing to a working sample in the readme

### ISSUE THREAD

**Issue by Doff3n** [aws/aws-iot-device-sdk-js-v2#66]
**Is your feature request related to a problem? Please describe.**
For each sample, add a readme that gives explicit step-by-step instructions to go from nothing to a working sample
**Describe the solution you'd like**
Example of solution, a bit simplified:

---
# Fleet provisioning:
## Prerequisite
You need to set up a fleet provision template in the aws console or via terminal
https://docs.aws.amazon.com/freertos/latest/lib-ref/c-sdk/provisioning/provisioning_tests.html#provisioning_system_tests_setup

## Quickstart
The certificate request is transferred over mqtt(?). 
 
1. install the SDK

`npm install aws-iot-device-sdk-js-v2`

2. main flow:
``` javascript
//iotidentity is used for certificate creation and registering things(?)
import iotidentity from 'aws-iot-device-sdk-js-v2'
//creates the sertificate
iotidentity.publishCreateKeysAndCertificate(input a, input b)
//creates the thing
iotidentity.publishRegisterThing(input a, input b, input c)
```

input b: QoS describes levels of QoS in the MQTT message. 
  - Level 0, completes as soon as the packet is sent.
  - Level 1, completes when PUBACK is received.
  - Level 2 is not supported by AWS IoT.

## Sample
- Sample
---

**Comment by runemadsen** [comment]
I just want to 👍 this one. The old `aws-iot-device-sdk-js` package describes exactly how to use it with nice code examples for everything. I have been using `aws-iot-device-sdk-js` for years, and after looking at the documentation for `v2` for an hour, I have honestly no clue on how to use it.

**Comment by jmklix** [comment]
I'm am currently working on this and testing it for all aws iot v2 languages. [Here](https://github.com/aws/aws-iot-device-sdk-js-v2/tree/fleet-provisioning-docs/samples#fleet-provisioning-detailed-instructions) is a link to the branch with the JavaScript instructions. I have tested them and have got them working on windows. Please let me know if you have any trouble or are confused with any of the steps.

**Comment by runemadsen** [comment]
Thanks! I think what people are looking for is a written walk-through with code examples that explains the node API. These samples, despite being much better than nothing, are pretty complex and written in Typescript. Take a look at the [README for `v1`](https://github.com/aws/aws-iot-device-sdk-js). That's the kind of documentation that makes it easy to get started.

**Comment by hanyufoodles** [comment]
The samples here in v2 are sort of `CLI` like code which is completely different from v1.
Basically with v1 I can follow the guide and build code that creates a device, connect it the `aws-iot core` and execute jobs. A guide to upgrade from v1 will be greatly helpful.
