### ISSUE TITLE
Register thing with fleet provisioning error code InvalidCertificateOwnershipTokenerrorMessage

### ISSUE THREAD

**Issue by eszymko** [aws/aws-iot-device-sdk-js-v2#69]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
I try to get https://github.com/aws/aws-iot-device-sdk-js-v2/tree/master/samples/node/fleet_provisioning work.
I changed this in the code:
in the index.js sample change :(line 179)
yield identity.subscribeToCreateKeysAndCertificateRejected(registerThingSubRequest, aws_crt_1.mqtt.QoS.AtLeastOnce, (error, response) => registerRejected(error, response));
by
yield identity.subscribeToRegisterThingRejected(registerThingSubRequest, aws_crt_1.mqtt.QoS.AtLeastOnce, (error, response) => registerRejected(error, response));

and I got :
RegisterThing ErrorResponse for statusCode=:400errorCode=:InvalidCertificateOwnershipTokenerrorMessage=:Certificate ownership token cannot be empty.

**SDK version number**
v2
**Platform/OS/Hardware/Device**
What are you running the sdk on?
ubuntu

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
see bug description

**Expected behavior**
I expect the registration to work :)

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
const level : io.LogLevel = parseInt(io.LogLevel[argv.verbosity.toUpperCase()]);
io.enable_logging(level);
```

**Additional context**

**Comment by bretambrose** [comment]
Please update to the latest SDK which fixes the incorrect subscribe.  Beyond that, can you supply your exact command line (x-out your ats endpoint if you feel like, but it's not really necessary)?

**Comment by eszymko** [comment]
great work fine :)
node index.js --endpoint xxxx-ats.iot.ca-central-1.amazonaws.com --ca_file AmazonRootCA1.pem --cert 94c9f6450c-certificate.pem.crt --key 94c9f6450c-private.pem.key --template_name LairdGateways --template_parameters '{"SerialNumber":"11"}'
