### ISSUE TITLE
Stupid question...Cognito?

### ISSUE THREAD

**Issue by tronious** [aws/aws-iot-device-sdk-js-v2#70]
I'm looking at this new SDK considering porting over from V1.

With that in mind we are using Cognito for authentication.  Can I still use that with this SDK?

**Comment by rccarper** [comment]
Hello, we don't currently have support directly in this SDK for Cognito.  However, we do have an example of how to use the Cognito support in the aws-sdk with an MQTT client.  That sample is in our Node.js CRT repo, which this SDK uses: https://github.com/awslabs/aws-crt-nodejs/blob/master/samples/browser/pub_sub/index.ts
