### ISSUE TITLE
Cordova - does it play well?

### ISSUE THREAD

**Issue by tronious** [aws/aws-iot-device-sdk-js-v2#71]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?  Android, IOS.  Cordova application

**Describe the question**

Having an issue with V1 of the SDK running in the context of a Cordova application.

We cannot get it to work with IOS running as a Cordova app.  The httpResponse.body is always undefined with a response code of 200

Trying to see if upgrading to V2 will help.

Does this SDK play well with Cordova?  Anything to know about this especially when using with Cordova app running on IOS?

Thanks

**Comment by jmklix** [comment]
Hello tronious, we don't currently support this as we don't have the binaries for IOS devices.

I recommend taking a look at AWS Amplify (https://aws.amazon.com/amplify/) to see if that will satisfy your use case.
