### ISSUE TITLE
Errors always logged to stderr when connecting with `MqttClient`

### ISSUE THREAD

**Issue by marcogrcr** [aws/aws-iot-device-sdk-js-v2#75]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?

- **OS:** Mac OS X 10.14.6
- **Node:** v12.13.0
- **aws-iot-device-sdk-v2:** 1.2.3
- **aws-crt:** 1.1.9

**Describe the question**

I have the following code to connect to IoT Core's MQTT Service Broker:

```js
const { io, iot, mqtt } = require("aws-iot-device-sdk-v2");

(async () => {
  const certPem = "...";
  const privateKeyPem = "...";

  const config = iot.AwsIotMqttConnectionConfigBuilder
    .new_mtls_builder(certPem, privateKeyPem)
    .with_endpoint("<prefix>-ats.iot.<region>.amazonaws.com")
    .with_client_id("...")
    .build();

  const client = new mqtt.MqttClient(new io.ClientBootstrap())
    .new_connection(config);

  await client.connect();
})();
```

Whenever I run this code, the client connects successfully, but the following always gets logged to `stderr`:

```
[ERROR] [yyyy-MM-ddThh:mm:ssZ] [...] [socket] - id=<id1> fd=<fd1>: connect failed with error code 65.
[ERROR] [yyyy-MM-ddThh:mm:ssZ] [...] [channel-bootstrap] - id=<id2>: failed to create socket with error 1049
```

After doing some digging, I was able to identify that these error messages are coming from the native-C libraries:

https://github.com/awslabs/aws-c-io/blob/cf9dbd744f56eccc00bd3f9c4e7ba283949e1a28/source/posix/socket.c#L656-L661

It seems the `socket.c` file is using the [`connect(2)`](https://man7.org/linux/man-pages/man2/connect.2.html) sys call. According to [`errno.h`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/asm-generic/errno.h#n48), error code 65 is `ENOPKG` which means `Package not installed`.

My guess is that the code has some sort of fallback where it first tries to use one flavor of sockets (which is not available in Mac OS), and then falls back to an alternative flavor that works. Hence I always see the error, but the connection works just fine. **Can you confirm that this is correct?** If so, **Is there a way to disable/configure the logging from the C libraries?**

https://github.com/awslabs/aws-c-io/blob/cf9dbd744f56eccc00bd3f9c4e7ba283949e1a28/source/channel_bootstrap.c#L575-L579

As per `channel_bootstrap.c`, it seems error `1049` is an AWS-specific error. **Where can I find documentation on these error codes?**

My guess is that this log is the result of a "`catch`" of the previous error, hence they're always accompanied by one another. **Can you confirm this is correct?**

**Comment by KaibaLopez** [comment]
Hi @marcogrcr ,
So this is a kind of known issue for the crt, and it happens (in very few words) because it sends 2 connection attempts and takes the first one, so the second one fails and throws the error.... In reality it should not throw an error unless both fail but yea, we are working on it.
For now, you can ignore the error message and continue using it. I'll keep this issue open as a way to update you when that is fixed.
