### ISSUE TITLE
SDK Assistance (Angular 9)

### ISSUE THREAD

**Issue by InspectorGadget** [aws/aws-iot-device-sdk-js-v2#77]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Ionic 5 (Angular 9), aws-iot-device-sdk-v2, MacOS Catalina

Node: 12.16.2
NPM: 6.14.7

**Describe the question**
Hi,

I have read the basic PubSub docs & Examples here (multiple times), and been trying to understand the basic flow of it. Would you mind showing me the way towards how to properly establish the connection to AWS IoT via MQTT, and one example of Sub? 

Here's what I have, and stuck in confusion.
```
import { Injectable } from '@angular/core';
import { iot } from 'aws-iot-device-sdk-v2';

@Injectable({
  providedIn: 'root'
})
export class AWSIoTService {

  constructor() { }

  async connect() {
    let config = null;
    config = iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path('file.private.key', 'file.cert.pem')
      .with_certificate_authority_from_path('root-CA.crt')
      .with_port(8863)
      .with_endpoint('xxxx-ats.iot.ap-southeast-1.amazonaws.com')
      .build();
    console.log('Main');
  }
}
```

```
ERROR in node_modules/aws-crt/dist/native/auth.d.ts:5:8 - error TS1192: Module '"/Users/raeveen/Documents/client/node_modules/aws-crt/dist/native/binding"' has no default export.

5 import crt_native from './binding';
         ~~~~~~~~~~
node_modules/aws-crt/dist/native/http.d.ts:5:8 - error TS1192: Module '"/Users/raeveen/Documents/client/node_modules/aws-crt/dist/native/binding"' has no default export.

5 import crt_native from './binding';
```

```
ERROR in ./node_modules/aws-crt/dist.browser/browser/http.js
Module not found: Error: Can't resolve '@awscrt/io' in '/Users/raeveen/Documents/Ionic Development/quix/quix-admin-dashboard/node_modules/aws-crt/dist.browser/browser'
```

Appreciate your time and assistance for a small kick start.

**Comment by InspectorGadget** [comment]
Hi @KaibaLopez,

Would sincerely appreciate your assistance. 

Thanks!

**Comment by KaibaLopez** [comment]
Hi @InspectorGadget ,
Sorry for the slow response here.
I have not been able to reproduce your exact error but I can see a couple things on your code:
* `new_mtls_builder_from_path('file.private.key', 'file.cert.pem')` the values are swapped.
* You do need to set a client ID and it has to be unique per device: `.with_client_id(argv.client_id)`.

Now I'm not sure if you have it later on your code, but the connection isn't stablished until you have an mqtt client create the connection: 
```
const config = config_builder.build();
const client = new mqtt.MqttClient(client_bootstrap);
const connection = client.new_connection(config);
```
Let me know if this is making sense for you, or if I misunderstood the problem?

**Comment by InspectorGadget** [comment]
Hi @KaibaLopez,

Thank you for your response.

I have duly understood on the configurations and the need of a Client to establish a MQTT Connection in order to PubSub.

The issue I'm facing is some or rather weird, as you can see with the error I published. It even starts to error when I tried to console log the config (without having the others). - @awscrt/io and the default binding.

I've tried several methods, but yet to find a exact solution towards this.

As such, I've quickly made a "test" project on the same Framework/environment my main project is on.

https://raeveen-personal.s3-ap-southeast-1.amazonaws.com/test.zip

1. npm i
2. ng s
3. The logic for the connection is inside /src/app/home/home.page.ts

Please do try on this project, and let me know if you could find any lead.

Thanks

**Comment by KaibaLopez** [comment]
Hi @InspectorGadget,
I'm afraid I'm not familiar with Angular, so I'm getting what I think are a lot of unrelated problems when I try to run your test. 
The first ones I managed to get working by adding imports to polyfills.js:
```
(window as any).global.Buffer = (window as any).global.Buffer || require('buffer').Buffer;
import * as process from 'process';
window['process'] = process;
```
I'm still trying to get it to work but thought I'd give you an update on it.
Right now I'm having troubles importing some functions, for example using `AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path` throws this error:
```
TypeError: aws_iot_device_sdk_v2__WEBPACK_IMPORTED_MODULE_2__.iot.AwsIotMqttConnectionConfigBuilder.new_mtls_builder_from_path is not a function
```
While `AwsIotMqttConnectionConfigBuilder.new_mtls_builder` seems to work, I fail later on trying to create a new connection.
So yea let me know if you're passed this steps, I have yet to reproduce your initial error.

**Comment by InspectorGadget** [comment]
Hi @KaibaLopez,

Thank you for your response.

As an update, I got my Web App working with aws-crt package as it has Browser dist in it. I am using `iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()` for it to work. As such, I am facing an issue where the WSS is showing Status Code of 101 which means that the protocol must be changed to WSS and then connect to IoT - It only shows this rather than firing the `connect` event. 

```
async connect_websocket() {
    return new Promise<mqtt.MqttClientConnection>((resolve, reject) => {
      const config = iot.AwsIotMqttConnectionConfigBuilder.new_builder_for_websocket()
        .with_clean_session(true)
        .with_client_id('test1')
        .with_keep_alive_seconds(20)
        .with_endpoint('xxxxxxxxxx-ats.iot.ap-southeast-1.amazonaws.com')
        .with_credentials('ap-southeast-1', 'xxxx', 'xxxxxxxx_secret')
        .with_use_websockets()
        .build();

      console.log('Connecting websocket...');
      const client = new mqtt.MqttClient();

      const connection = client.new_connection(config);
      connection.on('connect', (session_present) => {
        resolve(connection);
      });

      connection.on('interrupt', (error: CrtError) => {
        console.log(`Connection interrupted: error=${error}`);
      });

      connection.on('resume', (return_code: number, session_present: boolean) => {
        console.log(`Resumed: rc: ${return_code} existing session: ${session_present}`);
      });

      connection.on('disconnect', () => {
        console.log('Disconnected');
      });

      connection.on('error', (error) => {
        reject(error);
      });

      connection.connect();
    });
```

I am using aws-crt version 1.1.4 because the newer versions are broken with one import not being in place. [GH Pull Request](https://github.com/awslabs/aws-crt-nodejs/pull/112).

Could you advise me if you have any findings?

**Comment by KaibaLopez** [comment]
Ok, new update.
I've managed to get it to work there is a few things that I had to change besides the ones I mentioned on the comment above.

So, the issue is that some methods and classes are just not browser compatible, like 'new_mtls_builder_from_path' for example, the only way I found to establish a connection is through new_with_websockets, so that would change the code a bit:
```
ngOnInit() {
    const client_bootstrap = new io.ClientBootstrap();
    const myClient = iot.AwsIotMqttConnectionConfigBuilder
      .new_with_websockets({
        region: region,
        credentials_provider: undefined, //Credential provider is part of auth which isn't available for browser.
        proxy_options: undefined
    });
    let config = myClient.with_client_id(someId) // unique ClientId for each connection.
    .with_credentials(region, accessId, privateKey, '') //because we had no credentials provider set, we have to manually add them, I recommend using cognito.
    .with_endpoint('xxxxxx-ats.iot.region.amazonaws.com')
    .build();
    const client = new mqtt.MqttClient(client_bootstrap);
    const connection = client.new_connection(config);
    connection.connect();
  }
```
This way i got a connection established using the sample you provided,  I know it is not yet a pub_sub yet but I hope it helps you get there and let me know if you need some other help with that. Also, I never encountered the error from the original post, was that also happening on your the sample code you provided? Does it keep happening after the changes I suggested?

**Comment by InspectorGadget** [comment]
Hi @KaibaLopez,

I went ahead and tried your suggestion.

Here's the code after following your guide above:

```
ngOnInit() {
    const clientBootstrap = new io.ClientBootstrap();

    const myClient = iot.AwsIotMqttConnectionConfigBuilder
      .new_with_websockets({
        region: 'ap-southeast-1',
        credentials_provider: undefined,
        proxy_options: undefined
      });

    const config = myClient.with_client_id('wsssss')
      .with_clean_session(true)
      .with_credentials('ap-southeast-1', 'xxxx', 'xxxx', '')
      .with_endpoint('xxxx-ats.iot.ap-southeast-1.amazonaws.com')
      .build();

    const client = new mqtt.MqttClient(clientBootstrap);

    const connection = client.new_connection(config);

    connection.on('connect', (session_present) => {
      console.log(session_present);
      console.log('connected');
      connection.subscribe('/test/me/senpai', mqtt.QoS.AtLeastOnce, (topic, payload) => {
        const decoder = new TextDecoder('utf8');
        const message = decoder.decode(payload);
        console.log(`message received: topic=${topic} message=${message}`);
      }).then(subscription => {
        return connection.publish(subscription.topic, 'NOTICE ME', subscription.qos);
      });
    });

    connection.connect();
  }
```

The results are very intermittent, here are my findings:

1. There was the @aws-crt issue with the package where it can't resolve the bindings. I've went ahead and solved this, but still needs a fix from the Package itself.
2. The package's compilation isn't binding with Webpack, the connection establish with PubSub on and off. Here's an example:

In this screenshot, it establishes the connection on initial `ng s` run.
![Screenshot 2020-08-13 at 9 46 04 AM](https://user-images.githubusercontent.com/20971020/90085151-d12d9d00-dd49-11ea-8990-90c8d27ed7a0.png)

In this screenshot, it doesn't do that when I reload the page.
![Screenshot 2020-08-13 at 9 46 46 AM](https://user-images.githubusercontent.com/20971020/90085189-e9052100-dd49-11ea-8e91-daa2182310ef.png)

Please advise

**Comment by InspectorGadget** [comment]
Hi @KaibaLopez,

I can now confirm that this issue is now resolved. 

The latest release in aws-crt did the trick.

Thank you for your assistance.

**Comment by 3AGSystemsShervin** [comment]
Hi team,

I could not find any working example for Angular 9 for subscribing and publishing to AWS IOT so any help would be greatly appreciated. I have been trying to follow this example to establish a connection and subscribe to a specific topic. I'm also using Angular 9 but on a windows 10 OS. I have added the latest code mentioned here to my component but I get an error as soon as I uncomment the first line of code ( const clientBootstrap = new io.ClientBootstrap()). 


Also when I add the suggested code to my polyfills.ts it gives a error below so I tried the code without making any changes to my polyfills.ts and import statements are not giving any errors and it compiles successfully. 
(polyfills.ts:20 Uncaught TypeError: Cannot read properties of undefined (reading 'Buffer'). 
    at Module../src/polyfills.ts (polyfills.ts:20)
    at __webpack_require__ (bootstrap:84)
    at Object.2 (polyfills.ts:22)
    at __webpack_require__ (bootstrap:84)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at polyfills.js:1s)  

One thing to mention is for my project setup its recommended that I use Yarn however I have added other libraries using NPM and I have not had any issues mixing the two for installing libraries on same project. Not sure if that matters but I figured I mention it here

 Below are the details to my environment, code and error I get :

**Environment**

Angular 9, aws-iot-device-sdk-v2, Windows 10 

Node: 12.17.0
NPM: 6.14.4

**Code**

import { io, iot, mqtt } from 'aws-iot-device-sdk-v2';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class AWSIoTService {

  constructor() { }

  ngOnInit(): void {


    const clientBootstrap = new io.ClientBootstrap();

    // const myClient = iot.AwsIotMqttConnectionConfigBuilder
    //   .new_with_websockets({
    //     region: 'ap-southeast-1',
    //     credentials_provider: undefined,
    //     proxy_options: undefined
    //   });

    // const config = myClient.with_client_id('wsssss')
    //   .with_clean_session(true)
    //   .with_credentials('ap-southeast-1', 'xxxx', 'xxxx', '')
    //   .with_endpoint('xxxx-ats.iot.ap-southeast-1.amazonaws.com')
    //   .build();

    // const client = new mqtt.MqttClient(clientBootstrap);

    // const connection = client.new_connection(config);

    // connection.on('connect', (session_present) => {
    //   console.log(session_present);
    //   console.log('connected');
    //   connection.subscribe('/test/me/senpai', mqtt.QoS.AtLeastOnce, (topic, payload) => {
    //     const decoder = new TextDecoder('utf8');
    //     const message = decoder.decode(payload);
    //     console.log(`message received: topic=${topic} message=${message}`);
    //   }).then(subscription => {
    //     return connection.publish(subscription.topic, 'NOTICE ME', subscription.qos);
    //   });
    // });

    // connection.connect();

  }
}

**Error**

ERROR Error: Uncaught (in promise): ReferenceError: exports is not defined
ReferenceError: exports is not defined
    at Module../node_modules/aws-iot-device-sdk-v2/dist/iotidentity/iotidentityclient.js (app-main-main-module.js:36927)
    at __webpack_require__ (runtime.js:85)
    at Object../node_modules/aws-iot-device-sdk-v2/dist/index.js (app-main-main-module.js:36777)
    at __webpack_require__ (runtime.js:85)
    at Module../src/app/main/logicalunitview/logicalunitview.component.ts (app-main-main-module.js:151715)
    at __webpack_require__ (runtime.js:85)
    at Module../src/app/main/main-routing.module.ts (app-main-main-module.js:152268)
    at __webpack_require__ (runtime.js:85)
    at Module../src/app/main/main.module.ts (app-main-main-module.js:152373)
    at __webpack_require__ (runtime.js:85)
    at resolvePromise (polyfills.js:13260)
    at resolvePromise (polyfills.js:13203)
    at polyfills.js:13329
    at ZoneDelegate.invokeTask (polyfills.js:12710)
    at Object.onInvokeTask (vendor.js:109700)
    at ZoneDelegate.invokeTask (polyfills.js:12710)
    at Zone.runTask (polyfills.js:12460)
    at drainMicroTaskQueue (polyfills.js:12926)
