### ISSUE TITLE
How can I package the sdk with browserify to use it in web apps? I could do this in the version 1 of the SDK.

### ISSUE THREAD

**Issue by Bogatinovski** [aws/aws-iot-device-sdk-js-v2#82]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Windows 10, Chrome web browser

**Describe the question**
I am trying bundle the sdk v2 using browserify into a single javascript file which I can then use to include the SDK in my AngularJs application. In the previous version of the SDK this was possible out of the box by using the pre-made scripts. The documentation of this process is here: [https://github.com/aws/aws-iot-device-sdk-js#browser-applications](https://github.com/aws/aws-iot-device-sdk-js#browser-applications) 
In the new SDK I don't see a way how to do this. I want to upgrade the the v2 sdk so I can use the new feature for Persistent Sessions.
How can I do this ?

**Comment by Bogatinovski** [comment]
I found the answer in the documentation pages of AWS, on the following link: [https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up.html](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up.html)

**Comment by bretambrose** [comment]
As a followup, the the crt package that the v2 sdk depends on has some browser issues that I am working through now.  Depending on what version you are working on, you may want to wait for all the fixes to get published.

**Comment by Bogatinovski** [comment]
@bretambrose Currently I am using package aws-crt: "^1.1.11". Is this the troublesome package version ? When will the fixes get published ? Thanks for the heads up!  
Btw I figured out I also need to include the crt package the hard way. I had to install the package using `npm install aws-crt` and then I had to use browserify to export it as globally available object by writing `browserify node_modules/aws-crt/dist.browser/browser.js --standalone AwsCrt -o aws/aws-crt-bundle.js`. Finally I could access the crt object from the global scope by the name of `AwsCrt`.

**Comment by bretambrose** [comment]
Yes I believe that version suffers from the issues I'm looking into.  It looks like things got a bit broken when we unified the browser and node interfaces.  Here's what I'm fixing:

1. the samples failed to browserify (https://github.com/awslabs/aws-crt-nodejs/issues/117)
1. the http sample didn't get updated to the new unified interface
1. bugs in the browser implementation of http.ts
1. bug in unpacking corked event arguments causing everything other than the first argument to be undefined

All of these are fixed locally, but I am still tracking down an issue with the pub_sub sample where the websocket connection completion callback is not getting fired and it's unclear why.  As soon as that gets resolved, I'll push everything up, get it reviewed, and cut new releases of the crt and the sdk.

**Comment by bretambrose** [comment]
https://github.com/awslabs/aws-crt-nodejs/pull/118

**Comment by bretambrose** [comment]
Browser issues are hopefully addressed with the latest release yesterday.
