### ISSUE TITLE
NAPI issue while importing the module 

### ISSUE THREAD

**Issue by ClementMarrast** [aws/aws-iot-device-sdk-js-v2#86]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Hardware/Device**
NodeJS version v10.15.1 running on Windows computer

**Describe the question**
While importing the module, I have the following error:
`Error: The AWS CRT native implementation requires that NAPI version 4 be present. Please upgrade to node >=10.13.0, or use the provided browser implementation.`

It seems I'm not the only one, but he didn't get any response:
https://stackoverflow.com/questions/62880214/get-aws-cli-autocompletion-in-windows-cmder?noredirect=1#comment111196026_62880214

Any help on this issue would be greatly appreciated.
Thanks

**Comment by rccarper** [comment]
Hello!  There appears to be a typo with the needed node version--we'll fix that.  It looks like the NodeJS version required is actually v10.16.0.

**Comment by rccarper** [comment]
We recently merged in a fix for the typo; the error message should mention the correct version in the next release.  If you're still encountering an upgrade message even with v10.16.0, just let us know.

**Comment by TingDaoK** [comment]
The new release with the fix is out
