### ISSUE TITLE
Cannot find module aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-iot-device-sdk-v2/dist/index.js'. 

### ISSUE THREAD

**Issue by robertstumpe** [aws/aws-iot-device-sdk-js-v2#88]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
sample/node/pub_sub fails to start:
Error: Cannot find module '/home/<myuser>/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-iot-device-sdk-v2/dist/index.js'. Please verify that the package.json has a valid "main" entry 

**SDK version number**
1.3.0

**Platform/OS/Hardware/Device**
What are you running the sdk on?
OS Version: Ubuntu 16.04.2 LTS
node verson: v12.18.2

**To Reproduce (observed behavior)**
Follow AWS Docs here: https://docs.aws.amazon.com/iot/latest/developerguide/using-laptop-as-device.html

I did following (after created ~/cert as recommended):
```
cd ~/
npm install aws-crt
npm install aws-iot-device-sdk-v2
git clone https://github.com/aws/aws-iot-device-sdk-js-v2.git
cd ~/aws-iot-device-sdk-js-v2/samples/node/pub_sub
npm install
node dist/index.js --topic topic_1 --root-ca ~/certs/Amazon-root-CA-1.pem --cert ~/certs/device.pem.crt --key ~/certs/private.pem.key --endpoint <my-iot-endpoint>
```
This results in:

`Error: Cannot find module '/home/<myuser>/aws-iot-device-sdk-js-v2/samples/node/pub_sub/node_modules/aws-iot-device-sdk-v2/dist/index.js'. Please verify that the package.json has a valid "main" entry `

**Expected behavior**
```
Publish received on topic topic_1
{"message":"Hello world!","sequence":1}
Publish received on topic topic_1
{"message":"Hello world!","sequence":2}
Publish received on topic topic_1
{"message":"Hello world!","sequence":3}
```

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
const level : io.LogLevel = parseInt(io.LogLevel[argv.verbosity.toUpperCase()]);
io.enable_logging(level);
```

**Additional context**

If I don't run `npm install aws-iot-device-sdk-v2` in ~/,  `npm install in ~/aws-iot-device-sdk-js-v2/samples/node/pub_sub` fails too:
`index.ts:6:43 - error TS2307: Cannot find module 'aws-iot-device-sdk-v2`. Even a -g option des not help. I have to run it in ~/.

I took a look to the commit logs and noticed that the package.json files were changed with the last commit. There is a relative path now:

 "aws-iot-device-sdk-v2": "../../../"

If use the latest version number here:
 "aws-iot-device-sdk-v2": "1.3.0"

it works fine.

**Comment by TingDaoK** [comment]
Thank you for reaching out. Yeah, it's true that If you install the package via npm, the relative path will not work.
However, we don't want to the version under the samples get behind of the current release.

We added the note to our README. So if you install the package via npm, you will need to make change to the package.json a little bit to make it work.

**Comment by ericYagerPractice** [comment]
Made the change, still doesn't work.
