### ISSUE TITLE
Cant find module aws-crt-nodejs when running in browser env

### ISSUE THREAD

**Issue by stefan-karlsson** [aws/aws-iot-device-sdk-js-v2#92]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
Failing to find module when running Jest tests.

Also this lib can't be run in a browser

**SDK version number**
```
"aws-crt": "^1.3.0",
"aws-iot-device-sdk-v2": "^1.3.1",
```

**Platform/OS/Hardware/Device**
Windows 10

**Expected behavior**
The build should be successful and able to run in a browser environment.

**Logs/output**

```
 Cannot find module 'C:\Development\xx\Projects\xx\node_modules\aws-crt\dist\bin\win32-x64\aws-crt-nodejs' from '../../node_modules/aws-crt/dist/native/binding.js'

    Require stack:
      C:/Development/xx/Projects/xx/node_modules/aws-crt/dist/native/binding.js
      C:/Development/xx/Projects/xx/node_modules/aws-crt/dist/native/crt.js
      C:/Development/xx/Projects/xx/node_modules/aws-crt/dist/index.js
      C:/Development/xx/Projects/xx/node_modules/aws-iot-device-sdk-v2/dist/greengrass/discoveryclient.js
      C:/Development/xx/Projects/xx/node_modules/aws-iot-device-sdk-v2/dist/index.js
      src/lib/clients/aws-ws-client.ts
      src/lib/clients/aws-ws-client.spec.ts

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:307:11)
      at Object.<anonymous> (../../node_modules/aws-crt/lib/native/binding.js:40:19)
```

**Comment by bretambrose** [comment]
Can you supply the command line and an empty project skeleton via zip which show both of the issues?
