### ISSUE TITLE
More useful error messages

### ISSUE THREAD

**Issue by mangelino** [aws/aws-iot-device-sdk-js-v2#93]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js-v2/issues) and didn't find any solution
  
**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
I build a connection manually since I need to  use a custom authorizer. 
I use Javascript, and do not get the strong typing and checks provided by TypeScript. 
I forgot to set the `socket_options` parameter.
The error returned on `connection.connect()` is

```
CrtError: TypeError: Cannot read property 'native_handle' of undefined
    at /Users/angmas/Projects/jwt-iot-custom-authorizer/node_modules/aws-crt/dist/native/mqtt.js:331:36
```

**SDK version number**
1.3.1

**Platform/OS/Hardware/Device**
What are you running the sdk on?
macOS

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
```
const client_bootstrap = new device.io.ClientBootstrap();
        const tls_ctx_options = new device.io.TlsContextOptions();
        const tls_ctx = new device.io.TlsContext(tls_ctx_options);

        function addCustomAuthHeaders (request, done) {
            console.debug(request);
            request.headers['X-Amz-CustomAuthorizer-Name'] = argv.authorizer;
            request.headers['X-Amz-CustomAuthorizer-Signature'] = s;
            request.headers['token'] = t;
            done();
        }

        const client = new device.mqtt.MqttClient(client_bootstrap);

        const connection = client.new_connection({
            client_id: argv.id,
            host_name: argv.endopoint,
            port: 443,
            clean_session: true,
            tls_ctx: tls_ctx,
            use_websocket: true,
            websocket_handshake_transform: addCustomAuthHeaders
        });
```
**Expected behavior**

Specific error indicating the missing parameter
**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
const level : io.LogLevel = parseInt(io.LogLevel[argv.verbosity.toUpperCase()]);
io.enable_logging(level);
```

```
CrtError: TypeError: Cannot read property 'native_handle' of undefined
    at /Users/angmas/Projects/jwt-iot-custom-authorizer/node_modules/aws-crt/dist/native/mqtt.js:331:36
```

**Additional context**

**Comment by jmklix** [comment]
We have noted this feature request and will let you know when it has been added. You can also make the changes yourself and submit a PR. Make sure to take a look at our [Contributing Guidelines](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/master/CONTRIBUTING.md) before doing so.

**Comment by bretambrose** [comment]
Is this running in the browser or nodejs?

**Comment by massi-ang** [comment]
NodeJs

**Comment by jmklix** [comment]
After discussing with my team this is not a feature request, but is a bug, sorry for my incorrect change.

**Comment by jmklix** [comment]
Can you list out what errors that you would like better error messages for?

**Comment by massi-ang** [comment]
The error message should help me find the root cause of the problem and possibly fix my code. The current error message `CrtError: TypeError: Cannot read property 'native_handle' of undefined` is cryptic and cannot be related to anything I wrote in my own code.

**Comment by TwistedTwigleg** [comment]
Thank you for making this issue! This issue should be fixed by https://github.com/awslabs/aws-crt-nodejs/pull/414 - and should be included in the next Javascript V2 release.
