### ISSUE TITLE
Implement the raw-pub-sub client sample as in the CPP sdk

### ISSUE THREAD

**Issue by massi-ang** [aws/aws-iot-device-sdk-js-v2#95]
**Is your feature request related to a problem? Please describe.**

I would like to have examples on how to use MQTT connections with username and password, or custom headers on WSS to interact with a custom authorizer

**Describe the solution you'd like**
Provide a sample implementation in TS/Javascript of the raw-pub-sub client from the CPP SDK

**Describe alternatives you've considered**
Write the code myself based on the CPP code, but I would not have time to maintain it

**Additional context**

**Comment by bretambrose** [comment]
As per the other ones, this is something we need to do, but I don't know when we'll have a chance.

**Comment by anselpeters** [comment]
@bretambrose I know your team is busy but a quick example on how to pub/sub in the browser with websockets and custom authorizers would really help right now..  I've been struggling for days (weeks?)  Ideally I'm looking to pass a custom token to my custom authorizer but for the life of me can't figure out how to make it work.

**Comment by massi-ang** [comment]
@anselpeters you can look at this sample application https://github.com/aws-samples/aws-iot-enhanced-custom-authorizer-demo

**Comment by anselpeters** [comment]
Thanks @massi-ang, I have spent a bunch of time working with that sample over the last few weeks however it uses Amplify and from what I can tell requires an AWS profile(which i am trying to avoid) and (more importantly to me) doesn't support proxies.

I am able to successfully publish via curl/https using the authorizer however I need to be able to use a single token to connect/pub/sub.

**Comment by massi-ang** [comment]
@anselpeters the demo requires an AWS account to setup the infrastructure, but the App connects to AWS IoT using a custom authorizer.

**Comment by jmklix** [comment]
Update: This is an example that we are still interested in adding but we have not gotten to it yet. We will update in the future if our priorities change. 

This is something that should be added to CI to improve our testing
